### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#101]
Pagination consists of a ```<ul>``` with buttons as ```<li>``` and can be computed by giving a range. Thus I propose a custom element which we can enhance with callbacks such as ```onNext```, ```onPageChanged``` etc.

Usage example:
```html
<md-pagination md-pages="5" md-show.prev.next="true" md-show-first-last="false" md-on-page-changed.delegate="handlePageChange()">
</md-pagination>
```

Which translates to:
```html
  <ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>
```

Inspired by: http://krescruz.github.io/angular-materialize/#pagination

**Comment by Thanood** [comment]
Maybe we can rename this to ```md-paging```..
We could also make a templateController (is that right?) out of this custom element and provide some templating for the generated ```<li>```s:

```html
<md-paging>
  <!-- this would be repeated n times with ${page} set by the component -->
  <!-- "wordify" could by anything but as an example I thought of a value converter  which translates a nu,ber into a word, like 1 => one, 2 => two etc -->
  <span>${page | wordify}</span>
</md-paging>
```

**Comment by Thanood** [comment]
When the component is initialized with:
```html
<md-pagination md-pages="5"></md-pagination>
```

Aurelia throws an exception: "Cannot read property 'getCollectionObserver' of null" before reaching ```attached()``` handler.

Using:
```html
<md-pagination md-pages.bind="5"></md-pagination>
```

does not throw this error.

I've not seen this error yet, although I've used bound numbers f.i. in ```md-dropdown``` - but that's a custom attribute. I will try to reproduce this in a plunk.

**Comment by JeroenVinke** [comment]
Aurelia throws an exception: "Cannot read property 'getCollectionObserver' of null" before reaching attached() handler.

do you have the stacktrace that goes with that error? would be interesting to see

**Comment by Thanood** [comment]
It's hard to extract because for some reason I'm only getting "unresolved promise rejection" since last week or so.

**Comment by JeroenVinke** [comment]
so no three dots behind the exception in chrome's console? :cry:

**Comment by Thanood** [comment]
no :(

![image](https://cloud.githubusercontent.com/assets/677826/13401902/3f10c85e-df0e-11e5-9a9b-1c75fb6bf082.png)

I'm not the only one, Even gist.run doesn't give me good trace.

![image](https://cloud.githubusercontent.com/assets/677826/13401881/2b48b4e4-df0e-11e5-980d-dea47f3f094f.png)

**Comment by JeroenVinke** [comment]
bluebird cant be the cause?

**Comment by Thanood** [comment]
TypeError: Cannot read property 'getCollectionObserver' of null
    at Repeat._observeCollection (http://localhost:3000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.0/repeat.js:152:46)
    at Repeat.itemsChanged (http://localhost:3000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.0/repeat.js:99:14)
    at Repeat.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.1.0/repeat.js:70:12)
    at Controller.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2774:24)
    at View.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at View.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at Controller.automate (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2712:12)
    at http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:3733:22
    at run (http://localhost:3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:116:49)
    at http://localhost:3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:130:9
    at MutationObserver.flush (http://localhost:3000/jspm_packages/npm/core-js@2.0.3/modules/_microtask.js:25:7)

**Comment by Thanood** [comment]
I thought that, too. But if I deactivate it, it doesn't get any better.

**Comment by Thanood** [comment]
I have extracted that trace using a breakpoint in es6.promise.js

**Comment by JeroenVinke** [comment]
I have had this error when I did repeat.for on an uninitialized array but this seems different

**Comment by Thanood** [comment]
Yeah, it's initialized. The error occurs between ```constructor()``` (mdPages = 5) and ```attached()```.

**Comment by JeroenVinke** [comment]
can you even iterate over a number with repeat.for? I thought it was just arrays/maps/sets etc

**Comment by JeroenVinke** [comment]
it can't find the collectionobserver because it's not a collection? :D

**Comment by Thanood** [comment]
It's in the Aurelia docs (Cheat Sheet). So it should work.
And it does work if you either give the component a bound value (```md-pages.bind="5"```) or nothing at all.

**Comment by Thanood** [comment]
And I did ```parseInt()``` the value in attached() :smile:

**Comment by Thanood** [comment]
> it can't find the collectionobserver because it's not a collection? :D

That may be the case but I guess it's not intended like that. :smile:

**Comment by JeroenVinke** [comment]
well firstly, it will be a lot of work (and cause a lot of mistakes) if we are responsible for parsing strings to numbers. So it'd be better if people just use `.bind` IMO

secondly, I think reusing the variable may be the cause:

this fails:

```
import { bindable, customElement } from 'aurelia-templating';
import { inject } from 'aurelia-dependency-injection';

@customElement('md-pagination')
@inject(Element)
export class MdPagination {
  @bindable() mdPages = 5;
  activePage = 1;

  constructor(element) {
    this.element = element;
  }

  attached() {
    this.mdPages = parseInt(this.mdPages, 10);
  }
}
```


this is OK:

```
import { bindable, customElement } from 'aurelia-templating';
import { inject } from 'aurelia-dependency-injection';

@customElement('md-pagination')
@inject(Element)
export class MdPagination {
  @bindable() mdPages = 5;
  activePage = 1;

  constructor(element) {
    this.element = element;
  }

  attached() {
    this.mdPages1 = parseInt(this.mdPages, 10);
  }
}
```

note: 

```
  attached() {
    this.mdPages1 = parseInt(this.mdPages, 10);
  }
```

instead of

```
  attached() {
    this.mdPages = parseInt(this.mdPages, 10);
  }
```

and if you iterate over `mdPages1` it does not give an error

**Comment by Thanood** [comment]
Interesting, thanks!
Tbh, I've got parseInt all over the place. :smile: 

Do you think that is intentional or would that be worth opening an issue?

**Comment by Thanood** [comment]
I mean since it works in other cases.

**Comment by JeroenVinke** [comment]
seems to work from bind() instead of attached() :)

**Comment by Thanood** [comment]
Okay, changed it to bind(), thank you.
But I'm still unsure if that's intended. :smile:

**Comment by Thanood** [comment]
closing this and calling pagination done
that templateController idea above is some bonus for later :smile:
