### ISSUE TITLE
Implement chips (tags)

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#105]
Tbh, I find the Materialize implementation lacks a tag editor.
I'd rather like to implement a wrapper for this library: http://henrychavez.github.io/materialize-tags/examples/

**Comment by Thanood** [comment]
Any opinions on that?
Or stay "vanilla" and implement that later as an optional addition?

**Comment by adriatic** [comment]
I would like that you make this decision while keeping two seemingly contradictory criteria in mind:

1. Make Materialize as good as possible - as it will be very popular in Aurelia developers circles
2. Make yourself available for several next projects that will most likely be using Aurelia Materialize bridge

**Comment by Thanood** [comment]
Then I'll keep external dependencies to a minimum for now and have a look later when I've done all the other things.

I'm curious on what these several next projects might be. :smile:
