### ISSUE TITLE
Implement footer (?)

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#113]
I'm not sure how to implement these. Or if it makes sense at all.
If so, this may be sufficient:

```html
<md-footer>
content
</md-footer>
```

or:
```html
<footer md-footer>
</footer>
```

Translating to:
```html
<footer class="page-footer">
</footer>
```

Both are only adding a css class.

**Comment by Ullfis** [comment]
I vote for using this format

```html
<footer md-footer>
</footer>
```

Then the page structure and footer tag is visible for the user.

---

>Note: We use flexbox to structure our html so that the footer is always on the bottom of the page. It is important to keep the structure of your page within the 3 HTML5 tags: __header__, __main__, __footer__.
>
>http://materializecss.com/footer.html

**Comment by Thanood** [comment]
I agree.
On a sidenote, their description is wrong, they don't use flexbox. Maybe they did once.
Anyway, will add it as an attribute.
