### ISSUE TITLE
problems with nesting contents

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#116]
While trying to copy over the ```sample-runner```/```collapse-panel``` functionality from skeleton-bridge I've encountered problems nesting ```<content>```s inside of each other.

Basically this (simplified):
```html
<md-card>
  <!-- <content> for <collapse-panel> -->
  <content></content>
</md-card>
```

md-card:

```html
<template>
   <content></content>
</template>
```

So there is ```content``` injected into collapse-panel which serves as the ```content``` for md-card.

According to [this issue](https://github.com/aurelia/framework/issues/250) there should only be one unnamed content element.

That means, I have been using ```<content>``` wrong, but probably also the ```collapse-panel``` since how I understood this, an unnamed ```<content>``` is some kind of "fallback" for dynamic content. I may have gotten that wrong, though.

I'm wondering how this should be used correctly. I don't know what kind of content users inject into md-card, so I can't use a selector.
In a strict sense, it's the same with collapse-panel. Of course, I could restrict myself to "mark" content with a class and select it in ```content```. I could also create a new custom element ```md-card-content``` which I could then select. But that's not the point, right?

**Comment by Thanood** [comment]
It doesn't even work with:
```html
<content select="#exampleWrap"></content>
```

(that id is just for testing, of course)

**Comment by Thanood** [comment]
I've pushed the (non-working) changes for others to see.
Here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/31164c188ef588a1918346dd2f18a13fd64e4359

The ```md-card``` is commented to make it work. It uses ```<content>```, just like ```collapse-panel```does. The content is not visible if md-card is actually used.

**Comment by adriatic** [comment]
Darn - how is that we do not have issues with that in KendoUI bridge? Too simple nesting? I was hoping at some point to increase the depth - particularly in help section

**Comment by Thanood** [comment]
Yeah, KendoUI bridge and skeleton-bridge have one level of nesting at most, I guess.

**Comment by adriatic** [comment]
We would need more (for RTE) I think so any **reasonable** effort to solve it would make a lot of sense.

**Comment by Thanood** [comment]
Something doesn't add up. Even if I name everything (classes, components, tried them all) it won't display the composed contents.
```<template replaceable part="...">``` won't work either. That just doesn't fit what I've read in the issue I've posted above.

I have to leave it be for now. Will have another look tomorrow.

**Comment by Thanood** [comment]
The following nesting works in a plunk:

```html
<my-container>
  <my-content>this should be visible</my-content>
</my-container>
```

my-container:
```html
<template>
  <content></content>
</template>
```

my-content:
```html
<template>
  <content></content>
</template>
```

http://plnkr.co/edit/XIznzw4DUmfyO0eu5Snq?p=preview

**Comment by Thanood** [comment]
Can anyone have a look, please?
I must have done something wrong - although that would contradict what I've read about nested contents (the issue linked above). Anyway, the plunk does not have this issue.

Fresh eyes see more. Please help.

**Comment by Thanood** [comment]
Okay, at least I can reproduce it now:
http://plnkr.co/edit/XIznzw4DUmfyO0eu5Snq?p=preview

Still, this does not happen everytime. For example with simple html templates (no explicit view model) like the ```my-content``` example in the comment before the previous comment.

I will have another look at it.

**Comment by Thanood** [comment]
That is really confusing...

This kind of nesting works:
```html
<my-container>
  <my-card>
    flat "nested" content
  </my-card>
</my-container>
```

```my-container``` and ```my-card``` both look like:

```html
<template>
  <content></content>
</template>
```

This does not:

```html
<simple-panel title="there should also be content here:">
  simple-panel content
</simple-panel>
```

simple-panel:
```html
<template bindable="title">
  <require from="./simple-card.html"></require>
  <h4>${title}</h4>
  <simple-card>
    <content></content>
  </simple-card>
</template>
```

simple-card:
```html
<template>
  <content></content>
</template>
```

Does that make any sense?

**Comment by Thanood** [comment]
This seems to be a (the only?) possible solution:

sample-runner.html

```html
<collapse-panel>
  <md-card md-title.bind="sample.title">
    <compose view-model.bind="sample.path"></compose>
  </md-card>
</collapse-panel>
```

collapse-panel.html:

```html
<template>
  <div>
    <div class="row">
      <div class="col s12">
        <content select="md-card"></content>
      </div>
    </div>
  </div>
</template>
```

md-card.html (simplified):
```html
<template>
  <content></content>
</template>
```

I think that's a bit unfortunate, I thought ```<content>``` would work differently. I thought it meant "put whatever contents I put in my custom element's innerHTML here" - but apparently it doesn't work that way.

**Comment by Thanood** [comment]
I'm leaving the rest of the samples as they are until I can think again. :smirk:

**Comment by adriatic** [comment]
Jeroen started to build the Github Pages (gh-pages) hosted Materialize bridge today

**Comment by Thanood** [comment]
\ o /
