### ISSUE TITLE
add to JSPM registry

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-materialize-bridge#119]
https://github.com/jspm/registry/blob/master/registry.json

I would use the github endpoint ( we can change this to npm later ):

"aurelia-materialize-bridge": "github:aurelia-ui-toolkits/aurelia-materialize-bridge",

**Comment by adriatic** [comment]
I agree - and believe that @Thanood would too.

**Comment by Thanood** [comment]
done
