### ISSUE TITLE
add to aurelia registry

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-materialize-bridge#120]
https://github.com/aurelia/registry/blob/master/plugin-registry.json

**Comment by Thanood** [comment]
Or edit the existing entry to point to this repo.
https://github.com/aurelia/registry/blob/master/plugin-registry.json#L86

**Comment by JeroenVinke** [comment]
:o I didn't know that was in there

yes that should be aurelia-materialize-bridge instead

**Comment by Thanood** [comment]
That was rather a note to myself than a correction. :smile:

**Comment by Thanood** [comment]
done

**Comment by adriatic** [comment]
You are knocking your tasks off - as if you got infected by @JeroenVinke, making me feel as if I live in a slow motion movie :-)

**Comment by Thanood** [comment]
If that's infectious I won't feel guilty spreading it. :smile:

**Comment by adriatic** [comment]
Unfortunately this infection seems to be limited to spreading in Europe only !

**Comment by Thanood** [comment]
Takes a little time to cross the ocean.
guybedford just merged this into jspm. He's also infected. :smile:
