### ISSUE TITLE
implementing validation

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#126]
During a short discussion with @plea134 (:point_up: [2. März 2016 11:37](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=56d6c2550bdb886502f6a714)) it became apparent that we haven't yet decided upon a strategy on how to implement validation.

Let's discuss this here. @plea134 wanted to come up with a use-case.

**Comment by plea134** [comment]
I created a crude implementation of a custom view strategy for aurelia-validation.  I had to modify the input.js file to accept a string rather than a bool - this is the property to be validated.  Hopefully someone may take this and make it better :)

      MdInput.prototype.attached = function attached() {
      this.mdTextArea = _commonAttributes.getBooleanFromAttributeValue(this.mdTextArea);
        if (this.mdValidate) {
                 this.input.setAttribute('validate-property', this.mdValidate);
      }
      if (this.mdPlaceholder) {
              this.input.setAttribute('placeholder', this.mdPlaceholder);
             this.update();
        }
    };
    
    // example
    <md-input md-type="text" md-label="Username" md-value.bind="login.username | lowerCase" md-validate="username" />

The view strategy did the rest. I had to wait until the attached method to bind the form otherwise the nested views hadn't been generated + bound.

View Stratey below - only issue i have a the moment is styling the error label

    import {ValidationViewStrategy} from 'aurelia-validation';

    export class MaterialValidationViewStrategy extends ValidationViewStrategy {
           private _bindingPathAttribute: string;

           constructor() {
                 super();
                 this._bindingPathAttribute = 'validate-property';
           }    

            getValidationProperty(validation: any, element : any) : any  {
                   var attributes = element.attributes;
                   if (attributes[this._bindingPathAttribute]) {
                         var bindingPath = attributes[this._bindingPathAttribute].value.trim();
                         if (bindingPath.indexOf('|') != -1)
                                   bindingPath = bindingPath.split('|')[0].trim();

                         var validationProperty = validation.result.properties[bindingPath];
                         if (validationProperty === null || validationProperty === undefined) {
                                 validation.ensure(bindingPath);
                          validationProperty = validation.result.properties[bindingPath];
                   }
                   return validationProperty;
              } 
            }

         prepareElement(validationProperty: any, element: any) {
               this.appendUIVisuals(validationProperty, element);
         }

         updateElement(validationProperty: any, element: any) {
               this.appendUIVisuals(validationProperty, element);
         }

         appendUIVisuals(validationProperty: any, element: Element) {
               if (validationProperty) {
                      switch (element.tagName) {
                            case "LABEL":
                                 if (validationProperty.isValid) {
                                        element.classList.remove('invalid');
                                        element.classList.add('valid');
                                       element.removeAttribute('data-error');
                                 } else {
                                        element.classList.remove('valid');
                                        element.classList.add('invalid');
                                        element.setAttribute('data-error', validationProperty.message);
                                 }
                                 break;
                         case "INPUT":
                                 // find label and apply same properties as above
                                var label = $("label[for='" + element.id + "']");
                                if (validationProperty.isValid) {
                                      element.classList.remove('invalid');
                                      element.classList.add('valid');

                                 if (label) {
                                         label.removeClass('invalid');
                                         label.addClass('valid');
                                         label.removeAttr('data-error');
                                  }
                            } else {
                                 element.classList.remove('valid');
                                 element.classList.add('invalid');

                                 if (label) {
                                        label.removeClass('valid');
                                        label.addClass('invalid');
                                        label.attr('data-error', validationProperty.message);
                                 }
                             }
                            break;
                     }
              }
          }
       }

the CSS i'm using (i'm not very profficient with css) - using a relative position for the message meant that it remains visible when the input is not selected - which is what I was after.

    input:not([type])+label, 
    input[type=text]+label, 
    input[type=password]+label, 
    input[type=email]+label, 
    input[type=url]+label, 
    input[type=time]+label, 
    input[type=date]+label, 
    input[type=datetime-local]+label, 
    input[type=tel]+label, 
    input[type=number]+label, 
    input[type=search]+label, 
    textarea.materialize-textarea+label {
        display: inline-block !important;
        width: 100% !important;
        max-width: 1000px !important;
     }

    input:not([type])+label:after, 
    input[type=text]+label:after, 
    input[type=password]+label:after, 
    input[type=email]+label:after, 
    input[type=url]+label:after, 
    input[type=time]+label:after, 
    input[type=date]+label:after, 
    input[type=datetime-local]+label:after, 
    input[type=tel]+label:after, 
    input[type=number]+label:after, 
    input[type=search]+label:after, 
    textarea.materialize-textarea+label:after {
        display: inline-block !important;
        position: relative !important;
        text-overflow: ellipsis !important;
        width: auto !important;
        max-width: 1000px !important;
        top: 0px !important;
        margin-left: 3px !important;
     }

**Comment by Thanood** [comment]
Whoa, thanks! :smile: 
I will definitely have to look at this later when I get home.

**Comment by Thanood** [comment]
Quick status-update: this is an interesting topic. :smile: 
That's a very nice solution, @plea134.

All of this is possible without changing the existing ```md-validate``` attribute and adding ```validation-property``` manually. At least **for now**. So no changes to ```md-input``` are necessary.

I'd even question changing that property since we should *optionally* support html5 validation to not depend on aurelia-validation and to support users who don't want to use it or have existing solutions using Materialize's html5 validation.

We'd somehow have to apply the ```validate``` class to the wrapped input element since users don't have direct access to that element so I think we need such a property.

But ```validation-property``` could become a separate attribute and it would work (may be renamed to fit prefixes of course).

Problem is atm. I've only scratched the surface of aurelia-validation and it is being overhauled. It is certainly possible to do something more "sophisticated" already with the current implementation - f.i. by using custom validation rules, maybe. But who knows when that will change. :smile: 

I'll make a second post with what I've changed and how I applied it. It's basically another ```case``` in the ```switch``` statement of your view strategy.

Btw.: the error message *below* the input stays visible when the input is not selected (focused) - at least for me. Your css makes it appear at the right of the floating label. I'm not sure if that's a good thing according to the Material Design spec (haven't had a look yet).

**Note:** All of the above is without any changes to ```md-input``` at all! @plea134's view strategy leverages the existing possibilities of Materialize and aurelia-validation very well. Maybe we should keep it this way to let aurelia-validate stay in control. That's open for discussion.

If so, then we should provide that view strategy.

**Comment by Thanood** [comment]
Here is what I did:

* grabbed a fresh clone of https://github.com/aurelia-ui-toolkits/materialize-app-developers-tutorial (because it has everything I needed)
* added a new route "validation" (see below)
* copied the view strategy from above into the project
* added the ```MDL-INPUT``` switch case

view:

```html
<template>
  <h4>test validation</h4>
  <div validate.bind="validation">
    <md-input md-label="give me some input" md-value.bind="user.login" validate-property="login"></md-input>
  </div>
</template>

```

view model:

```javascript
import {inject} from 'aurelia-framework';
import {Validation} from 'aurelia-validation';
import {MaterialValidationViewStrategy} from './myViewStrategy';

@inject(Validation, MaterialValidationViewStrategy)
export class Validate {
  user = {
    login: null,
    pass: null
  };

  constructor(validation, viewStrategyInstance) {
    this.validation = validation.on(this.user, config => {
      config.useViewStrategy(viewStrategyInstance);
    }).ensure('login')
        .isNotEmpty()
        .hasMinLength(3);
  }
}
```

So the input has to be at least 3 characters long.

Changes to the view strategy:

```javascript
case "MD-INPUT":
    var input = element.querySelector('input');
    if (input) {
      var label = element.querySelector('label');
      if (validationProperty.isValid) {
          input.classList.remove('invalid');
          input.classList.add('valid');

          if (label) {
              label.removeClass('invalid');
              label.addClass('valid');
              label.removeAttr('data-error');
          }
      } else {
          input.classList.remove('valid');
          input.classList.add('invalid');

          if (label) {
              label.classList.remove('valid');
              label.classList.add('invalid');
              label.setAttribute('data-error', validationProperty.message);
          }
      }
    }
    break;
```

Works like a charm. Apart from the width of the error message being too small.

**Comment by Thanood** [comment]
Some screens:

Without @plea134's css:

![image](https://cloud.githubusercontent.com/assets/677826/13475106/4399f0f8-e0c1-11e5-86c6-88cb26ce6dd2.png)

With @plea134's css:

![image](https://cloud.githubusercontent.com/assets/677826/13475132/648d94c2-e0c1-11e5-9628-bcf305724961.png)

**Comment by adriatic** [comment]
Go  @plea134 - this is a great addition that can certainly "hold water" until next rewrite of aurelia validation

**Comment by plea134** [comment]
Can't take any real credit, just hacked another solution that was added into a now [defunct project](https://github.com/manuel-guilbault/aurelia-materialize).

I know the styling isn't everyones cup of tea, but that's what my boss preferred. I still can't get it to wrap properly on mobile in either case! just made my validation messages shorter for now! :)

**Comment by Thanood** [comment]
Yeah, I know this project (and somehow forgot about it). 

It's very interesting that they link to our old repo now. I didn't know that. :smile: 
@adriatic did you?
Anyway, in that case I think it's okay if we use their view strategy.
I just find it a little strange as this is not a continuation of their project.

I tried to change the styling but I didn't get a nicely looking result. And I was really tired yesterday, tbh. :smile:

**Comment by Ullfis** [comment]
Try this css:
```
label[data-error]:after {
    transition-property: all !important;
    white-space: nowrap;
    font-size: 0.8rem;
    -webkit-transform: translateY(-45%);
    -moz-transform: translateY(-45%);
    -ms-transform: translateY(-45%);
    -o-transform: translateY(-45%);
    transform: translateY(-45%);
}

label[data-error]:not(.active):after {

    -webkit-transform: translateY(-180%);
    -moz-transform: translateY(-180%);
    -ms-transform: translateY(-180%);
    -o-transform: translateY(-180%);
    transform: translateY(-180%);
}
```

**Comment by Thanood** [comment]
Very nice, thanks. :smile: 

![image](https://cloud.githubusercontent.com/assets/677826/13697515/3ff08030-e76e-11e5-8385-4777733c45b7.png)

**Comment by Thanood** [comment]
Now with the release of [`aurelia-validation` alpha](http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/) integrate with it and create a Materialize renderer.

**Comment by Ullfis** [comment]
I did a test on the new validation.

[aurelia-validatejs-materialize-typescript-webpack](https://github.com/Ullfis/aurelia-materialize-skeleton-typescript-webpack/tree/aurelia-validatejs)

**Comment by Thanood** [comment]
Looks really good.
The layout is a little off, though.. I wonder where that comes from.

![image](https://cloud.githubusercontent.com/assets/677826/17673480/979b1f1e-6321-11e6-8a02-959f09960f1b.png)

I'll try a JSPM version and have a look how we can deliver validation without creating a dependency on `aurelia-validation` - that is, if you're okay with it that I'm using your validator. :smile:

**Comment by Ullfis** [comment]
Yeah.. I had some strange styles in a file :1234:

btw.. here are some changes you maybe want to test #231
