### ISSUE TITLE
showdown not defined in demo-materialize

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#129]
After updating the bridge in demo-materialize I tried to circumvent the recent problems with aurelia-polyfills by downgrading to npm:aurelia-polyfills@1.0.0-beta.1.0.1

After that I encountered errors with ```<au-markdown>```:
```ReferenceError: showdown is not defined```

and another I can't seem to reproduce right now, telling me something about ```'Extension "prettify" could not be loaded. It was either not found or is not a valid extension.```

I'm sure I've seen that before but tbh I can't recall it.

**Comment by adriatic** [comment]
That is easy to address as you have even two solutions:

1. Add [markdown module](https://www.npmjs.com/package/markdown) which is being  used to render the .md files defining the texts in `Code View` panel tabs. @JeroenVinke removed that at some point from KendoUI catalog app but I believe that you have not switched to current catalog infrastructure.

2. Upgrade your catalog app to the current KendoUI catalog

**Comment by Thanood** [comment]
I'll try that tomorrow since jspm keeps throwing timeouts again.

But isn't that strange? I didn't remove anything since last week when it still worked. Right, I may not use the latest infrastructure but I also can't remember having changed it. :smile: 

We'll see tomorrow.

**Comment by Thanood** [comment]
After updating jspm again (and thus pulling the fixed polyfills version) it works again.
I had to reactivate babel runtime which I don't need to do locally.
I'm also getting a lot of warnings:
```
Warning: a promise was created in a handler but was not returned from it
```
