### ISSUE TITLE
options of including Materialize

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#13]
There are several options on how to include Materialize in this bridge.

a) which part should import the library?
1. the bridge
2. the catalog (and therefore the user's application)

I'd really like the catalog itself to show a [circular preloader](http://materializecss.com/preloader.html) instead of the font-awesome spinner so the catalog would still use Materialize css because this obviously has to be available before Aurelia starts. What do you think?

b) there are some variations available..
1. ```jspm install materialize=github:github:Dogfalo/materialize```
2. ```jspm install materialize=npm:materialize-css```
3. use a ```vendor``` solution like the [kendo-ui bridge](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation) does

Where...
1) Pulls the bundled and minified version of Materialize into the target and no sources. We cannot alter f.i. SASS files or just import single features with this variant (although I don't believe Materialize is made for "feaure picking" at all tbh). On the other hand this solves a few issues I've come across while experimenting with Materialize. For example toasts needing both a global ```Materialize``` variable, hammerjs and velocityjs to be present. Keep in mind that Materialize is not (yet?) built around any module system.

2) Pulls Materialize source files **and** dist builds. We can read and process SASS files and pick features to import. The SASS files could f.i. be used to create ```primary``` and ```accent``` colors which Materialize has no notion of, but [Material does](https://www.google.com/design/spec/style/color.html#color-ui-color-application). I've already been missing that with the first ```Waves``` sample. Also we could perhaps use the "original" Waves which includes disposing functionality.
But, as stated above, there are some issues to this approach.

3) I'm really not sure if this makes any sense at all since there are no real "editions" of Materialize and the variations noted above only make a difference from a bridge developer's point of view.

Btw: I've read the [Git Commit Guidelines](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/wiki/Development-Protocol) but this issue would fit neither (chore) or (doc) while it also does not discuss a feature I think (or does it?). Which ```<type>``` would fit here?

**Comment by Thanood** [comment]
Having written that (still not finished btw) I realize that perhaps the NPM version is best because it delivers source files and still contains the bundled version.
Please note though that this NPM version had issues in the past, like not containing anything useful at all (most files where missing). Of course, that need not happen again, but I'm mentioning it anyway.

**Comment by adriatic** [comment]
@Thanood - I will address only a subset of the issues you raised here, leaving space to @JeroenVinke as well

> which part should import the library?

**Both** - each side with a slightly different point of view. The bridge of course needs to do it as its only task is to convert third party controls into Aurelia components. The catalog has to import "parts" of the library (like CSS files, as the catalog ought to be in full control of how to render its UI. I will clearly indicate it once I get the chance to add all the code for the **[skeleton bridge](https://github.com/aurelia-ui-toolkits/skeleton-bridge)** task that evades me this whole day :-)

> I'd really like the catalog itself to show a circular preloader instead of the font-awesome spinner so the catalog would still use Materialize css because this obviously has to be available before Aurelia starts. What do you think?

This is a clear problem of bootstraping the project and the reason for my insistence to start with the **"green box" shown below**

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/12378844/f71a83b2-bd18-11e5-8643-4b8517927de3.png"></img>
<br>
</p>

that has only the UI components that are used in Aurelia Skeleton Navigation app (where the Aurelia team provided enough to create any basic Aurelia app without having to have a bridge to something else). Once you have this working, you can add the "circular preloader" as the very first Aurelia Materialize **component** -- and **only then use it in the catalog**. Any other way you will remain wrapped yourself in an unneeded battle with dependencies - and that is the kind of wrapping that is not a part of the bridge development :-)

leaving the rest of my comment for later ...

**Comment by Thanood** [comment]
> Once you have this working, you can add the "circular preloader" as the very first Aurelia Materialize component -- and only then use it in the catalog.

I could do that. But then, as an Aurelia component, it would not be displayed since the point of that "spinner" animation is to show the user something before Aurelia takes control. So this would have to be added before Aurelia takes control.

Of course I could do both: add an Aurelia Materialize component but then not use it (as it makes no sense **at that time**) but use simple css/html and no components.

But it's all not that important. If it doesn't fit in, I'll continue to use the font-awesome spinner. Just thought it'd be nice as a kind of "corporate identity" to show some material even before Aurelia is started.

**Comment by adriatic** [comment]
> But it's all not that important.

I disagree - as I want you to not be constraint by my possible lack of knowledge about Materialize. I am referring to the case where we have not decided what to do "styles only" section of Materialize :

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/12380008/66cf782c-bd35-11e5-9479-3b16b548f8de.png"></img>
 <br>
</p>

This is really the **subject** of our current discussion, which (subject) was settled for Aurelia Navigation Skeleton, the grand-father of all stuff in the "orange box" by including the styles needed to render the `<i class="fa fa-spinner fa-spin"></i>`
into the **[styles.css](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/styles/styles.css)** file.

Thus, your desire to use the circular preloader is a perfect sign of your dedication to ensure the native look and feel, and you should solve it to **add the needed css data** (which you commented out in the **[index.html](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/index.html)** file, into **[styles.css](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/styles/styles.css)**

Making sense?

**Comment by Thanood** [comment]
> Making sense?

I'm not sure since the Aurelia Navigation Skeleton also loads font-awesome before anything else. That file contains the base css for the classes defined in styles.css including f.i. the ```fa-spin``` keyframes.

On the other hand, when you say **both** parts should import Materialize, then this is not a problem at all because it wll be there anyway.

**Comment by adriatic** [comment]
> I'm not sure since the Aurelia Navigation Skeleton also loads font-awesome before anything else

Let me assure you then :-) -- check **[this line](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/index.html#L5)** where font-awesome gets loaded.

**Comment by mandia1204** [comment]
I'm trying to use aurelia materialize-css using the package npm:materialize-css, because I want to use the sass files. 

I added this in config.js to use my sass variables:

packages: {
    "materialize-css": {
      "main": "dist/js/materialize.js",
      "map": {
        "../css/materialize.css": "../../../src/styles/styles.scss"
      }
    }
  },

this works using gulp watch, but with gulp export it fails:

Error: CSS Plugin:
Ignoring local @import of "dist/src/styles/styles.scss" as resource is missing.
    at file:///C:/Users/marvin/Documents/Sistema Restaurant/restaurant-frontend/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13

- I already added 'materialize-css' to bundles file.

Any ideas?

**Comment by Thanood** [comment]
@mandia1204 I'm moving this question to a new issue: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/403
