### ISSUE TITLE
Improve datepicker

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#133]
Try to find a way to include [pickadate translations](https://github.com/amsul/pickadate.js/tree/3.5.6/lib/translations) and easily apply them.

**Comment by nndevstudio** [comment]
This is related to http://stackoverflow.com/questions/43225208/how-to-set-default-mddatepicker-options-translations-for-weekdays-months-fo

I did try but it seems that I miss something.

Is there any recommended approach for overriding default translations? Thanks.

**Comment by Thanood** [comment]
Maybe..
There is an `options` bindable here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L19
That object is merged here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L64

And the result is used to initialize the datepicker here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L76

Now, if you actually visited the links (:smirk:) you may have seen a commented example of an i18n config here (German strings): https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L47-L60

So, if you set the i18n properties in the `options` bindable, it could work..

```html
<input
      md-datepicker="container: body; value.two-way: selectedDate; options.bind:i18nOptions;"
      type="date" placeholder="pick a date"/>
```

Where `i18nOptions` might be:

```js
       selectMonths: true, // Creates a dropdown to control month
       selectYears: 15, // Creates a dropdown of 15 years to control year
       monthsFull: [ 'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember' ],
       monthsShort: [ 'Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez' ],
       weekdaysFull: [ 'Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag' ],
       weekdaysShort: [ 'So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa' ],
       today: 'Heute',
       clear: 'Löschen',
       close: 'Schließen',
       firstDay: 1,
       format: 'dddd, dd. mmmm yyyy',
       formatSubmit: 'yyyy/mm/dd'
```

I didn't test that and I definitely want to make it more explicit.

**Comment by Thanood** [comment]
As for your question

> is there any way to set this properties (defaults) on one place for all instances?

You might share the `i18nOptions` object application-wide.

**Comment by nndevstudio** [comment]
`options.bind:i18nOptions` per instance of MdDatePicker works fine but also this in App.ts: 
`import * as bridge from 'aurelia-materialize-bridge';`
`constructor () { bridge.MdDatePicker.prototype.options = i18nOptions;  }`
so now we have everything on one place for all instances.

Thanks, or i18n:Danke! :+1:

**Comment by Thanood** [comment]
i18n:"Kein Problem, gerne!".. 😄

**Comment by nndevstudio** [comment]
Just to update with first experiences.
After overriding options globally (`MdDatePicker.prototype.options = i18nOptions;`), there is a catch in L177 - https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/datepicker/datepicker.js#L177

> "Cannot read property 'debug' of undefined"
> "TypeError: Cannot read property 'debug' of undefined
>     at Object.valueChanged (http://localhost:9001/jspm_packages/npm/aurelia-materialize-bridge@0.20.6/datepicker/datepicker.js:240:19)
>     at BehaviorPropertyObserver.selfSubscriber (http://localhost:9001/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:3693:48)
>     at BehaviorPropertyObserver.call (http://localhost:9001/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:3559:14)
>     at TaskQueue.flushMicroTaskQueue (http://localhost:9001/jspm_packages/npm/aurelia-task-queue@1.2.0/aurelia-task-queue.js:151:16)
>     at MutationObserver.eval (http://localhost:9001/jspm_packages/npm/aurelia-task-queue@1.2.0/aurelia-task-queue.js:79:24)"
	
But in case of overriding options per instance in view (`options.bind:i18nOptions;`), `this.log `is not undefined so it works as expected.

**Comment by Thanood** [comment]
Hmm, interesting..
I never manipulated the prototype directly and atm I don't understand why this wouldn't work.

It's initialized from the imported `getLogger` function used in the contructor. Maybe that is `undefined` or for some reason returns `undefined`..

**Comment by MaximBalaganskiy** [comment]
Not relevant in the light of v1
