### ISSUE TITLE
catalog app does not load on IE11

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#135]
Kind of a proof that core-js is really gone (#128). :wink: 
`ReferenceError: "Symbol" is undefined`

see https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/127#issuecomment-191682959

**Comment by Grendizr** [comment]
Seems that this one would need to be re-opened.


![image](https://cloud.githubusercontent.com/assets/8410293/17479594/ae5f5cd2-5d73-11e6-8714-1c87a5bb7b7a.png)

**Comment by Thanood** [comment]
Right, looks like it..

It's probably this part:

```javascript
//Configure Bluebird Promises.
Promise.config({
  warnings: {
    wForgottenReturn: false
  }
});
```

That's interesting since bluebird should be loaded before anything else.
Thanks for reporting, I'll have a look.

**Comment by Thanood** [comment]
Also content padding is missing when the side-nav is opened (probably failing media queries).

**Comment by Thanood** [comment]
Well, this works:

```javascript
(Promise.config || P.config)({
  warnings: {
    wForgottenReturn: false
  }
});
```

I have no idea why `window.Promise` doesn't have `config()` but `window.P` does. And that only in IE..
I'd like to investigate this further. Uploading this as a workaround.

**Comment by Grendizr** [comment]
That was fast ^_^

IE is always full of nice gifts like this one !

**Comment by Thanood** [comment]
I'm now getting this with any browser and the reason is: GitPages doesn't deliver bluebird..

**Comment by MaximBalaganskiy** [comment]
Fixed
