### ISSUE TITLE
footer theme color

### ISSUE THREAD

**Issue by Ullfis** [aurelia-ui-toolkits/aurelia-materialize-bridge#142]
Thank you again for this bridge :)

I have added footer css to ./colors/md-colors.html so the footer follow the theme color. But I loose it every time I upgrade the library. Adding class “primary” do not work for me (not sure why). 

If its not in conflict with anything, could you please add it?

_src/colors/md-colors.html_:

```css
  /* footer */
  footer.page-footer {
    background-color: ${mdPrimaryColor};
  }
```

**Comment by Thanood** [comment]
Sure, I will do that.
A better approach would be to have a way to "plug in" to md-colors somehow. I just don't know how.

Maybe we should introduce a custom attribute to be able to have another css selector and not conflict with these unprefixed classes in case somebody wants to use them in another context.

But for now, that's simple enough. :smile:

**Comment by Thanood** [comment]
updated :smile:

**Comment by Thanood** [comment]
Anyway, just as a note to myself:
I should "bundle" releases a little more, I'm not holding to semver very much (releasing a feature with a patch release). :smile:
