### ISSUE TITLE
datepicker selected value issue

### ISSUE THREAD

**Issue by vdangwal** [aurelia-ui-toolkits/aurelia-materialize-bridge#146]
<input type="date" md-datepicker value.bind="selectedDate"/> is not selecting any value and causing 'undefined' issue. I can see the console.log message from this class in dev tool 'selectedChanged undefined'.

**Comment by Thanood** [comment]
Strange, I've never seen that before.. Do you see any other errors?
Can you show a snippet on how you use it?

**Comment by vdangwal** [comment]
no errors :( here is the snippet. 
<input value.two-way="CurrentMeeting.travelDate" id="travelDate" type="date" md-datepicker="container:body;" >

**Comment by Thanood** [comment]
I think you've missed the snippet.. :smile: 

Unfortunately I just noticed that the log output from valueChanged ```selectedChanged undefined``` is outputting the wrong variable so this output is nonsense essentially.

Is that behaviour just from clicking a date on the picker or where does it come from?

**Comment by Thanood** [comment]
Can you try with the current version (0.2.3)? There have been some minor adjustments to DatePicker.

**Comment by vdangwal** [comment]
Sure.

Thanks,
Vikas Dangwal




On Wed, Mar 30, 2016 at 12:21 PM -0700, "Daniel Bendel" <notifications@github.com> wrote:





Can you try with the current version (0.2.3)? There have been some minor adjustments to DatePicker.

---

**Comment by vdangwal** [comment]
Hi Dan,
I have attached couple of screenshots and also below the code snippet how i am using it. Please let me know if you see any issue here? I am still not able to get the selected date set to my property 'travelDate'. 

<div class="form-group col s12 m3 l3">                                                <label for="travelDate" >Travel Date</label>                                                                        <input md-datepicker="container: body;" id="travelDate" type="date" placeholder="pick a date" value.two-way="CurrentMeeting.travelDate"/>                    </div>


Class Declaration:
export class Meeting extends BaseModel {    /**     *     */    constructor() {        super();        this.meetingAttendees=new Array<MeetingAttendee>();    }    /** Primary Key */    id: number;    /** Date Travelled */    travelDate?: Date;

Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 19:23:41 +0000

**Comment by Thanood** [comment]
Unfortunately, I didn't get your screenshots. Maybe it doesn't work if you answer by email, but I don't know.

I've formatted your code a little for me to have a look later. It's getting late actually. :smile: 

```html
<div class="form-group col s12 m3 l3">
  <!--
    <input value.two-way="CurrentMeeting.travelDate" id="travelDate" type="date" class="datepicker" md-datepicker="container:body;" >
    <label for="travelDate" class="active">Travel Date</label>
  -->

  <label for="travelDate" >Travel Date</label>
  <!--
  <input id="travelDate" ak-datepicker="k-value.two-way:CurrentMeeting.travelDate" style="width: 100%" class="validate" required/>
  -->
  <!--
  <input value.two-way="CurrentMeeting.travelDate" id="travelDate"  md-datepicker="container:body;" >
  -->

  <input md-datepicker="container: body;" id="travelDate" type="date" placeholder="pick a date" value.two-way="CurrentMeeting.travelDate"/>
</div>
```

```javascript
export class Meeting extends BaseModel {
  /**     *     */
  constructor() {
    super();
    this.meetingAttendees=new Array<MeetingAttendee>();
  }
  /** Primary Key */
  id: number;
  /** Date Travelled */
  travelDate?: Date;
}
```

Does that work without inheritance? I've read somewhere that bindings don't work with inherited classes. I need to look it up to be sure.

**Comment by vdangwal** [comment]
Thank you. Is there any other way i can send you screenshots? If you dont mind, may be your personal email (wont bother you dont worry). :) 
Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 13:12:38 -0700

**Comment by Thanood** [comment]
daniel.bendel@aureliatools.com

Or paste it into GitHub. :smile:

**Comment by Thanood** [comment]
Oh, that value binding needs to be in the datepicker attribute.

**Comment by Thanood** [comment]
The example in the catalog app actually doesn't show ot. Shame on me.
I'll create an issue to update the catalog.

**Comment by vdangwal** [comment]
you mean md-value.bind="..."? 

Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 13:15:37 -0700

**Comment by Thanood** [comment]
Like this:

```html
<input md-datepicker="container: body; value.two-way: CurrentMeeting.travelDate;" id="travelDate" type="date" placeholder="pick a date" />
```

Sorry for the spam. :smile:

**Comment by vdangwal** [comment]
got you. Let me try that and will let you know if works. 

Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 13:17:56 -0700

**Comment by vdangwal** [comment]
😈 changing code as per your suggestion it works :) However i will have to change the format of the date as my WebAPI rejecting request as not a valid format like below. 
travelDate=Thu Mar 17 2016 00:00:00 GMT-0400 (Eastern Daylight Time)

Thanks,
Vikas Dangwal


From: vdangwal@hotmail.com
To: reply@reply.github.com; aurelia-materialize-bridge@noreply.github.com
Subject: RE: [aurelia-ui-toolkits/aurelia-materialize-bridge] datepicker selected value issue (#146)
Date: Wed, 30 Mar 2016 16:18:28 -0400




got you. Let me try that and will let you know if works. 

Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 13:17:56 -0700

**Comment by Thanood** [comment]
Great!
However, what you get should be a ```Date``` object, not a string. Does that work?
If so, you can of course format it in any way you want (probably ```JSON.stringify``` for WebApi).

**Comment by vdangwal** [comment]
one more thing, when i select the date from picker, it update the UI, but as soon as picker get closed, my control revert back to Today current date. Is it normal? 

Thanks,
Vikas Dangwal


From: vdangwal@hotmail.com
To: reply@reply.github.com; aurelia-materialize-bridge@noreply.github.com
Subject: RE: [aurelia-ui-toolkits/aurelia-materialize-bridge] datepicker selected value issue (#146)
Date: Wed, 30 Mar 2016 16:26:55 -0400




😈 changing code as per your suggestion it works :) However i will have to change the format of the date as my WebAPI rejecting request as not a valid format like below. 
travelDate=Thu Mar 17 2016 00:00:00 GMT-0400 (Eastern Daylight Time)

Thanks,
Vikas Dangwal


From: vdangwal@hotmail.com
To: reply@reply.github.com; aurelia-materialize-bridge@noreply.github.com
Subject: RE: [aurelia-ui-toolkits/aurelia-materialize-bridge] datepicker selected value issue (#146)
Date: Wed, 30 Mar 2016 16:18:28 -0400




got you. Let me try that and will let you know if works. 

Thanks,
Vikas Dangwal


Date: Wed, 30 Mar 2016 13:17:56 -0700

**Comment by Thanood** [comment]
> one more thing, when i select the date from picker, it update the UI, but as soon as picker get closed, my control revert back to Today current date. Is it normal?

No, that's not normal.
Now, that's hard to see from your examples - at least for me.

I sometimes got this with other bindings interfering. For example I had an input connected to a variable which was connected to a progress bar. I couldn't set the progress bar to ```null``` because the input would change it to '' (empty string).

But that's just a guess.

**Comment by Thanood** [comment]
When you close the picker, this is executed:

```javascript
  onClose() {
    let selected = this.picker.get('select');
    this.value = selected ? selected.obj : null;
  }
```

But it's not an explanation. Both my guesses would lead to the control being empty (with value being ```null```).. So your control is set to today but the model is correct? Or is it also set to today?
