### ISSUE TITLE
Typescript Definition file missing

### ISSUE THREAD

**Issue by Ullfis** [aurelia-ui-toolkits/aurelia-materialize-bridge#147]
Hi, it's me again :smile:

I missed the definition file during last update. This should get it back.

```bash
npm install babel-dts-generator --save-dev
```

and 
./build/tasks/babel-options.js:

```javascript

from (line 25):

    plugins: [
      // "babel-dts-generator",
      "syntax-flow",
      "transform-decorators-legacy",
      "transform-flow-strip-types"
    ]


to:

    plugins: [
      ['babel-dts-generator', {
        packageName: paths.packageName,
        typings: '',
        suppressModulePath: true,
        suppressComments: false,
        memberOutputFilter: /^_.*/
      }],
      "syntax-flow",
      "transform-decorators-legacy",
      "transform-flow-strip-types"
    ]


```

And maybe (not tested) add this to .gitignore (new way of building the definition file add 'aurelia-materialize-bridge' folder to the project):

```javascript
aurelia-materialize-bridge
```

**Comment by Thanood** [comment]
Hi @Ullfis :smile: 

Interesting, thanks for sharing this. I'm not familiar with this new way of building the definition file. Is it configurable somehow? Maybe we could just call it "definition" or something more descriptive and keep the generated folder.

**Comment by Thanood** [comment]
It seems to be hard to find any documentation on babel-dts-generator.

**Comment by adriatic** [comment]
@Thanood - I believe that you are aware of this article:https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/3.-Babel-DTS-generator

**Comment by Thanood** [comment]
I am, but there seems to be a new way to configure it. At least with babel6 toolkit.
It creates a directory with the package name in project root. Maybe this is more useful than just "gitignoring" it.

**Comment by Thanood** [comment]
Or maybe that's not so new, I don't know. Of course the plugin config is similar to the old format. But I would like to know if the name of that directory can be configured somewhere. :smile:

**Comment by Thanood** [comment]
This should be fixed in current release (0.2.3).

**Comment by Ullfis** [comment]
Thank you :smile:

It is possible to avoid the directory by doing this:

- revert the change in ./build/babel-options.js to :

```javascript

    plugins: [
      "syntax-flow",
      "transform-decorators-legacy",
      "transform-flow-strip-types"
    ]

``` 

- and add this function:

```javascript

exports.babelDtsGenerator = function() {
    var options = exports.base();
    options.plugins.push(
        ['babel-dts-generator', {
            packageName: paths.packageName,
            typings: '',
            suppressModulePath: true,
            suppressComments: false,
            memberOutputFilter: /^_.*/
        }]);
    return options;
};

```

And then change the build-es6-temp task to:

./build/tasks/build.js

```javascript
gulp.task('build-es6-temp', function () {
    return gulp.src(paths.output + jsName)
      .pipe(to5(assign({}, compilerOptions.babelDtsGenerator())))
      .pipe(gulp.dest(paths.output + 'temp'));
});
```

**Comment by Thanood** [comment]
That's clever, it's going to be generated in the temp directory. Thanks! :smile:
