### ISSUE TITLE
Datepicker not selecting initial value

### ISSUE THREAD

**Issue by Kukks** [aurelia-ui-toolkits/aurelia-materialize-bridge#148]
```
<input element.ref="referenced" md-datepicker="container: body; value.two-way: selectedValue" type="date" placeholder="Placeholder"/>
 ```

where `value` has been a `Date` or a  valid date `string` however the input element does not show the date and upon triggering the popup, it does not select the value specified. Checked the value of the attribute via the aurelia chrome plugin and the value showed to be set.

**Comment by Thanood** [comment]
I'm not sure if I get this right.
You set ```selectedValue``` to a certain date and the input doesn't update. Is that right?

**Comment by Kukks** [comment]
Not just the input element, the datepicker popup ui does not show a selected value. It's as if `selectedValue` is null

**Comment by Thanood** [comment]
It's interesting.. There's a log function called in ```valueChanged```. It works if you set the date via the picker itself. It is not called when value is changed from "outside", so in your example if ```value``` is set via ```this.referenced.value``` in the view model, the ```valueChanged``` callback of the date picker view model is not called.

**Comment by Thanood** [comment]
I could reproduce this and have it fixed in my version.
I will probably release a patch tomorrow, I'm not sure if I will have time for it today.

If you need a workaround, try:
```html
<input md-datepicker.ref="datepicker" element.ref="referenced" md-datepicker="container: body; value.two-way: selectedValue" type="date" placeholder="Placeholder"/>
```

```javascript
someFunction() {
  let date = new Date();
  this.datepicker.picker.set('select', date);
}
```

The ```picker``` property points to the pickadate instance, you can use it directly. It is basically what the fix will be, calling that instance's ```set``` method when the value changes. :smile:

**Comment by Kukks** [comment]
Awesome, thank you! :+1:

**Comment by Kukks** [comment]
On another note, the provided patch does not work if the value that the md-datepicker binds to is set BEFORE the datepicker is created. 

trying to set in the attached method cycle produces a js error saying:
`shim.min.js:2228 Unhandled promise rejection TypeError: Cannot read property 'set' of undefined(…)` with a broken datepicker control() (shows the native unstyled browser datepicker and popup does not come up)


```
    public attached() {
        if ( this.referenced ) {
            this.referenced.picker.set("select", this.selectedValue);
        }
    }
```

**Comment by Thanood** [comment]
The error comes from the fact that you reference the element but you'd need to reference the attribute's view model. That's what ```md-datepicker.ref="datepicker"``` does in the example.

I guess the issue with setting a value before the datepicker is created (never thought of that scenario) can be resolved by checking for a present value in ```attached()```. I will try that and build it into the bridge if it works.

**Comment by Thanood** [comment]
Thinking about it, I guess prepopulating the datepicker input is tricky. Datepicker handles not only the input's displayed value but also the raw data (a Date object of course) behind it and the connection to the visual datepicker.

So, the output of Materialize datepicker is actually something different than the ```Date``` constructor will expect. It's a formatted, human readable format (which is also configurable). That makes it heavily dependant on what exactly the input is prefilled with.

Having said that, I guess we could just try and let ```new Date()``` parse it and throw a meaningful exception if it fails.

**Comment by Kukks** [comment]
That would probably be the most reasonable way of handling it. :)
