### ISSUE TITLE
Datepicker binding

### ISSUE THREAD

**Issue by rosshigh** [aurelia-ui-toolkits/aurelia-materialize-bridge#149]
I'm trying to bind a value to the datepicker and not getting the date to appear:  My datepicker looks like this:

<input md-datepicker="container: body; value.bind: startDate" type="text" class='date-picker' placeholder="Start Date" md-label="Start Date"></input>

It works when I pick a date from the datepicker but if I set the date in code, it doesn't.

I've tried formatting the date in a variety of ways with no luck.  I'm wondering if I have a problem with the datepicker itself.

Thanks,

Ross

**Comment by Thanood** [comment]
Is it similar to issue #148?

If yes: strange, I have a button which does exactly that in my demo version (not uploaded yet).

If not, how do you set the date in code? By using the bound view model variable?
What do you set it to? A ```Date``` instance or a string (I suppose it's a string because you mention formatting).

**Comment by rosshigh** [comment]
I tried the workaround but I get the current date showing rather than the bound date.  However, the value I was trying to bind was a string so it wasn't working.  Your post gave me the hint.

Thanks

**Comment by Thanood** [comment]
I think date instances are the better (safer) option in any case where data-binding is involved. Let materialize handle the output. :smile: 

I thought about implementing a simple ```new Date(stringValue)``` in that case which throws a meaningful exception if that string cannot be parsed. But then data-binding to a date is essentially lost. The picker value is a date.

**Comment by rosshigh** [comment]
The problem was I'm getting data from a MongoDB.  The fields are date types in the database but the service is returning a string.  Makes since but it hadn't occurred to me.  Thanks again.
