### ISSUE TITLE
implement input prefix icons

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#150]
We're missing Materialize's feature of prefix icons for text fields. As far as I can see, these are always ```material-icons```.

Proposed use:
```html
<md-input md-prefix="phone" md-label="put some text here" md-value.bind="textValue"></md-input>
```

Which translates to:
```html
<div class="input-field">
  <i class="material-icons prefix">account_circle</i>
  <input id="phone_number" type="text" class="validate">
  <label for="phone_number">Phone</label>
</div>
```

If I'm wrong and prefixes can actually be anything we could use another custom attribute and inject it via ```<content select="md-prefix">```.

**Comment by Ullfis** [comment]
```html
<div class="input-field">
    <i class="primary-text mdi mdi-biohazard prefix"></i>
    <input type="text" class="validate">
    <label>Biohazard</label>
</div>
```

from package.json/jspm/dependencies: 
"mdi": "npm:mdi@^1.5.54",


in main: 
import 'mdi/css/materialdesignicons.min.css!';

**Comment by Thanood** [comment]
Alright, I see it right there. :smile:
