### ISSUE TITLE
expose files array from file input

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#154]
There is currently no way to access the files array of ```md-file```.

**Comment by Thanood** [comment]
@rosshigh I'm really unsure if this is better done by having a two-way bound new property, changing md-value attribute to hold the files or firing a CustomEvent (can do that regardless).

I don't like these types of two-way bindings because you cannot really set the component's value to anything meaningful. In case of md-value it would only change the label of the file input. In case of files I believe you can't really set the files array of a file input control (right?).

What is that actually? Some kind of "read only two-way binding"? :smile:

**Comment by Thanood** [comment]
Another alternative: let the user read the files property directly from view model:
```html
<md-file view-model.ref="fileInput">
```

and

```js
let files = this.fileInput.files;
```

**Comment by rosshigh** [comment]
That would a reasonable way to handle it.  I assume you're not saying that should work as it is implemented now, right?

**Comment by Thanood** [comment]
Of course. Currently you don't have any good method to get the files.
In master branch I have added a custom event as well as a view model property.
See here if you like: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/b78b47b9fe36f97b11488905f0833ba558f3ea1b

It's practically ready but I'm looking for the "best" way. :smile:
