### ISSUE TITLE
md-select random issue with selection.

### ISSUE THREAD

**Issue by vdangwal** [aurelia-ui-toolkits/aurelia-materialize-bridge#156]
I am seeing some random issue with md-select. I have a list of Products({id:2,productName:"Product1"}). When i try to edit my record (which has productId as a property i class) and in my edit view, i have a md-select which display these products, randomly, md-select does not generate any list. It happen when you edit/cancel multiple time. 

Code: 
 <select md-select id="prods" value.bind="CurrentMeeting.productId">         
                           
                            <option repeat.for="mt of products" model.bind="mt.id">${mt.productName}</option>
                        </select>
                        <label for="prods">Products</label>

Logs for working condition: 
2aurelia-logging-console.js:38 DEBUG [md-select] handleChangeFromViewModel  
aurelia-logging-console.js:38 DEBUG [md-select] handleChangeFromViewModel 1 AGGRASTAT

No logs when its not working. No exception either in console. Please let me know if anything wrong with my code snippet. 

I am loading lookup data (Products) in constructor async(using promise) and loading the record which i am trying to edit inside my vm's activate() function which is screen activation lifecycle of aurelia.

**Comment by Thanood** [comment]
We need some kind of live playground for things like this. Could you try and format the code, please? Also I think it would help if you provide the view model. :smile:

OR even better: can you create a repo with the relevant code? 
It's much easier to help with such things if you have the whole context.

**Comment by Thanood** [comment]
Not to step on your toes but this seems a little more complicated.. :smile:

**Comment by vdangwal** [comment]
which part? :)

**Comment by vdangwal** [comment]
```typescript

private products: Array<Product>;
constructor(private ea: EventAggregator, private cache: GlobalCacheService,
        private svc: LookupDataService,
        private meetingSvc: MeetingsDataService,
        private router: Router,
        private diag: DialogService,
        private validationContext: Validation) {
        super();
        this.CurrentMeeting = new Meeting();
        this.CurrentMeeting.id = 0;
        this.CurrentMeeting.productId=24;
        this.svc.getAllProducts().then((prod: Product[]) => {this.products = prod}); }

 activate(params: any) {

        return new Promise((resolve, reject) => {
            //From Meetings List -> Editing : isAddTo=false
            //Get new item from server.
            if (params.id > 0 && params.isAddTo && params.isAddTo === "false") {
                //Editing existing Record. 
                this.inEditMode = true;

                this.meetingSvc.getMeetingById(params.id).then(meet => {
                    this.CurrentMeeting = <Meeting>meet;                    
                    resolve();
                });
            }
}

```html
 <select md-select id="prods" value.bind="CurrentMeeting.productId">
           <option repeat.for="mt of products" model.bind="mt.id">${mt.productName}</option>
 </select>
 <label for="prods">Products</label>

**Comment by vdangwal** [comment]
let me know if you need more details :)

**Comment by Thanood** [comment]
When you say
> md-select does not generate any list

does that mean the select is empty all of a sudden?
If so, that is strange. Your ```activate()``` doesn't change products in any way. What's the state of ```products``` after activation? And does the above work with a native select?

**Comment by vdangwal** [comment]
i think whats happening here is select has values, but dropdown click is somehow disabled. When i use dev tools -> element to debug the html, i see <ul> .... and all items are there. But i cannot click the dropdown.

**Comment by Thanood** [comment]
I guess I'll have to try this.
Unfortunately this can take some time but if I'm lucky I can spare some time tomorrow.

Let's see if  got this right..
* I'll fill an array of products from a service in constructor
* set a product id before (!) the actual products are read
* in activate I'll overwrite the bound product id

Then I should not be able to use the select.
I'm wondering what happens when ```meet``` (from activate) doesn't have a productId.

Did you try this with a native select?

**Comment by vdangwal** [comment]
have not tried with native select but will give it a shot. i modified my code a bit to use TaskQueue. So one of the scenario (while adding new record) looks fine now. Yes you got it right. :)

```typescript
this.svc.getAllProducts().then((prod: Product[]) => { this.products = prod;
            if (this.inEditMode === false) {
                this.taskQueue.queueMicroTask(() => {
                    this.Logger.info(`${this.products.length} ADD loaded`);
                    this.CurrentMeeting.productId = 24;
                });
            }            
             });

**Comment by Thanood** [comment]
Hmm.. What would happen if activate is executed before the service call in the constructor returns?
There'd be no products at the time when attached is called. That may be the reason.

In that case, the Materialize select is initialized without any items and it's displayed as such. But the native select will be populated.

Materialize select would need a refresh which it doesn't have unfortunately..
We could fake one in the bridge, I think destroy is implemented. So that would be destroy and recreate.

Nasty but that may work.

**Comment by Thanood** [comment]
Btw. that idea came to me when you mentiones taskQueue.
It's basically waiting. And if waiting solves something, there are issues with asynchronous tasks. :smile:

**Comment by vdangwal** [comment]
i agree. Async functions are not that fun.

**Comment by Thanood** [comment]
Refresh doesn't work as expected. Currently, it only refreshed when called twice and throws exceptions.

**Comment by vdangwal** [comment]
How do we set colors in Md-card?

Thanks,
Vikas Dangwal




On Sun, Apr 3, 2016 at 11:03 PM -0700, "Daniel Bendel" <notifications@github.com> wrote:





Refresh doesn't work as expected. Currently, it only refreshed when called twice and throws exceptions.


---

**Comment by Thanood** [comment]
By using the built in Materialize colors or one of:
* accent (background)
* primary (background)
* accent-text (text of course)
* primary-text

See also: http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/color

**Comment by Thanood** [comment]
added a refresh function to md-select
