### ISSUE TITLE
accordion: false not working

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#16]
```md-collapsible="accordion: false``` leads to this being executed:
```javascript
$(this.element).collapsible({
  accordion: false
});
```

but that still initializes the collapsible as an accordion.

**Comment by JeroenVinke** [comment]
accordion.bind: true perhaps?

**Comment by Thanood** [comment]
It checks if it's a string, so that shouldn't make a difference.
But I've tried it anyway. Unfortunately stays the same.

**Comment by Thanood** [comment]
Adding ```data-collapsible="expandable"``` works.
Not pretty, but works.
