### ISSUE TITLE
string interpolation in custom attributes

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#164]
:point_up: [11. April 2016 19:02](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=570bd8ab8b17927458e35d71)

This does not work:

``` html
  <tr repeat.for="product of products">
    <td>
        <div class="actions">
            <a md-dropdown="activates: productlist-dropdown-${product.Id}; below-origin: true;">
                <i class="material-icons center primary-text hoverable">more_vert</i>
            </a>
        </div>
    </td>
  </tr>
```

The expression in the `md-dropdown` attribute is not evaluated.
I wonder if this is on purpose or if it's a bug.

**Comment by eikaramba** [comment]
Here too. I really think this needs to be fixed, as otherwise how can you use the dropdown component in a custom element? Or even multiple ones on the same side that are generated dynamically?

**Comment by Thanood** [comment]
I think it *may* be a bug in Aurelia's binding/templating. I think I've seen a related issue posted recently, but couldn't find it now.

As for the question on how to do dynamic dropdowns, this works:

```html
  <tr repeat.for="product of products">
    <td>
        <div class="actions">
            <a md-dropdown="activates.bind: 'productlist-dropdown-' + product.id; below-origin: true;">
                <i class="material-icons center primary-text hoverable">more_vert</i>
            </a>
        </div>
        
    </td>
  </tr>
```

I guess the bridge could probably work around it by using `ref` attributes and creating the `id`s automatically. I'll need to try it.

**Comment by Thanood** [comment]
"Ref"s are available now:

```html
  <div class="dropdown-sample">
    <a md-button md-dropdown="ref.bind: dropdown2;">drop me!</a>
    <ul ref="dropdown2">
      <li><a click.trigger="showToast($event)">one</a></li>
      <li><a click.trigger="showToast($event)">two</a></li>
      <li class="divider"></li>
      <li><a click.trigger="showToast($event)">three</a></li>
    </ul>
  </div>
```

Not published, yet. I'd like to test it with dynamic dropdowns and provide a sample.

**Comment by eikaramba** [comment]
May i ask, the difference between using ref and activates.bind is that within a view-model you can happily use a name as the reference, that can exists multiple times on the page. like populating a list of <custom-element> whereas the custom element uses a dropdown inside with ref="myDropdown" (<-- no dynamic name generation)

**Comment by Thanood** [comment]
As you mentioned, this should happen mostly in a `repeat.for`, inside of multiple custom elements and probably `if.bind` Anything else would probably be worse than using the same `id` attribute on multiple html elements. 😉 

In the case of a `repeat.for` the `ref` is scoped and refers only to the current iteration.
This means that in this list:

```html
  <div repeat.for="c of 20">
    <span fake-id="ref.bind: referenced">${c}</span>
    <span ref="referenced">${c}</span>
  </div>
```

the ref `referenced` is always the current element of the current iteration.

A sample gist:
https://gist.run?id=5f40c3c60d4428a04219f330e79ac27c

Check the numbers in dev-tools, there is a span with a custom attribute and a referenced sibling. The `fake-id` attribute sets the ids of both.
