### ISSUE TITLE
Prepare for shadowdom v1

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#166]
:point_up: [13. April 2016 22:57](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=570eb2b75ed5a4fd3fe2c1fc)

Try it. :smile:

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/523

**Comment by Thanood** [comment]
@JeroenVinke How do you set this up?

I tried in a minimal setup to install templating from `aurelia-templating=github:aurelia/templating@1.0.0-beta.2.0.1` but Aurelia uses the npm versions. I guess because the jspm registry is different, it gets treated as a completely different library instead of a fork (two versions of the same lib).

I'm thinking of manipulating the `config.js` dependencies directly. Do you know a more "elegant" way? :smile:

**Comment by Thanood** [comment]
Seems I'm not getting everything right..

here's the `md-card` markup:
```html
<template>
  <require from="./card.css"></require>
  <div class="card ${ mdSize || '' }">
    <div if.bind="mdImage !== null" md-waves="color: light; block: true;" class="card-image">
      <img class="${ mdReveal === true ? 'activator' : '' }" src.bind="mdImage" />
      <span if.bind="mdReveal === false" class="card-title">${mdTitle}</span>
    </div>
    <div class="card-content">
      <span if.bind="mdReveal === true" class="card-title activator">
        ${mdTitle}
        <i class="material-icons right">more_vert</i>
      </span>
      <span if.bind="mdImage === null" class="card-title">${mdTitle}</span>
      <slot>fallback default</slot>
    </div>
    <div if.bind="mdReveal" class="card-reveal">
      <span class="card-title activator">
        ${mdTitle}
        <i class="material-icons right">close</i>
      </span>
      <slot name="reveal-text">fallback reveal</slot>
    </div>
  </div>
</template>
```

The `reveal-text` slot is never filled. Even its fallback content is not displayed.

**Comment by JeroenVinke** [comment]
Is this in a branch somewhere?

**Comment by Thanood** [comment]
Not the most recent version as I've just edited it (marginal changes) but it's in the `shadow-dom` branch:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/shadow-dom
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/shadow-dom/src/card/card.html

**Comment by Thanood** [comment]
Seems like it's because the `<slot>` is inside a template controlled by `if.bind`.

**Comment by Thanood** [comment]
Next issue.. :smile: 

ShadowDOM is messing up my CSS..

![image](https://cloud.githubusercontent.com/assets/677826/16017270/4c7ea55e-319f-11e6-9ed3-464baf9b4678.png)

That dropdown has *three* entries. Before using `<slot>` it would overlap the card. Relatively easy to fix but I wouldn't expect that.

**Comment by JeroenVinke** [comment]
:cry:

**Comment by Thanood** [comment]
Somthing is not right with that..

The MaterialBox usually creates an overlay, displaying an image in full height/width (it's a lightbox).
Now the image is zoomed (as if displayed in full size) but the viewport is cut to the size of the samples's card (which is the ShadowDOM root?)..

**Comment by Thanood** [comment]
Okay, this one is strange..

Step 1: http://localhost:3000/#/samples/select/

![image](https://cloud.githubusercontent.com/assets/677826/16018454/cf6171ea-31a4-11e6-9d65-638117557189.png)

* click on "set to item 3".
* select something from the select box

![image](https://cloud.githubusercontent.com/assets/677826/16018495/f308776a-31a4-11e6-8932-64e1d11bde08.png)

Select options are cut off..

* switch to another route and come back
* immediately select something from the select box

![image](https://cloud.githubusercontent.com/assets/677826/16018523/15b41472-31a5-11e6-86cd-f7a0dab446df.png)

Select options are displayed in full.

**Comment by JeroenVinke** [comment]
I am sure that the aurelia team is interested in feedback on the new shadow dom before it is used by the everyone. How much time will it take to reproduce in skeleton navigation?

**Comment by Thanood** [comment]
I don't know..

I would have to see if it happens with a less complicated setup. This here is with jQuery + Materialize involved. I can try in a minimal setup (more [like this](https://github.com/Thanood/aurelia-min/tree/master/es2016-jspm)).

Better than GitBook driving me crazy on "invalid entries in SUMMARY.md" :smile:

**Comment by JeroenVinke** [comment]
:) I will try shadow dom again tomorrow with kendo since I now know the errors I got were caused by bluebird

**Comment by Thanood** [comment]
Funny.. When I remove the `show.bind` from above everything looks good.
So it's not an Aurelia problem.

**Comment by Thanood** [comment]
Part of the reason is, "reveal cards" also introduce an `activator` which sets the `card` itself to `overflow: hidden;`.

**Comment by Thanood** [comment]
Oh wow, seems like `1.0.0-beta.3.0.0` has been pushed to npm a few hours ago..
https://www.npmjs.com/package/aurelia-templating
https://github.com/aurelia/templating/releases

Noticed that when I tried to update the gist.run bundle.. Of course that doesn't work with `<content>` and `<template replace part...>`.

**Comment by Thanood** [comment]
done
