### ISSUE TITLE
Md-Colors template is not loaded

### ISSUE THREAD

**Issue by Kukks** [aurelia-ui-toolkits/aurelia-materialize-bridge#169]
I was using the md-colors custom element before just fine and I upgraded the packages and it seems to not load anymore. Using it as so:
```
<template>
    <require from="./app.css"></require>
    <require from="./modules/sections/nav-bar/nav-bar"></require>
    <nav-bar router.bind="router"></nav-bar>

    <md-colors md-primary-color="#0084DE" md-accent-color="#FF9E5F"></md-colors>

    <!--App's Host-->
    <div class="page-host">
        <page-loader></page-loader>
        <router-view></router-view>

    </div>
</template>
```

Did something change?

**Comment by Thanood** [comment]
Not that I know of. I always immediately test this with the catalog app and it seems to work fine there.

Are there any errors?

**Comment by Kukks** [comment]
No errors whatsoever.. super weird. I can see that the template has been requested by the app.

**Comment by Thanood** [comment]
I will try to reproduce this issue. Not sure, how. :smile: 
Can you try to bind the colors?
```html
<md-colors md-primary-color.bind="'#0084DE'" md-accent-color.bind="'#FF9E5F'"></md-colors>
```

If that works, I guess there's a regression somewhere.
I've tried this in a gist.run and it worked but that is not using the most recent version of either Aurelia or the bridge.

**Comment by Thanood** [comment]
It seems to work on a staging server.
