### ISSUE TITLE
materialize sidenav css and js not found error

### ISSUE THREAD

**Issue by chaituGS** [aurelia-ui-toolkits/aurelia-materialize-bridge#170]
issue:
XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.5.0/sidenav/sidenav.css.js

  Facing the above mentioned issue, when adding .useSidenav() to the plugin.
please reply with possible working solution. Thanks in advance.

**Comment by Thanood** [comment]
Are you using skeleton-navigation?

The current skeleton-navigation seems to have two conflicting versions of `plugin-css` installed. Can you check if ```jspm update``` helps?

**Comment by chaituGS** [comment]
Thanks for the quick reply. will try that and update you.

**Comment by chaituGS** [comment]
Thank you Thanood. it worked fine by updating jspm.

**Comment by Thanood** [comment]
Great. :+1: 
Thanks for the update.
