### ISSUE TITLE
Links broken on http://aurelia-ui-toolkits.github.io/demo-materialize

### ISSUE THREAD

**Issue by AnderssonPeter** [aurelia-ui-toolkits/aurelia-materialize-bridge#178]
`Help/Docs` and `app developers tutorial` under installation.

**Comment by Thanood** [comment]
Ouch, that's embarassing.. `localhost:3000` :smile: 
I don't know how it got there. `Help/Docs` does work for me, though.

**Comment by Thanood** [comment]
Link in `installation` is fixed.

**Comment by AnderssonPeter** [comment]
Sorry for the late response, but the Help/Docs work in Edge, but not IE 11.

> ERROR [app-router] Error: Error invoking Doc. Check the inner error for details.
> ------------------------------------------------
> inner error: TypeError: Object doesn't support property or method 'includes'
>    at Doc (Unknown script code:53:15)
>    at S[2].invoke (Unknown script code:4:27910)
>    at e.prototype.invoke (Unknown script code:4:27563)
>    at e.prototype.invoke (Unknown script code:4:31033)
>    at e.prototype.get (Unknown script code:5:30243)
>    at e.prototype.get (Unknown script code:4:30302)
>    at y (Unknown script code:5:1084)
>    at e.prototype.create (Unknown script code:6:20439)
>    at v (Unknown script code:5:2524)
>    at e.prototype.create (Unknown script code:6:67)
>    "ERROR [app-router]"
>    {
>       [functions]: ,
>       __proto__: { },
>       __symbol:hasInstance0.103838544633028946: undefined,
>       __symbol:isConcatSpreadable0.103838544633028947: undefined,
>       __symbol:iterator0.103838544633028941: undefined,
>       __symbol:match0.103838544633028942: undefined,
>       __symbol:replace0.103838544633028943: undefined,
>       __symbol:search0.103838544633028944: undefined,
>       __symbol:species0.103838544633028949: undefined,
>       __symbol:split0.103838544633028945: undefined,
>       __symbol:toPrimitive0.1038385446330289410: undefined,
>       __symbol:toStringTag0.1038385446330289411: undefined,
>       __symbol:unscopables0.103838544633028948: undefined,
>       description: "Error invoking Doc. Check the inner error for details.
> ------------------------------------------------
> inner error: TypeError: Object doesn't support property or method 'includes'
>    at Doc (Unknown script code:53:15)
>    at S[2].invoke (Unknown script code:4:27910)
>    at e.prototype.invoke (Unknown script code:4:27563)
>    at e.prototype.invoke (Unknown script code:4:31033)
>    at e.prototype.get (Unknown script code:5:30243)
>    at e.prototype.get (Unknown script code:4:30302)
>    at y (Unknown script code:5:1084)
>    at e.prototype.create (Unknown script code:6:20439)
>    at v (Unknown script code:5:2524)
>    at e.prototype.create (Unknown script code:6:67)",
>       innerError: { },
>       message: "Error invoking Doc. Check the inner error for details.
> ------------------------------------------------
> inner error: TypeError: Object doesn't support property or method 'includes'
>    at Doc (Unknown script code:53:15)
>    at S[2].invoke (Unknown script code:4:27910)
>    at e.prototype.invoke (Unknown script code:4:27563)
>    at e.prototype.invoke (Unknown script code:4:31033)
>    at e.prototype.get (Unknown script code:5:30243)
>    at e.prototype.get (Unknown script code:4:30302)
>    at y (Unknown script code:5:1084)
>    at e.prototype.create (Unknown script code:6:20439)
>    at v (Unknown script code:5:2524)
>    at e.prototype.create (Unknown script code:6:67)",
>       name: "Error",
>       stack: "Error: Error invoking Doc. Check the inner error for details.
> ------------------------------------------------
> inner error: TypeError: Object doesn't support property or method 'includes'
>    at Doc (Unknown script code:53:15)
>    at S[2].invoke (Unknown script code:4:27910)
>    at e.prototype.invoke (Unknown script code:4:27563)
>    at e.prototype.invoke (Unknown script code:4:31033)
>    at e.prototype.get (Unknown script code:5:30243)
>    at e.prototype.get (Unknown script code:4:30302)
>    at y (Unknown script code:5:1084)
>    at e.prototype.create (Unknown script code:6:20439)
>    at v (Unknown script code:5:2524)
>    at e.prototype.create (Unknown script code:6:67)
>    at e.prototype.invoke (Unknown script code:4:31139)
>    at e.prototype.get (Unknown script code:5:30243)
>    at e.prototype.get (Unknown script code:4:30302)
>    at y (Unknown script code:5:1084)
>    at e.prototype.create (Unknown script code:6:20439)
>    at v (Unknown script code:5:2524)
>    at e.prototype.create (Unknown script code:6:67)
>    at e.prototy"
>    }
>

**Comment by Thanood** [comment]
I've seen this before. There must be a polyfill missing or I didn't remove all of the direct `includes` calls. Thus reopening this. Thanks. :smile:

**Comment by Thanood** [comment]
Fixed this in source and will upload the updated app later today.

**Comment by Thanood** [comment]
fix uploaded
