### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#18]
```gulp build-es6-temp``` now fails with an error I've never encountered before:
```
aurelia-materialize-bridge/devbuild/aurelia-materialize-bridge.js: Line 126: "fireMaterializeEvent" is read-only
```

```
  124 | * @param data Addition data to attach to an event
  125 | */
> 126 | export function fireMaterializeEvent(element: Element, name: string, data? = {}) {
      |        ^
  127 |   return fireEvent(element, `${constants.eventPrefix}${name}`, data);
  128 | }
  129 |
```

Removing that task from the gulp chain at least permits executing it. What does ```build-es6-temp``` do anyway?

**Comment by JeroenVinke** [comment]
It generates the d.ts file with the babel-dts-generator

**Comment by Thanood** [comment]
Okay, good to know. But why is that function read-only? :smile:

**Comment by JeroenVinke** [comment]
Not sure. I believe the kendo Plugin had this function too,  perhaps you can try to build that and compare (perhaps different versions of dependencies)

**Comment by Thanood** [comment]
I've actually copied it from there.
On first sight there is no difference but kendoui doesn't throw errors on build.
I will have to do it later though.

**Comment by Thanood** [comment]
Strange, when I change
```javascript
import { fireMaterializeEvent } from '../common/events'
```
to
```javascript
import { fireMaterializeEvent as fe } from '../common/events'
```
it works

**Comment by Thanood** [comment]
Oh wow...
It happens when you forget the semicolon here:
```
import { fireMaterializeEvent } from '../common/events';
```

In that case the import is not included in the import block at the beginning of the concatted file. :smile:

**Comment by JeroenVinke** [comment]
Good find!!
Op 19 jan. 2016 10:41 schreef "Thanood" <notifications@github.com>:

**Comment by Thanood** [comment]
Could that be an aurelia-tools bug? I mean I've made a mistake but it could at least fail ```extractImports``` or issue a warning.
