### ISSUE TITLE
improve docs: explain bootstrap removal

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#185]

**Comment by dev0x10** [comment]
I'd like to help this. But please let me to be clear, are we going to explain bootstrap removal on skeleton-navigation project?

**Comment by Thanood** [comment]
Something like that. :smile: 

There has been a question about what to do with Bootstrap after going through the tutorial and another question was if the Materialize bridge needs Bootstrap. I guess this will just be one or two sentences but it should be mentioned in the docs.

**Comment by adriatic** [comment]
Here is the story on Bootstrap requirement in our bridges: as they are all descendants of Aurelia Navigation Skeleton app and because that app uses the Bootstrap nav-bar component, initial versions of all aurelia-ui-toolkits bridges kept that nav-bar, which is the only Bootstrap dependency. As the bridges were more and more functional we replaced the nav-bar (menu bar) with the native widget of the SDK the bridge wraps as a set of Aurelia components. A good example is the KendoUI bridge's [catalog](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/stock) where the KendoUI menu widget is used for top level navigation. As a consequence, KendoUI bridge has no dependency on Bootstrap.

**Comment by dev0x10** [comment]
I see.
Where we should put it? What if we put it on Help/Docs under App Developer Notes
![uninstall-bootstrap](https://cloud.githubusercontent.com/assets/4746126/15988822/4ac4c752-3091-11e6-8b67-78944b77ae92.png)

**Comment by JeroenVinke** [comment]
I believe that the kendo catalog still has a bootstral dependency, because the bootstrap grid system is used

**Comment by Thanood** [comment]
@dev0x10 

I think that it should be mentioned in the tutorial. At the end of [chapter 2](http://aurelia-ui-toolkits.github.io/demo-materialize/#/help/docs/app_developers_tutorials/2._setup), all references to Bootstrap are basically gone from the code but it isn't mentioned anywhere.

There is `main.js` without a bootstrap reference and `app.html`. Also `nav-bar.html` now uses the Materialize grid system (and the bridge's `md-navbar`). At that point, Bootstrap isn't used anymore but it's still present in `package.json`.

Maybe that would be the right places to put it. What do you think?
That could as well be some one-line notes with a link to the new chapter you'r proposing. :+1:

**Comment by Thanood** [comment]
@adriatic @JeroenVinke 

Please keep in mind that this issue is about the tutorial and Bootstrap in the catalog app is long gone. But don't let that stop you from commenting. :smile: 
It's always good to have some reasons why it has been there in the first place and why/when it can be removed. Helps other users make a decision on the subject. :smile:

**Comment by adriatic** [comment]
I do not understand the need to explain such details of the catalog app which is not a part of the KendoUI distribution. It could be written in Fortran while still retaining its relevance 😊

**Comment by JeroenVinke** [comment]
It was actually a minor correction of this:

> A good example is the KendoUI bridge's catalog where the KendoUI menu widget is used for top level navigation. As a consequence, KendoUI bridge has no dependency on Bootstrap.

Yes, we are using the Kendo menu in the catalog but we still have a dependency on bootstrap

**Comment by adriatic** [comment]
**That** I understand and I realized that I lied in my comment as it is all my code that uses Bootstrap grid :-). Nevertheless explaining the **catalog** application's structure details should be removed from the online documents and replaced with the description of **generic** application that uses KendoUI bridge

**Comment by dev0x10** [comment]
@Thanood 
I agree that would be the best place since some of files are mentioned there. What if we put the removal process before aurelia-materialize-bridge installation?

**Comment by Thanood** [comment]
@dev0x10 
Yes, why not? You could say something like "we don't need bootstrap anymore since at the end of this setup article it will be replaced by Materialize's controls"..

That should make everything pretty clear. I like that. :+1:

**Comment by dev0x10** [comment]
This is what I put on the tutorial, if you think it's ok then I'll send PR. Let me know if we need to change the wording

![fireshot capture 1 - help i aurelia materialize components_ - http___localhost_3000_ _help_docs_a](https://cloud.githubusercontent.com/assets/4746126/16034160/c7c65db2-3242-11e6-95c7-6c6ac5e4b7f3.png)

**Comment by Thanood** [comment]
I like it, good work. :+1: 
Not sure if "we need to remove Bootstrap" is a little too "direct"? :smile: 
But in fact, the two css frameworks collide at certain points (navbar for example) so we can keep it.

I guess you've tested this instructions so it doesn't lead to unexpected errors.
Should we also mention removing it from the jspm registry?

**Comment by dev0x10** [comment]
Maybe this sentence sounds better?
"Before we continue to the next step, we **can** remove Bootstrap from the app skeleton because we are going to use Materialize css."

Thanks for reminding me the JSPM part. Yes we should mention it, although it won't causing any error but the bundle size is wasted. I'll put it at the beginning of removal instructions.

Before I send PR, I will test my own tutorial to make it works properly 😄

**Comment by Thanood** [comment]
Great, thanks! :+1:

**Comment by dev0x10** [comment]
Last result
![fireshot capture 4 - help i aurelia materialize components_ - http___localhost_3000_ _help_docs_a](https://cloud.githubusercontent.com/assets/4746126/16057606/6dfee9aa-32ad-11e6-8b06-69b37fb332c7.png)

PR sent

**Comment by Thanood** [comment]
I guess that happens because `export` is a reserved word in javascript and the MD component gets confused. :smile: 
Looks good on GitHub, though.

Thanks again, I will merge now and see what I can do about `export`.

**Comment by Thanood** [comment]
Yeah, it's because of the backticks in the file name. I guess it's just the `showdown` package behaving this way. Honestly, I don't care very much, we will be transferring the docs to gitbook (and include that in the catalog) soon. It's still markdown, so at first it'll be a simple copy, nothing is lost.

I've put the changes online, looking good. :smile:

**Comment by dev0x10** [comment]
Ok then, thanks!
Hope I can contribute to the other issues 👍
