### ISSUE TITLE
Multiple files not found when starting

### ISSUE THREAD

**Issue by killbom** [aurelia-ui-toolkits/aurelia-materialize-bridge#186]
I am just getting started with aurelia, so i might be doing something completely wrong, but I am having an issue.

For the record I am using Windows 10. I try to use the skeleton app https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016 and setting it up works fine.

After that i try to follow the steps to install aurelia-materialize-bridge, located here: http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation

After importing the plugin the site stops loading and outputs the following errors:

`undefined:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/slider/slider.css.js(…)
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/chip/chip.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/collection.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/collection-item.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/collection-header.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/md-collection-selector.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/fab/fab.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/file/file.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/input/input.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/navbar/navbar.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/pagination/pagination.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/progress/progress.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/radio/radio.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/range/range.html Array[0]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/sidenav/sidenav.html Array[1]
aurelia-logging-console.js:56 DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/switch/switch.html Array[1]
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/breadcrumbs/breadcrumbs.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/card/card.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/collection-item.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/collection-header.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/collection/md-collection-selector.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/input/input.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/navbar/navbar.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/sidenav/sidenav.css.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.6.1/switch/switch.css.js Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by Thanood** [comment]
This seems like the css files are not loaded as css.
Can you try installing the SystemJS css plugin?
`jspm install css`

After this, you might get JSPM forks. If this is the case, maybe this helps:
http://aurelia-ui-toolkits.github.io/demo-materialize/#/help/docs/app_developers_tutorials/7._what_you_need_to_know

Anyway, I'm wondering why that plugin isn't pulled from the start..

**Comment by killbom** [comment]
I will give it a shot.

I have found out that it only seems to bug when i use "gulp watch" as server. If i create a new project using aspnet i have no issuse (except that i must use aspnet ;) )

**Comment by Thanood** [comment]
I just cloned the skeleton and installed the bridge. `plugin-css` is installed but I got forks.
It could be that you already had jspm forks.. :smile:

**Comment by Thanood** [comment]
I guess the skeleton is configured with a slightly older version then the most recent one. In this case:
```
       npm:aurelia-binding 1.0.0-beta.1.3.5 1.0.0-beta.1.3.6
    npm:aurelia-templating 1.0.0-beta.1.2.6 1.0.0-beta.1.2.7
```

So the bridge will cause jspm to download the most recent versions while the skeleton retains the older ones, leading to a fork. Why this doesn't load css escapes me, tbh..

I think the asp.net skeleton may already use newer versions.

But this is just a guess.

**Comment by killbom** [comment]
I removed all downloaded requirements and did:
`npm update
jspm update`

Seems to do the trick. I have still no idea why it would try to load css as javascript :/
