### ISSUE TITLE
Issue with md-select options updating

### ISSUE THREAD

**Issue by Kukks** [aurelia-ui-toolkits/aurelia-materialize-bridge#187]
It seems that when updating the options within an `md-select`, it does not update. The underlying select is updated though. 

Further is there a way to be able to bind the actual model to the option to make it easier to use? Perhaps we could add an `md-option` or something?

**Comment by Kukks** [comment]
Another issue with `md-select` is that there is no action upon clicking the caret icon on the dropdown

**Comment by Thanood** [comment]
Is this happening to multiple selects only or also to single selects?
In [this example](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/refresh) the options are updated correctly.

But there are still unresolved issues with [multiple selects](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/multiple).

Also [this example](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/binding-to-objects) shows how to bind to objects. The "You selected:" output is the `JSON.stringify` representation of an actual object.

So I'm not sure what's going on there. :wink:

**Comment by Kukks** [comment]
Must be our bad, we're doing some complex bindings and everything can get a little blurry in between :) Sorry for the hassle. Didn't know about the refresh part though.
