### ISSUE TITLE
AuMarkdown: showdown is undefined

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#19]
```import 'showdown';``` does not introduce a global "showdown" anymore (as stated in ```meta``` section of config.js).
```import * as showdown from 'showdown';``` imports a local showdown but then showdown-prettify cannot be found.

Compared it with kendo-ui-bridge, it works there. Until now I couldn't find any difference.
(and of course: yesterday it worked :smile: )

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/config.js#L19-L23

**Comment by Thanood** [comment]
right, but...
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/config.js#L19-L23

**Comment by JeroenVinke** [comment]
Works here BTW. Does `jspm dl-loader` help? perhaps removing jspm_packages and node_modules and then running npm install & jspm install again

**Comment by Thanood** [comment]
I tried ```jspm dl-loader```, did not help.
Will try removing jspm_packages/node_module now.

**Comment by Thanood** [comment]
That helped. Thanks!
I guess no chance now to find out what happened..
