### ISSUE TITLE
md-text-area placeholder issue

### ISSUE THREAD

**Issue by easyt** [aurelia-ui-toolkits/aurelia-materialize-bridge#192]
Hey Daniel,

There is a small issue when using the ```md-text-area``` with ```md-placeholder```. The code fails at the following location:

```this.input.setAttribute('placeholder', this.mdPlaceholder);```

```this.input``` is undefined. The reason for this is the binding in the ```md-input``` template:  ```if.bind="mdTextArea === true"``` since it requires a boolean value.

Initially, if we use the following:
```<md-input md-label="Description" md-placeholder="Enter a description" md-text-area="true"></md-input>```

The ```md-text-area="true"``` is evaluated to a ```true``` string and not a boolean.

If I use the following:
```<md-input md-label="Description" md-placeholder="Enter a description" md-text-area.one-time="true"></md-input>```

It works because the ```one-time``` binding is evaluating the ```true``` to a boolean value.

You might try moving the following line from the ```attached``` to the ```bind``` method of the ```md-input``` custom element:

```this.mdTextArea = getBooleanFromAttributeValue(this.mdTextArea);```

**Comment by Thanood** [comment]
Great bug report, thanks! :smile: 
Interesting enough, that it *seems* to work in the sample.

If you like, you can also issue a PR and I will merge it.
If you do, please follow our [commit message conventions](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol).

**Comment by Thanood** [comment]
Done and updated samples to show text area placeholders.
Thanks again for the suggestion and solution. :smile:

**Comment by easyt** [comment]
Thanks for the fix!
