### ISSUE TITLE
Add a simple date parser to editable datepicker

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#197]
Proposal:
* takes the format used by pickadate as its configuration
* simple parsing of the current date entered, match format with value entered
* maybe just throw an error if the value entered does not fit the configured format
* pluggable(?) to enable users to bring their own parser - how would this work?
* maybe add a placeholder showing the current format

#196

**Comment by Kukks** [comment]
The pluggable parser could easily work in the same style as the equality matcher https://github.com/aurelia/binding/issues/94

**Comment by Thanood** [comment]
So that would be something like...

```javascript
.plugin('aurelia-materialize-bridge', bridge => { bridge.useAll().useDatePickerFormatter(myFormatter); });
```

And we would somehow get DatePicker to use `myFormatter`? :smile:

**Comment by Kukks** [comment]
I was thinking more along the lines of simply specifying a function as a bindable that accepts a string and outputs a Date or null so something like: 
`md-datepicker="container: body; value.two-way: selectedValue; options.bind: advancedOptions"`

` this.advancedOptions = {
                    closeOnSelect: true,
                    closeOnClear: true,
                    selectYears: 50,
                    editable: {},
                    showIcon: false,
                    parser: this.specialDateParser
                };`

`public specialDateParser( text: string ): Date {
        if ( text === "Incredibly complex date" )
            return new Date();//we aint got time fo'dat
    }`

**Comment by Kukks** [comment]
But maybe a mix of both so that you're able to set a default parser globally and then allow yourself to override it with an inline bindable :)

**Comment by Thanood** [comment]
I like the thought. :smile:
