### ISSUE TITLE
Add installation instructions for webpack/typescript

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#198]
At the moment there is only JSPM/esnext.
This description is insufficient when dealing with the latest changes to Aurelia's TypeScript/webpack handling.

**Comment by glennpierce** [comment]
hmm I have added
import 'materialize-css';

to main.ts

and

.plugin('aurelia-materialize-bridge', bridge => { bridge.useRange(); })

In webpack.config.js

I have added 'aurelia-materialize-bridge'

The range control works but the css doesn't seem to load for the control. Even though I get no error from import 'materialize-css';

The range cursor bubble doesn't appear.

Ant ideas ?

**Comment by Thanood** [comment]
@glennpierce 
I had to `<require from="materialize-css/bin/materialize.css"></require>` to load the css. Did you also do that?
[see here](https://github.com/Thanood/md-webpack-skeleton/blob/master/src/app.html) to have a look at how I used it in a reference skeleton.

**Comment by glennpierce** [comment]
That did it. Thanks Thanood. I thought import 'materialize-css';

 in main was meant to load it for the entire app. My misunderstanding.

Thanks again
