### ISSUE TITLE
checkbox now visible while editing grid 

### ISSUE THREAD

**Issue by genericuser-me** [aurelia-ui-toolkits/aurelia-materialize-bridge#199]
I am using aurelia-materialize-bridge along with aurelia-kendoui-bridge. any idea why checkbox is not shown?

https://gist.run/?id=8c9525d604a14b0c2bb90ba3f6e5abc8

Can anyone please help?

**Comment by Thanood** [comment]
I'm sorry, @genericuser-me but I can't run your gist.
Materialize bridge isn't loaded in index.html and I'm not sure why it doesn't even when I add a reference to index.html.

I will try it again in a skeleton.
Ping @JeroenVinke mayybe you already see something.

What versions are you using? Maybe I broke something yesterday.
Btw, one thing I broke yesterday (on purpose): If you happen to fetch directly from master (don't do that! :smile: ) you would have to import materialize yourself in `main.js`.

**Comment by JeroenVinke** [comment]
@Thanood I believe I've got a skeleton-navigation with both these bridges installed, will try and reproduce

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16479294/acac9244-3e9f-11e6-9378-c19eccfb1b69.png)

and with this CSS:

```
.k-grid [type="checkbox"]:not(:checked), .k-grid [type="checkbox"]:checked {
  position: relative;
  left: 0;
  opacity: 1;
}
```

![image](https://cloud.githubusercontent.com/assets/2189477/16479298/b21bed7e-3e9f-11e6-8400-bde70602fcf3.png)

**Comment by Thanood** [comment]
Thanks for having a look at that, @JeroenVinke. I wonder why this has worked before.

**Comment by genericuser-me** [comment]
You are awesome @JeroenVinke , Thanks a ton!
