### ISSUE TITLE
Problems with running Karma

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-materialize-bridge#2]
While running the newly created aurelia-materialize bridge, I am getting this error message
```
[18:58:43] Starting 'tdd'...
[18:58:44] Finished 'copy-css' after 4.58 s
13 01 2016 18:58:46.564:ERROR [karma]: { [Error: EMFILE: too many open files, open 'C:\work\aurelia-ui-toolkits\aurelia-materialize-bridge\src\click-counter.js']
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\work\\aurelia-ui-toolkits\\aurelia-materialize-bridge\\src\\click-counter.js' } Error: EMFILE: too many open files, open 'C:\work\aurelia-ui-toolkits\aurelia-materialize-bridge\src\click-counter.js'
```

each time I change something in the source code of the "bridge consumer application. Note that the task `gulp watch` is running as I expect to see the effects of my change, without having to manually restart the `gulp watch`

Looking up this error message, it seems that this is a possibly still not resolve issue with karma on Windows, so I would like to be able to exclude invoking karma in my daily grind, until we have a solution for this

Note: this simple cure in `default.js` file
```
var gulp = require('gulp');
var runSequence = require('run-sequence');

gulp.task('default', function(callback) {
  return runSequence(
    'lint',
    'build',
    // 'test',
    callback
  );
});
``` 

did not result with a fix

**Comment by JeroenVinke** [comment]
fixed in https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/51ed4f527440dd068d7dc959a2bc06b58d55deb9

same fix as https://github.com/aurelia-ui-toolkits/plugin-builder/issues/4
