### ISSUE TITLE
Implement cards

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#20]
Cards are used throughout the catalog application, all of them following a similar layout. To not necessarily repeat everything we could introduce ```<md-card>``` as a custom element.

Usage example:
```html
<md-card title="fancy title">
  <div>card content</card>
</md-card>
```

Which translates to:
```html
<div class="card">
  <div class="card-content">
    <span class="card-title">fancy title</span>
    <div>card content</card>
  </div>
</div>
```

(this issue is part of a first milestone [implement the catalog's basic user interface](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/milestones/implement%20the%20catalog's%20basic%20user%20interface))

**Comment by adriatic** [comment]
There is a typo above - I would think that the translated HTML would be this
Which translates to:
```html
<div class="card">
  <div class="card-content">
    <span class="card-title">fancy title</span>
    <card>card content</card>
  </div>
</div>
```

**Comment by Thanood** [comment]
Certainly, a good idea to use that!
That would mean replace the ```<div>``` from the example with ```<card>``` or wrap it in a card so it translates to:
```html
<div class="card">
  <div class="card-content">
    <span class="card-title">fancy title</span>
    <card>
      <div>card content</div>
    </card>
  </div>
</div>
```

**Comment by Thanood** [comment]
@adriatic Where does that ```<card>``` actually come from?
It's not defined in HTML as far as I could see.

**Comment by adriatic** [comment]
I think that the concept of a <card> originates from Twitter - see:

- https://dev.twitter.com/cards/overview

- https://medium.com/intercom-inside/why-cards-are-the-future-of-the-web-d3f6ce8b843a#.h5zds1e2b

**Comment by Thanood** [comment]
Thanks, very interesting stuff..
But I actually mean the ```<card>``` element you mentioned. Not the concept. :smile: 

Although it *is* really interesting.

**Comment by adriatic** [comment]
I am not aware of mentioning a `<card>` so I do not understand your question

**Comment by Thanood** [comment]
Then maybe there is something I didn't understand. I was referring to:
> There is a typo above - I would think that the translated HTML would be this

```<div class="card">
  <div class="card-content">
    <span class="card-title">fancy title</span>
    <card>card content</card>
  </div>
</div>```

Anything I didn't get?

To clarify: I implemented it like this and posted an issue on aurelia/templating regarding problems with ```@inlineView```. Rob then stumbled upon that ```<card>```, asking if it was global.
That's the reason I've looked up the ```<card>``` element. :smile:

**Comment by adriatic** [comment]
From the comment at https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/20#issuecomment-173230215

![image](https://cloud.githubusercontent.com/assets/2712405/12485890/3d46e908-c02e-11e5-80fb-625654f0ea8a.png)

**Comment by Thanood** [comment]
Oh wow! Thanks, I didn't see this even the third (or more) time I looked at it!
