### ISSUE TITLE
Trailing comma in package.json

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia-ui-toolkits/aurelia-materialize-bridge#201]
Hi,

In line 113 of your package.json you have a trailing comma which prevents npm from directly referencing the github repository. I think you'll have it fixed faster than merged a PR, but if you need a PR just give a hint.

Thanks and kind regards

**Comment by Thanood** [comment]
Fixed. :smile: 
Thank you.

But it was [line 112](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L112), right?

**Comment by JoschaMetze** [comment]
Thanks, npm said 113, but you hit the right line :+1:
