### ISSUE TITLE
Add information for webpack users (uglifyJs plugin)

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia-ui-toolkits/aurelia-materialize-bridge#202]
Hi,

as I've learned it the hard way, you might share this information on your wiki. When using aurelia-materialize-bridge (and thus materialize) via webpack with the UglifyJS-plugin (standard in aurelia webpack skeleton production build) you have to make sure to except the materialize module (via `exclude: ['materialize']` if your module is named materialize) from the UglifyJS plugin. Otherwise the names will be mangled and the materialize module won't load correctly (missing dropdown). Another option would be to disable mangle as a global setting on the UglifyJS settings object.

Thanks
Joscha

**Comment by Thanood** [comment]
Thanks! I will add this.
