### ISSUE TITLE
About `md-well`

### ISSUE THREAD

**Issue by bigopon** [aurelia-ui-toolkits/aurelia-materialize-bridge#206]
As I want a collection with `md-waves` attribute but when applying this attribute, the element display type changes to inline block. This leaves me 2 options which are inline CSS or set additional class.

I saw in demo you have nice `<md-well>` component but i don't see the documentation about it anywhere. Does that mean it's not encouraged to use it ?

**Comment by Thanood** [comment]
`<md-well>` is not included in the original Materialize distribution. We focused on these first.
Also it's a bit limited, it only work with a bound router.
I can add documentation, though.

It's used like this:
```html
<md-well router.bind="router"></md-well>
```

It's easy to create an own well which responds to anything. This is the complete code of `<md-well>`:

```html
<template bindable="router">
<style>
  md-well li[md-waves] {
    display: block;
  }
  md-well li a {
    padding: 5px;
    display: inline-block;
    width: 100%;
  }
</style>
  <ul class="z-depth-1">
      <li md-waves="color: primary;" repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
          <a href.bind="row.href">${row.title}</a>
      </li>
  </ul>
</template>
```

**Comment by bigopon** [comment]
Hi, thanks for that.

I decided to used inline style to keep things simple.

I'll close this.
