### ISSUE TITLE
`md-card` text-align problem

### ISSUE THREAD

**Issue by bigopon** [aurelia-ui-toolkits/aurelia-materialize-bridge#208]
Hi, There is a invalid (I assume) css rule for `md-card` as `.card-content` has `text-align: center`

This is not a desired style for every card. This should be as default 'left' or just unset. I'm using version `0.10.0`

**Comment by Thanood** [comment]
Thanks for mentioning this. I'm not sure where that is coming from. This is the complete css for `md-card`:

```css
md-card {
  display: block;
}
```

But it doesn't seem to be set by Materialize itself, either.
I'll have another look later to be sure.

**Comment by Thanood** [comment]
The card in this gist has no `text-align: center;`:
https://gist.run/?id=7c6f695313e2a3fe7755a3c85a8e5557

Could it be possible that this rule comes from another class in your css?
If not, would you mind to share your code (just fork the gist and link it here)?

**Comment by bigopon** [comment]
Please disregard.
I developed from Aurelia Skeleton and the rule come from basic css the application.
Thanks for your help and sorry for this.
