### ISSUE TITLE
Implement navbar

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#21]
The current NavBar is still using Bootstrap and it's only because Bootstrap is loaded after Materialize (at least I think that's the reason). Also everyone likes NavBars. :smile: 

Implementing NavBar as a custom component allows for assigning a global ```primary``` color as the background. Implementing it as a custom element I think it will be easier to implement a [fixed navbar](http://materializecss.com/navbar.html) because that wraps the actual navbar in another wrapper.

Usage example:
```html
<md-navbar fixed="true">
  <a href="#!" class="brand-logo">Logo</a>
  <ul class="right hide-on-med-and-down">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li class="active"><a href="collapsible.html">JavaScript</a></li>
  </ul>
</md-navbar>
```

Which translates to:
```html
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Logo</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="sass.html">Sass</a></li>
          <li><a href="badges.html">Components</a></li>
          <li class="active"><a href="collapsible.html">JavaScript</a></li>
        </ul>
      </div>
    </nav>
  </div>
```

**Comment by adriatic** [comment]
I like your approach of showing together the Aurelia and Materialize syntax!

**Comment by Thanood** [comment]
It's my way of not forgetting things. :smile:

**Comment by Thanood** [comment]
Any opinions on having the main navigation links on the left vs on the right?
