### ISSUE TITLE
Override template for component.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#212]
Is it possible to override a component template ?

The one in question is 

https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/pagination/pagination.html

I would like to hide the number links to each page in the middle. However, there is no if.bind for that feature. 
The reason I want it hidden is I have many thousands of items and too many links are displayed.

Thanks

**Comment by Thanood** [comment]
Maybe we could do it with slot, where the current template is the default slot.
Or add it as an option. How would you do it?

**Comment by glennpierce** [comment]
Ideally I would add it as an option. Although in reality the pagination should never probably show more pages than a set amount.

Ie 
Usually you would see something like below

< 1, 2, 3, 4, 5, 6, 7 ...  >

and as you move along pages it changes to

< ... 4 ,5, 6, 7, 8, 9, 10 ... >


I could try to implement this if you want.

**Comment by Thanood** [comment]
I guess you mean something like the pagination here: http://forums.civfanatics.com/showthread.php?t=570683&page=51
(albeit prettier :smile: )

> I could try to implement this if you want.

That would be great, of course. :smile:

**Comment by glennpierce** [comment]
Yep. I will have a go

**Comment by glennpierce** [comment]
Created a pull request for this
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/214
Thanks

**Comment by Thanood** [comment]
Added an indicator "..." to the template when the first and last are not visible.

![image](https://cloud.githubusercontent.com/assets/677826/17052416/a7171d8a-4ffd-11e6-8884-ecd4f641a8f8.png)

**Comment by glennpierce** [comment]
Found a bug in my code. I get decimal links when you have an odd number of visible links.
One line patch below.

Thanks

diff --git a/src/pagination/pagination.js b/src/pagination/pagination.js
index 6a95359..cbc28f7 100644
--- a/src/pagination/pagination.js
+++ b/src/pagination/pagination.js
@@ -74,7 +74,7 @@ export class MdPagination {
 
   generatePageLinks() {
     let numberOfLinks = parseInt(this.mdVisiblePageLinks, 10);
-    let midPoint = (numberOfLinks / 2) + 1;
+    let midPoint = parseInt((numberOfLinks / 2)) - 1;
     let start = Math.max(this.mdActivePage - midPoint, 0);
     let end = Math.min(start + numberOfLinks, this.mdPages);

**Comment by Thanood** [comment]
merged and published
