### ISSUE TITLE
Fix tab styling

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#22]
The last tab in a tab strip causes to display a horizontal scrollbar even if there is enough space left (f.i. with only three tabs).

**Comment by adriatic** [comment]
Is this behavior 

> The last tab in a tab strip causes to display a horizontal scrollbar even if there is enough space left (f.i. with only three tabs).

present in Materialize - or only in aureliaized tabstrip?

**Comment by Thanood** [comment]
It seems to be present in Materialize but it may be due to my lack of css-fu because I've fixed this in the "code preview" section of waves/colors.

**Comment by Thanood** [comment]
Seems to be okay with #36 applied.

**Comment by Thanood** [comment]
Reopened, since the tabs basic sample still has this issue.

**Comment by Thanood** [comment]
This may be related: https://github.com/Dogfalo/materialize/issues/2635

**Comment by Thanood** [comment]
And it's gone.. Don't know why. Let's see if it appears again. :smile:

**Comment by Thanood** [comment]
I'll keep this open but "done" because I couldn't find out yet why it happened.

**Comment by Thanood** [comment]
This seems to be the reasin why it happens:
https://github.com/Dogfalo/materialize/pull/2809

**Comment by adriatic** [comment]
I really like your attention to details and the persistence it takes to take care of little imperfections. While this might be a more often present German value, I was raised with sincere appreciation of everything German :-)

**Comment by Thanood** [comment]
I appreciate that.. Always thought of these things being more of a myth. :smile:

**Comment by adriatic** [comment]
No myth there, trust me. Until few years ago, I drove Mercedes S550 - just about everything in that car is perfect.

**Comment by Thanood** [comment]
That really **is** a great car! :smile: 
Btw. did you know this little gem? https://github.com/auchenberg/volkswagen

**Comment by adriatic** [comment]
Great gem!!

**Comment by Thanood** [comment]
The css tab in waves/colors in way off:

![image](https://cloud.githubusercontent.com/assets/677826/13372623/39f697c8-dd4b-11e5-951b-b9435d56ba98.png)

**Comment by Thanood** [comment]
Most probably fixed in next Materialize release: https://github.com/Dogfalo/materialize/issues/2584#issuecomment-198151364

**Comment by Thanood** [comment]
This seems to be fixed.
