### ISSUE TITLE
Dropdown options not working

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#224]
Known Materialize issue: https://github.com/Dogfalo/materialize/issues/3417#issuecomment-235537425
A fix is included in master there.

**Comment by dgonzalezr** [comment]
I updated to master, and still the same..
https://github.com/Dogfalo/materialize/issues/3417#issuecomment-235537425

**Comment by Thanood** [comment]
Override the current implementation with the fixed version since next Materialize release seems to take some time.

**Comment by Thanood** [comment]
Fixed with 0.97.8
