### ISSUE TITLE
Feature request: Enable html-attribute in tooltip

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia-ui-toolkits/aurelia-materialize-bridge#228]
Hi Daniel,

I would love to see the html option in the tooltip component:

> html	Allow custom html inside the tooltip. (Default: false)
[Materialize page for tooltip](http://materializecss.com/dialogs.html)

Any chance on adding this? Otherwise I would consider a pull request implementing this.

Thanks
Joscha

**Comment by Thanood** [comment]
Should be easy enough, I guess. Just a new `@bindable` and a change to the `tooltip` call..
I can add this.

If you'd like to make a PR anyway, feel free to do so. :smile: 
In that case, please adjust your commit messages to follow our [commit message conventions](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol).
Would be something like "feat(md-tooltip): add html switch".

I can merge and release in a few hours from now, when I get home.

**Comment by JoschaMetze** [comment]
Having problems right now to correctly build aurelia-materialize-bridge (jspm over mobile on a train doesn't really work...). So no pull request today. If you don't have time to add this till the end of the week I'll create the pull request on Friday.

**Comment by Thanood** [comment]
Just added the change. Thanks again. :smile:
