### ISSUE TITLE
md-datepicker does not show up

### ISSUE THREAD

**Issue by fracz** [aurelia-ui-toolkits/aurelia-materialize-bridge#233]
I have followed the installation instructions of materialize-bridge and most of components work well.

However, whey I try this one:

```html
<input md-datepicker="container: body; value.two-way: selectedDate;" type="date" placeholder="pick a date" />
```

And click on the field, the datepicker is not showing up. The field focuses only (the bottom border is lightened).

When I try with "simple" input like

```html
<input type="date" class="datepicker" id="mypicker">
```

And execute the following in the console

```js
$("#mypicker").pickadate();
```

Then the datepicker works on that field.

What might be the reason why the `md-datepicker` component does not work? bridge 0.13.0, Aurelia 1.0.1.

**Comment by Thanood** [comment]
I guess I will have to try this myself... And prepare a new gist bundle. Will try it tomorrow. Does the demo work?

**Comment by Thanood** [comment]
@fracz Do you use JSPM or webpack?
Do any other of the components work? For example `md-input` or `md-select`?

**Comment by fracz** [comment]
JSPM. I can confirm `md-input` works because I've tried it. Currently have no ability to try the others.

I'll check this when I'm at work.

**Comment by Kukks** [comment]
I'll try it out first thing tomorrow morning,  most likely I caused the bug
with the changes to the control.  What happens when you leave out the
container setting?

**Comment by Kukks** [comment]
Seems to work when using the same code provided on the samples app. No errors at all?

**Comment by Thanood** [comment]
@fracz I cannot reproduce this, sorry.. Whatever I do, it works. :smile: 
Can you upload a reproduction?

**Comment by fracz** [comment]
Strange. 

After I got home from holidays and run the same example again, it works. I might have not built something or I accidentally hit some corner case.

I will open this issue when it reoccurs.

**Comment by Thanood** [comment]
Or maybe it was a cache issue with your last call before holidays.. :smile:
