### ISSUE TITLE
autocomplete missing ?

### ISSUE THREAD

**Issue by m4s0fd1s** [aurelia-ui-toolkits/aurelia-materialize-bridge#234]
Hello,

when I installed aurelia-materialize-bridge in my skeleton-esnext project, everything worked well when I tried the app with 

`gulp watch`

However, bundling and export with gulp export didn't work. 

What I did, was adding this in my bundles.js

`        "materialize",`
`        "aurelia-materialize-bridge",`
`        "aurelia-materialize-bridge/**/*.html!text",`
`        "aurelia-materialize-bridge/**/*.css!text",`

and in export.js I added

`, [`
 `     'materialize', [`
 `       '/fonts/roboto/*'`
 `     ]`
`],`

Now running the app with 

`gulp serve-export` 

gives me the following error

`system.js:4 GET http://localhost:9001/jspm_packages/npm/aurelia-materialize-bridge@0.13.0/autocomplete/autocomplete.js 404 (Not Found)`

By changing 

bridge.useAll() to only the parts I needed, I didn't receive this error... However it would be nice, I can also use the autocomplete feature.

Looking at your source, I think the export is missing in

`/src/index.js`

**Comment by Thanood** [comment]
You're right but it worked before without all the exports.. To be honest, I seem to have lost track on how bundling works. *sigh*
Need to catch up on that. I'll add the autocomplete export. Thanks for reporting. :smile:
