### ISSUE TITLE
Document usage and development of the first components used

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#24]
Describe usage and development of md-tabs, mb-button, md-collapsible and md-navbar as an online-help article in "App developers tutorials" and "Bridge developers tutorials".

- [x] [AppDev-tutorials:-1.-Introduction](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-1.-Introduction-(r2))
- [x] [AppDev-tutorials:-2.-Setup](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-2.-Setup-(r3))
- [x] [AppDev-tutorials:-3.-Select-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-3.-Select-component)
- [x] [AppDev-tutorials:-4.-Button-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-4.-Button-component)
- [x] [AppDev-tutorials:-5.-Slider-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-5.-Slider-component)
- [x] [AppDev-tutorials:-6.-Collapsible-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-6.-Collapsible-component)

---

- [x] [BridgeDev-tutorials:-1.-Introduction](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-1.-Introduction-(r2))
- [x] [BridgeDev-tutorials:-2.-Setup](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-2.-Setup-(r2))
- [x] [BridgeDev-tutorials:-3.-Select-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-3.-Select-component)
- [x] [BridgeDev-tutorials:-4.-Button-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-4.-Button-component)
- [x] [BridgeDev-tutorials:-5.-Slider-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-5.-Slider-component)
- [x] [BridgeDev-tutorials:-6.-Collapsible-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/BridgeDev-tutorials:-6.-Collapsible-component)

**Comment by Thanood** [comment]
- [ ] [AppDev-tutorials:-1.-Introduction](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-1.-Introduction)
- [ ] [AppDev-tutorials:-2.-Setup](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-2.-Setup)
- [ ] [AppDev-tutorials:-3.-Tabs-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-3.-Tabs-component)
- [ ] [AppDev-tutorials:-4.-Button-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-4.-Button-component)
- [ ] [AppDev-tutorials:-5.-Collapsible-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-5.-Collapsible-component)
- [ ] [AppDev-tutorials:-6.-NavBar-component](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-6.-NavBar-component)

**Comment by Thanood** [comment]
As skeleton-navigation users are dealing with a Bootstrap app and mixing that with Materialize screws up layout - and because Materialize doesn't have such a great control like kendo-grid - I think we could show components here which fix the layout and end up with removing Bootstrap.

**Comment by adriatic** [comment]
I disagree. Please check **[this section](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/wiki/Aurelia-Bridge-to-KendoUI-User-Interface-Toolkit#7-moving-ahead)** which will better explain our intent with the expected future of the skeleton bridge concept (to make a set of templates that can be used to build many different types of Aurelia applications

For example, we did not mention layout anywhere in the KendoUI online help or other documents, since using Bootstrap's layout (rows and columns) is pretty sufficient to ensure that the catalog application conforms to the "Mobile first design"

**Comment by Thanood** [comment]
I should have stated "show components which have the **side-effect of fixing the layout**". Reading my comment again it reads like there are some components which literally "fix the layout". There aren't, sorry for the confusion.

What I meant basically was: "describe NavBar and Button". These "fix the layout" by enabling the user to remove Bootstrap because they are the only "real" Bootstrap controls used in skeleton-navigation apart from well.

These are in my list anyway (topics 4 and 6) - I'd just change the order and maybe post a short info under [the first screenshot of "setup"](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/AppDev-tutorials:-2.-Setup-(r2)): "Don't worry, we'll fix that NavBar" - then have NavBar described right in the next step.

The description of NavBar would not have any layout stuff mentioned. But when it's ready it looks good again. :smile: 
Then maybe switch one component on the list with an input field.

What are your thoughts on that?

**OR** forget all of the above and move on as normal. But then I'd still want to give an info on why it looks so different to the standard skeleton-navigation.

(btw. you could mix Bootstrap and Materialize but then you'd have to literally fix the layout)

**Comment by Thanood** [comment]
:relieved:
