### ISSUE TITLE
Generate blur event from md-input

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia-ui-toolkits/aurelia-materialize-bridge#240]
It would be nice if `md-input` generated `blur` when underlying `input` generates one.
For now, `aurelia-validation` does not automatically validate unless validate trigger is `change`.

**Comment by Thanood** [comment]
I suppose you closed this issue because of this PR: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/236

If not, please tell me. :smile:
