### ISSUE TITLE
input label in Edge misplaced

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia-ui-toolkits/aurelia-materialize-bridge#244]
Input label is incorrectly positioned in Edge 25.10586

![image](https://cloud.githubusercontent.com/assets/3712700/18115669/90d9307a-6f84-11e6-92d2-31e5a9652011.png)

**Comment by MaximBalaganskiy** [comment]
Presence of `col` class on `div.input-element` fixes that

**Comment by Thanood** [comment]
Thanks, @MaximBalaganskiy I will have a closer look ai it when I have access to Edge (in the evening today or tomorrow).

**Comment by Thanood** [comment]
You're right and I've been wondering why it doesn't affect the Materialize website. It seems like they compensated for this only on their website but not in the framework..

Will fix this.
