### ISSUE TITLE
validationRenderer

### ISSUE THREAD

**Issue by Ullfis** [aurelia-ui-toolkits/aurelia-materialize-bridge#245]
Current validationRenderer overwrite aurelia validation error messages. Multiple different error messages get lost during the renderer process. Custom list of errors look strange with same repeating message.

The Materialize error label is one line? Multiple messages in that line would look a bit rare?

Suggestions are welcome

Here is my suggestion:

- if md-validate-error is set, use that. If not, concentrate error messages into error label separated with '; ' [mention here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/112ddf8eaff66d54eceb05f85960f62d5166b1f9#commitcomment-18837613). [Remove data-error attribute on success](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/241) if so.

- do not change aurelia validation messages.

Code:

```javascript

export class MaterializeFormValidationRenderer {

  render(instruction) {

    // remove errors
    for (let { error, elements } of instruction.unrender) {
      for (let element of elements) {
        this.remove(element, error);
      }
    }

    let errors = [];
    // loop errors and group them for each element
    for (let { error, elements } of instruction.render) {
      for (let element of elements) {

        // group errors
        let elementId = element.getAttribute('au-target-id');
        if (!errors[elementId]) errors[elementId] = { element:element, errors:[] };
        errors[elementId].errors.push(error);
      }
    }

    // add errors
    for (let elementId in errors) {
      this.add(errors[elementId].element, errors[elementId].errors);
    }
  }

  add(element, errors) {
    switch (element.tagName) {
    case 'MD-INPUT': {
      let input = element.querySelector('input');
      if (input) {
        input.classList.remove('validate');
        input.classList.remove('valid');
        input.classList.add('invalid');

        // build error message
        let errorMessage = '';
        for (let error of errors) {

          // focus target
          error.target = input;

          // make validation error messages fit into error label
          if (error.message) {
            if (errorMessage) errorMessage += '; ';
            errorMessage += error.message;
          }
        }

        let label = element.querySelector('label');
        if (label) {
          // label.classList.add('active');

          // get error message from label
          let msg = label.getAttribute('data-error');
          if(!msg) {
            // error message not set? add
            label.setAttribute('data-error', errorMessage);
            label.setAttribute('data-amb-tmp', 'err');
          } else {
            // present custom error only and let error-list list details?
            // set label message into error object
            // error.message = msg;
          }
        }
      }
      break;
    }
    default: break;
    }
  }

  remove(element, error) {
    switch (element.tagName) {
    case 'MD-INPUT': {
      let input = element.querySelector('input');
      if (input) {
        input.classList.remove('invalid');
        input.classList.add('valid');

        let label = element.querySelector('label');
        if (label && label.getAttribute('data-amb-tmp')) {
          label.removeAttribute('data-error');
          label.removeAttribute('data-amb-tmp');
        }

      }
      break;
    }
    default: break;
    }
  }

}

```

To test it, save it to a file in your project and import it.

```javascript

import { MaterializeFormValidationRenderer } from './your-file';

  constructor(controller) {
    this.controller = controller;
    this.controller.addRenderer(new MaterializeFormValidationRenderer());
  }


and add some stuff to your validation rule:

ValidationRules
    .ensure('firstName').required().minLength(2).email()
```

refs:
- [implement validation](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/126)
- [Remove data-error attribute when removing errors
](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/241)
- [overwriting error messages]( https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/112ddf8eaff66d54eceb05f85960f62d5166b1f9#commitcomment-18837613)

**Comment by Thanood** [comment]
There's a recent comment on a PR I can't seem to find right now mentioning this, including a suggestion (which you asked for :smile: ).. I'll try to find it.

**Comment by Ullfis** [comment]
Adding style to error message

```html
  <style>
    md-input label[data-error]:after {
      transition: .2s ease-out;
      white-space: nowrap;
      font-size: 0.8rem;
      -webkit-transform: translateY(0);
      -ms-transform: translateY(0);
      transform: translateY(0);
    }

    md-input label[data-error]:not(.active):after {
      -webkit-transform: translateY(-140%);
      -ms-transform: translateY(-140%);
      transform: translateY(-140%);
    }
  </style>
```

and some changes:

- removing validate class from input

```javascript
        // only used when input leverages HTML5 validation?
        input.classList.remove('validate');
```

- ; only between error messages
```javascript
          // make validation error messages fit into error label
          if (error.message) {
            if (errorMessage) errorMessage += '; ';
            errorMessage += error.message;
          }
```

**Comment by Thanood** [comment]
@Ullfis Found the PR comment I mentioned earlier.
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/112ddf8eaff66d54eceb05f85960f62d5166b1f9#commitcomment-18837613

**Comment by Ullfis** [comment]
Ignore materialize way of showing the error. Following code remove validate on input and data-error on label. It also add a div for each error into md-input component. No custom error message from md-validate-error.

Minor changes in code from http://www.sobell.net/aurelia-validation/

```javascript
export class MaterializeFormValidationRenderer {

  render(instruction) {

    for (let { error, elements } of instruction.unrender) {
      for (let element of elements) {
        this.remove(element, error);
      }
    }

    for (let { error, elements } of instruction.render) {
      for (let element of elements) {
        this.add(element, error);
      }
    }
  }

  add(element, error) {
    switch (element.tagName) {
    case 'MD-INPUT': {
      let input = element.querySelector('input');
      if (input) {
        input.classList.remove('validate');
        input.classList.remove('valid');
        input.classList.add('invalid');
        error.target = input;
      }

      let label = element.querySelector('label');
      if (label) {
        label.removeAttribute('data-error');
      }

      const message = document.createElement('div');
      message.className = 'validation-message-div';
      message.style.cssText = 'margin: -16px 0 16px 0; font-size: 0.8rem;color:red;';
      message.textContent = error.message;
      message.id = `validation-message-${error.id}`;
      element.appendChild(message, element.nextSibling);
      break;
    }
    default: break;
    }
  }

  remove(element, error) {
    switch (element.tagName) {
    case 'MD-INPUT': {
      let input = element.querySelector('input');
      if (input) {
        input.classList.remove('invalid');
        input.classList.add('valid');

        // remove error div
        const message = element.querySelector(`#validation-message-${error.id}`);
        if (message) {
          element.removeChild(message);
        }
      }
      break;
    }
    default: break;
    }
  }

}

```

Try it. No styles needed (except for error color).

**Comment by Ullfis** [comment]
![error](https://cloud.githubusercontent.com/assets/10699174/18142689/06dbc578-6fbf-11e6-93ae-3a6c5c6c6968.png)

**Comment by Ullfis** [comment]
I changed something and needed styling. Added it to md-colors. Hope it's ok.

md-validate="true" is needed for md-validate-success message. md-validate-error is ignored and removed from label attribute. #246

**Comment by Thanood** [comment]
I'm wondering if we should rename the element (`md-layout` or something) or create a separate one. It definitely does more than colors now. On the other hand I guess most people use it anyway. #243 has a similar "issue" importing css from js.

**Comment by Thanood** [comment]
Hmm, I'm trying to come up with an example having multiple validation messages at once but I can't seem to get it. :smile: 

Any idea? Would be nice to show.

**Comment by Ullfis** [comment]
There could be two renderer included in the library. One for multi line errors and one for using materialize function (label)

MaterializeFormValidationRenderer
MaterializeMultilineRenderer or something

**Comment by Thanood** [comment]
Or an option to the renderer? It's used like a simple class anyway so we could as well send arguments to the constructor.

But why would you seperate them? Isn't a single line renderer basically the same as a multiline renderer displaying a single line?
I mean I'm all for separation of concerns but I don't understand the motivation. But I must confess I still didn't have a deeper look at the multiline error messages.
