### ISSUE TITLE
blur event on md-select

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia-ui-toolkits/aurelia-materialize-bridge#248]
`blur` event is not generated from `md-select`, which prevents validation triggering unless `change` trigger is set on a controller. This is not super important as I can always call validation manually...

**Comment by Thanood** [comment]
Alternatively you could set the trigger to `change`.
At the moment I'm not sure if we can actually do this without hacking into materialize events. I'm not sure if the "real" select `blur`s at all - probably does, but it doesn't receive focus so how would it lose focus? :smile: 

I'll try it, though.

**Comment by Ullfis** [comment]
I have a solution [here](https://github.com/Ullfis/aurelia-materialize-bridge/commit/f2197529ea84c62680838b1222ba968adada9a43). Should I spam another pull request?

**Comment by Thanood** [comment]
Please do.. :smile:

**Comment by Thanood** [comment]
Oh, should I merge your other PR then?

**Comment by Ullfis** [comment]
Yes, both of them. One change the validationRenderer to show error messages. The other change md-select to forward blur event. :cake:

**Comment by Ullfis** [comment]
ehmm.. I also added the forward blur event to checkbox [here](https://github.com/Ullfis/aurelia-materialize-bridge/commit/c5c451e90862b83b7fac34f8bf5092f83d0355fc) and switch [here](https://github.com/Ullfis/aurelia-materialize-bridge/commit/0eb63b5b983725099e735e205022212c6ba27b9b). But have not made any error list for validation yet (if needed). Would it be interesting to add pull requests for the blur events?

**Comment by Thanood** [comment]
I'm not sure why you would validate a boolean element. Maybe `required` for some options like "Yes, I've read the important stuff and I'm okay with it"..

So if `aurelia-validation` uses `blur` by default this would be interesting, yes.

Btw. the select `blur` is fired now. But validation doesn't seem to be triggered in [this example](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/samples/select/validation.js). Any idea why?

**Comment by Ullfis** [comment]
I just tried your master branch and the example works on both Chrome and Firefox. Can you try to add '.on(this)' to your code?

```javascript
  rules = ValidationRules
    .ensure('selectedValue')
      .required()
      .on(this)
      .rules;
```

I will add pull request for blur event on checkbox and switch. But no validation renderer for now.

**Comment by Ullfis** [comment]
I just cloned the project into a new folder and did an npm i && jspm i && cd sample && npm i && jspm i.

Still working.

**Comment by Thanood** [comment]
Maybe I need to update jspm dependencies. I'll try it.

**Comment by Thanood** [comment]
Still doesn't validate on blur (Chrome on Windows).. Strange. I will try with a fresh clone.

Btw. This throws an error in IE 11 here:
```javascript
const selectWrapper = element.closest('.select-wrapper');
```

element.closest is not defined. There is a polyfill [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Polyfill) which I'll add.

**Comment by Ullfis** [comment]
Hmmm... I am looking at the select validation. First time I open the select list and select an item, the validation blur event runs before item is visually added to the input and bound variable updated.

**Comment by Thanood** [comment]
I guess because native `select` sends `change` then `md-select`picks it up and handles it while the `blur` event gets handled before.
The underlying native `select` should be updated by that time. But okay, it's a hint. :smile:

**Comment by Ullfis** [comment]
[parentElement](http://www.w3schools.com/jsref/prop_node_parentelement.asp) should be supported in IE11.

```javascript
      const selectWrapper = element.parentElement;
      if (!(selectWrapper && selectWrapper.classList.contains('select-wrapper'))) {
        return;
      }
```

**Comment by Thanood** [comment]
Just added the polyfill. I wanted a polyfill collection anyway. :smile: 
Need to refine it but still a start.

**Comment by Ullfis** [comment]
It is possible to delay blur event and give the bound variable time to update.

https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/select/select.js#L62

```javascript

  handleBlur() {
    setTimeout(()=> {
      fireEvent(this.element, 'blur');
    }, 200);
  }

```

It works but it doesn't feel right.

**Comment by MaximBalaganskiy** [comment]
TaskQueue should do the job

**Comment by Ullfis** [comment]
Thanks for the suggestion.

I just tried with TaskQueue but it didn't work.

```javascript
        this.taskQueue.queueTask(() => {
          fireEvent(this.element, 'blur');
        });
```

I also tried to reduce timeout to 50 ms. Didn't work.

```javascript
    setTimeout(() => {
      fireEvent(this.element, 'blur');
    }, 50);
```

On my computer the timeout have to be 100 ms or more. Not a good solution.

___

When the select get focus, the select list is shown. When the select loose focus, list is hidden again. Maybe listen to an event and fire blur when list closes?

**Comment by Thanood** [comment]
[Along with the change event, perhaps](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/select/select.js#L78)?

**Comment by Ullfis** [comment]
We could fire blur on change event. But that would not fire blur when select loose focus without any value has been selected.

I tried listening on input close event without luck. It fires before variable is updated. I replaced jQuery removeClass function so it could fire an event when active class was removed from ul-list. No luck.

Scratching my head on this. Don't know what to try next.

**Comment by Thanood** [comment]
Can we hook into this? https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L528

But I guess you already tried that.

**Comment by Thanood** [comment]
Okay, but let's keep this issue open to track it.
Also maybe we should combine it with triggering blur on change. What do you think?

**Comment by Ullfis** [comment]
I gave it a try with blur effect on change. Blur event is fired twice. It could be possible to detect if the blur has been fired from change and not fired it after timer has run. 

Ideally the control shouldn't fire blur before focus is removed. Value changed or not. It kinda work with the timer. The timer is set to 0.2 s. It's just a wild guess. 

This one is to difficult for me. I will make a pull request with the timer and then crawl under a rock.

**Comment by Thanood** [comment]
Okay, I'll try to continue from there.. But don't crawl under a rock. :smile: 
I'll merge the four open PRs now and have a look when I have some time (I'm at work right now).

**Comment by Thanood** [comment]
@Ullfis 
In your PR everything seems fine.. There is no blur on change but it doesn't matter for materialize select.
Even if I just close the dropdown (not selecting anything) it fires a blur event.

Did you observe the same?
If so, the only problem is the timeout?

**Comment by Ullfis** [comment]
I didn't include blur on change in the pull request. Only delayed blur event from input control. It's only the timeout problem. It work (on my computer) but don't know if it need more or less time on other computers. I am not sure where the delay source is. From input blur event to value is changed.

**Comment by Ullfis** [comment]
Good news everyone!

Listening on the display style on the `dropdown-content` and send blur event if display==='none' solves the timing issue.

```javascript

  attached() { ..

    // observe display style on ul dropdown-content
    let drContent = this.element.parentElement.querySelector('.dropdown-content');
    this.mObserver = DOM.createMutationObserver(mutations => {
      // fire multiple times
      let isHidden = false;
      for (let mutation of mutations) {
        if (window.getComputedStyle(drContent).getPropertyValue('display') === 'none') {
            isHidden = true;
        }
      }
      if (isHidden) {
        fireEvent(this.element, 'blur');
      }
    });

    this.mObserver.observe(drContent, {
      attributes: true,
      attributeFilter: ['style']
    });

  }
```

Only catch: #256

```javascript
import { DOM } from 'aurelia-pal';
```

And if  DOM.createMutationObserver support most browsers.
___
<i>crawling out from the rock again</i>

**Comment by Thanood** [comment]
![image](https://cloud.githubusercontent.com/assets/677826/18341422/36dd4d0a-75aa-11e6-92f3-409ade041178.png)

Very tricky.. :smiley: 
I've had some unresolved problems with MutationObservers in IE11 but I'd like to solve that anyway.

Good time to address that aurelia-pal issue again. I guess this one will turn out to be pretty simple.

**Comment by Ullfis** [comment]
[Bootstrapping Older Browsers](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/3) is already described in the docs (IE9+). MutationObserver should be supported in browsers where Aurelia runs.

I will add another pull request :smile:

**Comment by Thanood** [comment]
Yeah I know, got "unsupported method" anyway somehow..
But that's a completely different project so this may be anything.

Btw. I guess if we move `aurelia-pal` from `devDependencies` to `dependencies` it should solve the "`aurelia-pal` not found" issue.

**Comment by Ullfis** [comment]
ai ai.. forgot aurelia-pal dep

**Comment by Thanood** [comment]
So, this is in. :smiley:
