### ISSUE TITLE
Describe including Material Icons in installation instructions

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#249]
Hi

I thought I had this going before.
I am using md-pagination that works but the chevron icons just show as chevron_left and chevron_right
text.
I am using 

<require from="materialize-css/bin/materialize.css"></require>
which seems to load

inspecting the css in chrome shows

.material-icons {
    text-rendering: optimizeLegibility;
    -webkit-font-feature-settings: 'liga';
    -moz-font-feature-settings: 'liga';
    font-feature-settings: 'liga';
}

where in the demo I get

.material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    line-height: 1;
    letter-spacing: normal;
    text-transform: none;
    display: inline-block;
    white-space: nowrap;
    word-wrap: normal;
    direction: ltr;
    -webkit-font-feature-settings: 'liga';
    -webkit-font-smoothing: antialiased;
}

Any ideas ?

Thanks

**Comment by Ullfis** [comment]
Try this in your index.html

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by glennpierce** [comment]
Yep that worked.
Should the docs be updated ?

Thanks

**Comment by Thanood** [comment]
@glennpierce Where would you put that in the docs?

As this information is relatively hidden on [Materialize website](http://materializecss.com/getting-started.html#setup) I guess we should actually add the information.

**Comment by glennpierce** [comment]
I personally would have found it useful

https://aurelia-ui-toolkits.github.io/demo-materialize/#/installation

(On the webpack tab)

**Comment by Thanood** [comment]
Agreed. Will add it.
