### ISSUE TITLE
Implement side-bar

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#25]
If I understood correctly, ```project status``` is a temporary overview.
To be able to present a component catalog using Material principles (and looking familiar to Materialize users), implement a side-bar which holds the categories and examples from ```project status```.

**Comment by adriatic** [comment]
Yes, the `project status` page was created to offer a **quick view** on what is done, what are we working on and what yet has to be done (which makes the task of keeping the information current, important).

At the same time, the wording "quick view" might be important enough to continue maintaining it even when everything is done. There is a problem with a controls hierarchy that is too deep for our "standard" layout which fits most controls (using button as the example of a control that is **not too deep**):

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/12452569/1d9ef86a-bf5d-11e5-9baa-15af19de1585.png"></img>
 <br><br>
Image 1
</p>

Note that besides the obvious selection of the `Samples menu item` (which has already been replaced with `Components catalog`) you need to know that the `Button` component is a member of the `Navigation` category where using `Project status` page based selection requires a single click.

In the case of Charts category, the navigation to a specific chart type requires two more clicks (when compared with `Button`)

**Comment by Thanood** [comment]
I have seen that this structure is from Telerik's KendoUI catalog. That's certainly a good decision because it's familiar to KendoUI users.

Personally, I'd choose another structure and keep it more like Materialize's own structure - for the same reasons mentioned above (familiarity). Although I'm struggling a bit with their structure because... I mean who put "toasts" into the "dialogs" category and "modals" into its own?

I'd really like to have a flat structure, maybe at most three levels deep including the samples' sub-pages. What do you think?

**Comment by adriatic** [comment]
> Personally, I'd choose another structure and keep it more like Materialize's own structure

That is the correct approach - as at least initially, we are trying to attract people familiar with Materialize to use Aurelia. Since Materialize already has defined the catalog of their controls, we should make ours as close to the original as it makes sense

**Comment by Thanood** [comment]
Put into the milestone again because it's handy for mobile-first approach. Currently, the navigation just diappears on phones.

**Comment by Thanood** [comment]
Proposed usage:

```html
<md-sidenav>
  <ul>
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
</md-sidenav>
```

Which translates to:
```html
<div id="slide-out" class="side-nav">
  <ul>
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
</div>
```

The id may perhaps be generated by md-sidenav. Maybe we don't even need it if we use the second approach to the "companion attribute" below.

Custom element since:
1. md-nav-bar is a custom element, increases similarity
2. can contain embedded styles to (at least) manipulate ```<li>``` children with waves (```display: block;``` and ```:hover```)
3. easier to create links using an optionally bound router

Needs a companion atttribute to indicate its collapse button.
```html
<a md-sidenav-collapse><i class="mdi-navigation-menu"></i></a>
```

Which translates to:
```html
<a data-activates="slide-out"><i class="mdi-navigation-menu"></i></a>
```

This attribute will then be initialized by:
```javascript
$(this.element).sideNav();
```

or
```html
<a md-sidenav-collapse="side-nav-viewmodel-ref"><i class="mdi-navigation-menu"></i></a>
```

Which translates to:
```html
<a><i class="mdi-navigation-menu"></i></a>
```

This attribute will handle opening/closing the side-nav itself using the view-model.ref.

**Comment by Thanood** [comment]
```md-sidenav``` differs from original implementation on two ways:
1. Configuration is done on the sidenav itself and not on its trigger-button. I found that to be counter-intuitive.
2. ```closeOnClick``` has its default value set to ```true```
