### ISSUE TITLE
Need help with pagination

### ISSUE THREAD

**Issue by Ganbin** [aurelia-ui-toolkits/aurelia-materialize-bridge#253]
Hello,

I have a strange behaviour, again with a CLI installation.

When I put `md-pages="5"` the number of page is correct, but if I use `md-pages.bind="worktime._count"` I don't get no page. And it is the same for the other attributes when I try to use the `.bind`.

**Comment by Ullfis** [comment]
```javascript
  worktime = {
    _count: 6
  };

  _count = 6;
```

```html
        <md-pagination
          md-pages.bind="worktime._count">
        </md-pagination>

        <md-range 
          md-value.bind="worktime._count" 
          md-min="1" 
          md-max="10" 
          md-step="1">
        </md-range>

        <md-pagination
          md-pages.bind="_count">
        </md-pagination>

        <md-range 
          md-value.bind="_count" 
          md-min="1" 
          md-max="10" 
          md-step="1">
        </md-range>
```
works here in a cli project

What do you get if you add this to your html?

```html
<h1>${worktime._count}</h1>
```

**Comment by Thanood** [comment]
@Ganbin Any news?

**Comment by Ganbin** [comment]
Sorry for the delay.

I have test with your code and effectively it works.

I think the difference is that my data come from a server asynchonously, so I think the component is already loaded.

So is there a way to get my data before the initialization of the aurelia-materialize component?

**Comment by Ganbin** [comment]
Hello sorry for delay.

I don't know what I was doing wrong but now it works. Sorry for disagreements.

**Comment by Thanood** [comment]
Glad it works now 👍
