### ISSUE TITLE
Check usage of aurelia-pal

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#256]
When installing the bridge in a new skeleton project, the bridge loads `aurelia-pal` as a dependency which is not installed as a top-level dependency in the current skeleton.

See:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/204#issuecomment-244968036

Do we need `aurelia-pal` at all (apart from testing but then it's in the wrong dep category)?

**Comment by Ullfis** [comment]
my bad

https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/input/input.js#L2

It is used to throw blur event.

**Comment by Thanood** [comment]
Actually I guess it's better to use DOM like you did. 
But I thought I had understood JSPM and that's obviously not the case. :smile:

Why is pal expected as a top level dependency?

**Comment by Ullfis** [comment]
I didn't discover [fireEvent](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/select/select.js#L78) before playing with the select. Maybe we could use that function on the input instead?

**Comment by Thanood** [comment]
Sure we could do that. But that doesn't solve the queston for me. :smile: 
Actually a lot of packages in the skeleton depend on `aurelia-pal` (including the framework itself) and it doesn't complain when the bridge isn't called.

Let's do this anyway to get this out of the way. But I'll have a look into it.

**Comment by victormaestri** [comment]
> Dis you run jspm update?
> For a quick fix try jspm install aurelia-pal but I suppose this should be pulled by Aurelia skeleton already.
> 
> Anyway, I wonder why this happens.

> I just took a completely new download of the esnext skeleton (from their "releases" tab) and installed materialize and the bridge. I can reproduce this issue.
> 
> We may have an unnecessary dependency on aurelia-pal which is missing in the skeleton. I'd like to check this out.
> 
> Did my "quick fix" work, btw? :smile:

@Thanood, thanks! I just try `jspm install aurelia-pal` and work.

**Comment by Thanood** [comment]
great :+1:
