### ISSUE TITLE
Change how Materialize is included

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#26]
At the moment, the catalog application imports Materialize CSS **and** JS. Change it to only use CSS and let the bridge take control of Materialize's JS parts.

**Comment by adriatic** [comment]
I disagree with this approach since we made the decision not to task the bridge with any UI responsibilities - leaving this intentionally to the application developer.

**Comment by Thanood** [comment]
You're right, that was my intention. :smile: 
But you explained it more thoroughly.
