### ISSUE TITLE
Materialize initialized twice on bundled JSPM apps

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#263]
@MaximBalaganskiy encountered a problem where the dropdown component was initialized twice in his app and therefore showed only the default options (:point_up: [7. September 2016 07:07](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=57cfa0a868f483b41caab173)).

The reason for that seems to have been asynchronous module load order where Materialize finished loading after the dropdown element `attached()`, thus re-initializing Materialize.

[Here's also his StackOverflow question](http://stackoverflow.com/questions/39403683/attached-method-is-called-before-document-ready).

This seemed to have been resolved by enforcing load order on Materialize and aurelia-bootstrapper.

As of today enforcing load order does not do the trick anymore. :point_up: [9. September 2016 05:35](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=57d22dff89655972304fee1a)

edit: This happens since we removed the direct Materialize dependency from the bridge..

**Comment by Thanood** [comment]
Now I'm curious.. Any idea why load order does not work anymore?
Here's my point of view:
* You tell the browser "load materialize first and when you're ready, load aurelia-bootstrapper".
* That happens short before DOMContentLoaded is fired (right?)
* So whatever happens, if this works, then document.ready should trigger before Aurelia starts. Does that happen, too?

**Comment by MaximBalaganskiy** [comment]
I think the minified module loads really fast and document.ready is fired
after that. So enforcing would work.... If anything think making it load
slower will work...

**Comment by MaximBalaganskiy** [comment]
*sorry, enforcing wouldn't work... A typo

**Comment by Thanood** [comment]
@MaximBalaganskiy Can you share your bundle config?
I'm getting some errors about not being able to redefine a property..

Because of that, I've excluded the bridge's JS files from the bundle and it also happens.
I've logged `DOMContentLoaded` and Materialize's `document.ready` for dropdown. This is the log output:

```
-- DOMContentLoaded
-- dropdown init
-- dropdown init finished
DEBUG [aurelia] Loading plugin aurelia-templating-binding.
DEBUG [aurelia] Configured plugin aurelia-templating-binding.
DEBUG [aurelia] Loading plugin aurelia-templating-resources.
DEBUG [aurelia] Configured plugin aurelia-templating-resources.
DEBUG [aurelia] Loading plugin aurelia-event-aggregator.
DEBUG [aurelia] Configured plugin aurelia-event-aggregator.
DEBUG [aurelia] Loading plugin aurelia-history-browser.
DEBUG [aurelia] Configured plugin aurelia-history-browser.
DEBUG [aurelia] Loading plugin aurelia-templating-router.
DEBUG [aurelia] Configured plugin aurelia-templating-router.
DEBUG [aurelia] Loading plugin aurelia-materialize-bridge.

... more aurelia stuff
```

So this is actually the correct order.. But the issue remains.

**Comment by Thanood** [comment]
This is strange.. After playing around with the bundle config, dropdown initializes correctly. And I have a state now that's in no way different to the original! :confused:

**Comment by Thanood** [comment]
Okay, I'm going nuts.. :smile: 

There *is* a difference:
When I remove the `DOMContentLoaded` listener the issue happens again!

**Comment by MaximBalaganskiy** [comment]
I think it doesn't really depend on bundling or anything else - all that matters is when attached is called. Sometimes it's called after document.ready, especially when modules are not bundled or not minified. But sometimes module loader is faster than dom parser (pardon my language, i'm not a specialist :) and this causes the issue

**Comment by MaximBalaganskiy** [comment]
i bet, if you import aurelia-bootstrapper on document.ready it will fix the issue

**Comment by MaximBalaganskiy** [comment]
Could it be that the browser queues the document.ready callback and executes it later?

**Comment by Thanood** [comment]
jQuery's `document.ready` is implemented using a promise, so anything you put into the callback is executed immediately if the event has already been fired.

You can check this with a simple test in console after everything has loaded:
```javascript
$(document).ready(function() { console.log('I am ready!'); });
```

So the answer is "yes" in a way.. The browser doesn't queue up anything but if you call `ready` after that, it's executed anyway.

Having said that, the console log for dropdown only appears once. So... Just guessing but is there a second Materialize interfering?

btw. this breaks my app.. `dropdown not defined`:
```javascript
System.import('materialize-css').then(function() {
  console.log('materialize loaded');
  return System.import('aurelia-bootstrapper');
});
``´

Anything wrong there?

Would you mind to share your bundle config anyway?

**Comment by Thanood** [comment]
In my last run I've got

```
-- dropdown init
-- dropdown init finished
```

at the end of the console log.

**Comment by Thanood** [comment]
Okay, I have an idea.
Promises are guaranteed to execute, right? And, if I remember correctly, the order of execution is guaranteed to be in the order of adding callback..

Importing Materialize sets a callback to the `document.ready` promise. If we load Aurelia after that, it may work.

So, main.js:

```javascript
export function configure(aurelia) {
  return System.import('materialize-css').then(() => {
    aurelia.use
      .standardConfiguration()
      .developmentLogging()
      .plugin('aurelia-materialize-bridge', b => b.useAll());

    return new Promise(resolve => {
      $(document).ready(() => {
        aurelia.start().then(() => aurelia.setRoot()).then(() => resolve());
      });

    });
  });
}
```

It's hard to test but this worked in 20 consequent runs.

**Comment by MaximBalaganskiy** [comment]
```
var gulp = require("gulp");
var bundler = require('aurelia-bundler');
var del = require("del");

var aureliaBundle = {
	"includes": [
		"aurelia-auth",
		"aurelia-bootstrapper",
		"aurelia-event-aggregator",
		"aurelia-fetch-client",
		"aurelia-framework",
		"aurelia-materialize-bridge",
		"aurelia-materialize-bridge/**/*.html!text",
		"aurelia-materialize-bridge/**/*.js",
		"aurelia-materialize-bridge/**/*.css!text",
		"aurelia-templating",
		"aurelia-templating-binding",
		"aurelia-templating-resources",
		"aurelia-templating-router",
		"aurelia-validation",
		"aurelia-loader-default",
		"aurelia-router",
		"aurelia-history-browser",
		"aurelia-logging-console",
		"bluebird",
		"fetch",
		"moment",
		"materialize",
		"nprogress",
		"numeral",
		//"text",
		//"css"
	],
	"options": {
		"inject": true,
		"minify": false,
		"rev": true
	}
};
var appBundle = {
	"includes": [
		"[**/*.js]",
		"**/*.html!text",
		"**/*.css!css"
	],
	"options": {
		"inject": true,
		"minify": false, // minification will not work with es6 modules because of uglify-js incompatibility
		"rev": true
	}
};
var prodBundle = {
	"dist/aurelia": aureliaBundle,
	"dist/app": appBundle
};
var devBundle = {
	"dist/aurelia": aureliaBundle
};

var prodConfig = {
	force: true,                    // Force overwrite bundle file if already exists. Default false
	baseURL: './wwwroot',                   // `baseURL of the application` 
	configPath: './wwwroot/config.js',      // `config.js` path. Must be within `baseURL` 
	bundles: prodBundle
};

var devConfig = {
	force: true,                    // Force overwrite bundle file if already exists. Default false
	baseURL: './wwwroot',                   // `baseURL of the application` 
	configPath: './wwwroot/config.js',      // `config.js` path. Must be within `baseURL` 
	bundles: devBundle
};

gulp.task('del', function () {
	return del("wwwroot/dist/*.js");
});

gulp.task('unbundle', ["del"], function () {
	return bundler.unbundle(prodConfig);
});

gulp.task('prodBundle', ['unbundle'], function () {   // Running `unbundle` before bundling is a good practice.
	return bundler.bundle(prodConfig);
});

gulp.task('devBundle', ['unbundle'], function () {   // Running `unbundle` before bundling is a good practice.
	return bundler.bundle(devConfig);
});
```

**Comment by MaximBalaganskiy** [comment]
Ideally, this global execution chunk has to be removed. I guess it's not going to happen because it's just been added :)

**Comment by MaximBalaganskiy** [comment]
Minification is off in the code above, so it's working for me. Once it's on for `aurelia` the issue is back

**Comment by Thanood** [comment]
Thanks! :+1: 
What do you think about the `main.js` I've posted above?
Or is your last comment about that and I didn't get it?

**Comment by MaximBalaganskiy** [comment]
No, it was about mine.... Your idea seems ok. I'll try it tomorrow or on Sunday. Already 8pm here :)

**Comment by Thanood** [comment]
Alright, thanks for trying and feedback. :+1:

**Comment by droda59** [comment]
I have the problem too because I override the sass variables and recompile the materialize css, and use it my styles.css, but then the materialize.js file also uselessly loads the original materialize.css file.
Still not sure how I should fix this.

**Comment by Thanood** [comment]
@droda59 I never played around with the sass files, yet. 😃 

As far as I know, materialize itself doesn't load its css, does it?
Did you try to `<require>` your changed css explicitly?

Also I'm not sure right now which one of the materialize output directories jspm loads (bin or dist). `require` loads relative to that directory so maybe it's the wrong one.

Now if materialize actually loads its css and I just didn't notice that for the past few months, could you try to enforce load order like [a few comments above](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/263#issuecomment-245863046)?

**Comment by MaximBalaganskiy** [comment]
Systemjs loads CSS, because there's a reference to it in js file. Not sure
about other loaders

**Comment by Thanood** [comment]
Then maybe anoverride in SystemJS config would work?

**Comment by droda59** [comment]
Oh so this must be an issue with the SystemJS load... How could I write such an override?

**Comment by MaximBalaganskiy** [comment]
@Thanood your solution works so far. All I had to do is add this line before setting the app root
```
	await new Promise(resolve => $(document).ready(() => resolve()));
```

**Comment by Thanood** [comment]
@droda59 
> Oh so this must be an issue with the SystemJS load... How could I write such an override?

I'm not sure.. Not an expert on JSPM overrides. :smiley:

I took a shot at http://jarreddebeer.github.io/jspm-package-override-generator/public/
And out came the following:

```javascript
{
  "map": {
    "materialize.css": "dist/css/materialize.css"
  }
}
```

This snippet is usually used in `package.json` like [in our sample config](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/package.json#L36-L40).

But I'm not sure if that would work. Will have to take a closer look at JSPM configuration when I have some more time..

**Comment by Thanood** [comment]
@MaximBalaganskiy Wonderful.. I guess this should be documented in the install instructions.

**Comment by droda59** [comment]
@Thanood doesn't seem to do anything. If you find anything, let me know! (I'll do the same)

**Comment by MaximBalaganskiy** [comment]
@droda59 this is what worked for me
```
{
	packages: {
		"materialize": {
			main: "js/materialize.js",
			map: {
				'../css/materialize.css': 'someOther.css'
			}
		}
	},
}
```

**Comment by droda59** [comment]
@MaximBalaganskiy yes it worked! Thanks a lot guys!

**Comment by Thanood** [comment]
I'd like to check if this goes away when I change the bridge's JSPM config from referencing `amd` to `SystemJS` and then check if this happens with requirejs (it should)..

This is to decide if an alternative `main.js` should be documented only in Aurelia-CLI installation instructions or additionally in JSPM instructions.

**Comment by Thanood** [comment]
Regarding Aurelia-CLI:

Can anyone who encountered this problem add "materialize-css" to the dependencies in this bridge config in `aurelia-json`? It just doesn't seem to hit me whatever I do. :confused: 

Like this:

```json
"name": "aurelia-materialize-bridge",
"path": "../node_modules/aurelia-materialize-bridge/dist/amd",
"main": "index",
"deps": [
  "jquery",
  "materialize-css"
],
"resources": [ ... ]
```

**Comment by Thanood** [comment]
See #286
