### ISSUE TITLE
Tooltip text doesn't load when from i18n

### ISSUE THREAD

**Issue by droda59** [aurelia-ui-toolkits/aurelia-materialize-bridge#266]
I'm trying to create a tooltip with localized text using aurelia-i18n, and it seems the resource doesn't get properly loaded. 

`<a class="btn-floating" md-tooltip="text: ${ 'deleteButton' | t };"><i class="material-icons">delete</i></a>`

**Comment by Thanood** [comment]
Ah yes, I've seen this interpolation with valueConverters not update, too..
`${ 'deleteButton' | t }`

I'm still not sure if this is a bug or intended (https://github.com/aurelia/templating/issues/438#issuecomment-236657358).
Can you try to add a signaler just to see if it works in principle?

**Comment by Thanood** [comment]
I think this is solved. 😃

**Comment by ApRoland** [comment]
I have the same problem now.. use release 0.24.0

<a md-button="floating: true; large: true;" md-tooltip="position: left; text: ${'button.edit'| t};"
       md-waves="color: light; circle: true;">

Please advise where I am wrong

**Comment by Thanood** [comment]
I need to check this when I get home, it worked before and I don't remember the details.
Some new samples with i18n support are in the works by @mar9000

**Comment by Thanood** [comment]
Hmm, this doesn't work, either:

```js
<div md-tooltip="position: ${'left'}; text: todo.add;">
```

I wonder if this has anything to do with i18n at all.
Of course, in that case my statement that it was solved was wrong.

**Comment by MaximBalaganskiy** [comment]
Please check on v1 and reopen if persists
