### ISSUE TITLE
How do I add a custom attribute to the select element? 

### ISSUE THREAD

**Issue by droda59** [aurelia-ui-toolkits/aurelia-materialize-bridge#267]
I have a custom attribute that I created to change the width of an element based on its value. How can I use this attribute on the md-select element? 

`<select md-select value.two-way="value" autowidth>`

Doesn't seem to work. In the resulting html, I would want it on the input element.

**Comment by Thanood** [comment]
Interesting question.. 😃 

How would this work with "vanilla" Materialize, though? The input field is created by jQuery on initialization of the `material_select`. So you wouldn't have direct control of the input element at that time, right?

You would somehow have to "wait" for `attached()` and `material_select` to finish so the input is created.. We could f.i. fire an event in `md-select` or provide a promise which is resolved when materialize is ready. You should have access to the view-model of `md-select` in `autowidth`.

But that's very specific to `md-select` - for example this is not needed on a plain input element.

**Comment by droda59** [comment]
Exactly, it would work only on the md-select element. But I guess this could work!

**Comment by Ullfis** [comment]
Another approach could be to make an option to your custom attribute and then bind the value to it:
 
```html
<div autowidth="calculate-width.bind: value">
  <select md-select value.two-way="value">
</div>
```

**Comment by droda59** [comment]
@Ullfis wow, didn't thought about that. 
What would it look like in the attribute code?

**Comment by Ullfis** [comment]
Take a look at this

```javascript
import { bindable, customAttribute } from 'aurelia-templating';
import { inject} from 'aurelia-dependency-injection';
import { getLogger } from 'aurelia-logging';

@inject(Element)
@customAttribute('auto-width')
export class AutoWidthInput {
  @bindable() calculateWidth = '';

  log = getLogger('auto-width');

  constructor(private element) {}

  calculateWidthChanged(newValue) {
    let width = (((newValue || '').length + 1) * 9) + "px";
    this.element.style.width = width;
    this.log.debug('calculateWidthChanged width:' + width);
  }
}
```

```html
        <div auto-width="calculate-width.bind: inputValue;">
          <select md-select value.two-way="inputValue" autowidth>
            <option value="" disabled selected>select an item</option>
            <option value="item 1">item 1</option>
            <option value="item longer">item longer</option>
            <option value="item even longer">item even longer</option>
          </select>
        </div>
```

**Comment by droda59** [comment]
@Ullfis it works! Thanks a lot!
Though now if I use it on regular inputs I have to specify the calculate-width binding. I can't find a way to set my @bindable property in the bind() function when I have an input element.

**Comment by Thanood** [comment]
Let's use gists.. :smiley: 
https://gist.run/?id=7bf9039494d482a931845b4c9b26215e

**Comment by droda59** [comment]
The best scenario would be to use it like the last input in this: https://gist.run/?id=07847098fcab498862003696adb5d9c4
For now, I have done it like the first input, by specifying the calculate-width binding in my html, and it works fine. I just find that it makes for a lot of repetition, so ideally I could do it like the last input (and the code that goes with it in the js). 
Do you think there is a way to achieve that? If not, it's not a big problem to specify the calculate-width in the html.

**Comment by Thanood** [comment]
I've updated my gist and hope I understood your intention. :smiley: 
I've called the variable `disconnected` to show that no JS is used there.

If I got you right, a problem with this is that the initial value is `undefined` and therefore the input is as short as it can get. I don't know of any way to set a default or initial value when using variables only in templates.

Just to be clear.. I understood that this would be your ideal:

```html
    <div auto-width="calculate-width.bind: disconnected">
      <input value.bind="disconnected" />
    </div>
```

**Comment by Ullfis** [comment]
Reading [Aurelia HUB](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-attributes/4)..

You can save some typing by replace the `calculateWidthChanged(newValue) {` with `valueChanged(newValue) {` and use the attribute like this:

```html
<div auto-width.bind="inputValue">
```

**Comment by Ullfis** [comment]
https://gist.run/?id=7611b6ad8fc700af6492951928e5424e

**Comment by Thanood** [comment]
I always forget about this. Thanks, @Ullfis 😃

**Comment by droda59** [comment]
Well it works, but I just find it repetitive to specify the autowidth binding for the input, when you know it's gonna be the value. 
The ideal would be like
`<md-input md-label="put some text here" md-value.bind="inputValue2" auto-width></md-input>`
(You know the autowidth property will be the value)

But then you would have to create the binding in the viewmodel. Just not sure how that can be made.

**Comment by Thanood** [comment]
That would be very special to *this* use-case.

You should be able to access the view model of the element `auto-width` is assigned to.
Add a propertyObserver which observes the value property of said element. This observer calls `valueChanged` and you can use @Ullfis' solution. :smiley: 

https://gist.run/?id=8751ad98b3826310824a4eb118855535

**Comment by droda59** [comment]
Oh nice I'll try this out!
