### ISSUE TITLE
Carousel repeat.for not working

### ISSUE THREAD

**Issue by ignusk84** [aurelia-ui-toolkits/aurelia-materialize-bridge#268]
I am trying to use the repeat.for to render images inside of the carousel component, but it blows up.

**Comment by ignusk84** [comment]
It works for me when the data is already there, try where you set your data asynchronously.

https://gist.run/?id=04c392533457e93f34c2a0f5813521ac

**Comment by Thanood** [comment]
Thanks for the example.

I understand that the initialization should be deferred in that case. Maybe carousel can be re-initialized although I'm not sure if that makes sense in practice. I'll try ot.
