### ISSUE TITLE
Transitions have Uncaught TypeError

### ISSUE THREAD

**Issue by SnipersCode** [aurelia-ui-toolkits/aurelia-materialize-bridge#269]
Examples on the demo page don't work.
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/transitions

I can also not get it to work on my own aurelia app.

Demo app error:
* Uncaught TypeError: n.find is not a function [stagger-list]
* Uncaught TypeError: n.css is not a function [md-fadein-image]

Using: Chrome 53.0.2785.101 m (64-bit)

**Comment by Thanood** [comment]
Thanks for reporting! :+1: 

So, these errors seem to originate from the materialize bundle. Maybe the usage has changed in the previous update. I will have a look at that.

```
materialize-3ad7a42cc5.js:7 - Uncaught TypeError: n.find is not a function
```

```
materialize-3ad7a42cc5.js:7 - Uncaught TypeError: n.css is not a function
```

**Comment by Ullfis** [comment]
Convert ref to jQuery element and it should work

https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/transitions/staggered-list.js#L26

```javascript
  staggerList() {
    Materialize.showStaggeredList($(this.ref));
  }
```

**Comment by Thanood** [comment]
You're right. And they really changed it..
https://github.com/Dogfalo/materialize/commit/e3b8c7f8828803b068990dfe1195620a64f6e2ed#diff-8b4b1972283fb426455686ff01c44ce0

**Comment by Thanood** [comment]
Still needs to be pulished. I'll try tomorrow.
