### ISSUE TITLE
Select Refresh Issue

### ISSUE THREAD

**Issue by AmareshKulkarni** [aurelia-ui-toolkits/aurelia-materialize-bridge#270]
I am trying to gather address as part of a form. I am using two selects, one for country and one for State. country select has a observer on it and whenever the country changes, I am filtering the list of States which is used to populate the State select.

For both selects, I want to start with "select an option" as the default value. With these defaults, when I change the country for the first time, the state dropdown is correctly getting populated with appropriate States for the selected country. But if I change the country again without making any State selection, the state list displayed doesn't change. The binding changes though; what I mean is, when I try to select the State, the bounded value in the model represents States for the new country. The display value is not getting updated though.   I tried the this.select.refresh method only to run into errors indicating refresh() is not defined on unidentified.

Here is my HTML fragment and corresponding model. Any help is greatly appreciated.

` <form role="form">
        <div class="col s12 m6 push-m3 l4 push-l4">
          <div class="row">
           <div class="input-field col s12">
            <select md-select value.two-way="residingAddress.country">
              <option value="" disabled>Select Country of residence..</option>
              <option repeat.for="country of countryList" value.bind="country.code">${country.name}</option>
            </select>
            <label class="active" for="country">Country</label>
          </div>
        </div>
        <div class="row" if.bind="filteredStateList!=null && filteredStateList.length>0">
          <div class="input-field col s12">
            <select md-select md-select.ref="select" value.two-way="residingAddress.state" >
              <option value="" disabled>Select State of residence</option>
              <option repeat.for="state of filteredStateList"  value.bind="state.short">${state.name}</option>
            </select>
            <label class="active" for="state">State</label>
          </div>
        </div>`

`export class ProfileSetupAddress extends BaseAction {
    validationError = '';
    residencyStatusList = ResidencyStatusList;
    countryList = CountryList;
    stateList = Provinces;

    filteredStateList = null;
    constructor(router, multiObserver, auth, residingAddress, permanentAddress) {

        super(router);

        this.auth = auth;
        this.residingAddress = residingAddress;
        this.permanentAddress = permanentAddress;
        this.multiObserver = multiObserver;
        this.filterStatesForSelectedCountry();
        var subscription = this.multiObserver
            .observe([
                [this.residingAddress, 'country']
            ], () => this.filterStatesForSelectedCountry());
        logger.debug('1. Constructor called');
        logger.debug('Current model : ' + JSON.stringify(this.residingAddress));
    }

    filterStatesForSelectedCountry() {
        let country = this.residingAddress.country;
        if (country != undefined && country != null)
            this.filteredStateList = this.stateList.filter(function(stateEntry) { return stateEntry.country === country });
        logger.debug('filterStatesForSelectedCountry called ' + country + ' ;' + JSON.stringify(this.filteredStateList));
        //this.select.refresh();
    }`

**Comment by Thanood** [comment]
@AmareshKulkarni Please have a look at this gist: https://gist.run/?id=22b6c2c0187883ac7a2c96d9fc2be81e

When you call `this.filterStatesForSelectedCountry();` in the constructor, binding has not happened yet and thus `md-select.ref` is not yet defined. I've moved the call into `attached()` and it worked.

The same is true for `if.bind`. If its expression is `false` bindings are not evaluated, so `md-select.ref` is not defined. I've worked around this by using `show.bind` instead.

**Comment by AmareshKulkarni** [comment]
Thanks a ton! Really appreciate your prompt help.
