### ISSUE TITLE
Range with Input

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-materialize-bridge#271]
Hi,

I'm trying to allow the user to use a range control or an input to update the same underlying property. I'd like for the value to be formatted as currency (with commas) in the input itself. It seems like having the comma in the input messes up the range.  Am I going about this the wrong way?

```html
<div>
     <input type="text" value.bind="loanAmount" />
    <md-range md-value.bind="loanAmount" md-min="0" md-max="300000"></md-range>
  </div>
  <div>
    Value: ${loanAmount | numberFormat}
  </div>
```

```javascript
export class App {
  constructor() {
    this.loanAmount = 10000;   
  } 
}
export class NumberFormatValueConverter {
    toView(value, format) {
        if (!format) {
            format = '($0,0.00)';
        }

        return numeral(value).format(format);
    }
}
```

**Comment by jasonhjohnson** [comment]
I did this, which seems to work but may not be the best route:

```javascript
export class App {
  constructor() {
    this.loanAmount = 10000;
  }

  get loanAmountFormatted() {
    return numeral(this.loanAmount).format('($0,0)');
  }

  set loanAmountFormatted(value) {
    let unformatted = numeral().unformat(value);
    this.loanAmount = unformatted;
  }
}

export class NumberFormatValueConverter {
    toView(value, format) {
        if (!format) {
            format = '($0,0)';
        }

        return numeral(value).format(format);
    }
}
```

**Comment by Thanood** [comment]
In [this example](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/range/minmax) the "trick" was to set the steps to a floating number.

But somehow the input dowsn't allow entering floats. Strange.. Maybe the bindings interfere.

Gist: https://gist.run/?id=8751ad98b3826310824a4eb118855535

**Comment by Thanood** [comment]
I guess this could be done by not directly binding the range and input elements. I'd try an observer for instance but in a way you already did this with your getter/setter. :smile:

I'll try that tomorrow. Need some sleep now.

**Comment by Thanood** [comment]
I've changed the gist to use a "disconnected" `md-range` and it works.. So I guess two-way binding was interfering.
https://gist.run/?id=8751ad98b3826310824a4eb118855535

Of course, that is without numeral or any number formatting but I think you got that covered. :smiley: 

Your approach seems similar, indeed. I'm curious, does this introduce dirty checking on the getter?

**Comment by jasonhjohnson** [comment]
@Thanood Thanks for the gist. I'm not sure on the dirty checking. My method does seem to work. I'm not sure if your method is a smarter approach than mine though?

**Comment by Thanood** [comment]
If your version introduces dirty checking then it's not that "smart". I hate to say such things because I do a lot of "not so smart" things myself and I don't want to judge. But you asked. :smiley: 

It's far from being bad, though. You can check for dirty checking by logging anything in the getter. If it's printed periodically without you doing anything => dirty checking. :smile: 
In that case `@computedFrom()` may help.

**Comment by jasonhjohnson** [comment]
@Thanood Gotcha. Well I went ahead and implemented it your way:

```html
<input id="loan_amount" type="text" class="validate" value.bind="loanAmount | numberFormat">
<md-range md-value.bind="loanAmountRangeValue" md-min="10000" md-max="300000" md-step="10000.0" change.delegate="onRangeChange($event)"></md-range>
```

```javascript
import {observable} from 'aurelia-framework';
import numeral from 'numeral';

export class App {
  @observable() loanAmount;
  loanAmountRangeValue;

  constructor() {
    this.loanAmount = 10000.0;
    this.loanAmountRangeValue = this.loanAmount;
  } 
  loanAmountChanged(newValue) {
    let unformatted = numeral().unformat(newValue);
    this.loanAmountRangeValue = unformatted;
  }
  
  onRangeChange(e) {
    this.loanAmount = this.loanAmountRangeValue;
  }  
}

export class NumberFormatValueConverter {
    toView(value, format) {
        if (!format) {
            format = '(0,0)';
        }

        return numeral(value).format(format);
    }
}
```

**Comment by Thanood** [comment]
I think this would make a great example.
