### ISSUE TITLE
Feature request: enable different preloader sizes from materialize

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia-ui-toolkits/aurelia-materialize-bridge#274]
Hi,

it would be nice if md-progress had an option to set the size of the preloader. Right now it defaults to big and can't be changed.

Thanks
Joscha

**Comment by Thanood** [comment]
Good one. :+1: 
What do you think about setting the size manually as another option (in addition to pre-configured sizes)?

**Comment by JoschaMetze** [comment]
An option would be cool :+1:
