### ISSUE TITLE
Scrollfire has Uncaught TypeError

### ISSUE THREAD

**Issue by SnipersCode** [aurelia-ui-toolkits/aurelia-materialize-bridge#275]
Example on the demo page doesn't work:
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/scrollfire

Demo app has same error as #269 . Might be related.

Using Chrome 53.0.2785.101 m (64-bit)

**Comment by Thanood** [comment]
I should have thought of that, thanks. 👍
