### ISSUE TITLE
Cannot find bundles.dependencies

### ISSUE THREAD

**Issue by explorer2309** [aurelia-ui-toolkits/aurelia-materialize-bridge#278]
I am trying to follow the installation instructions at http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation

I am stuck at the 2nd step of Configure Aurelia CLI - "add this to bundles.dependencies" 

However, I am unable to find bundles.dependencies

**Comment by Ullfis** [comment]
You find it in aurelia_project/aurelia.json. Example [here](https://github.com/Ullfis/aurelia-cli-materialize-bridge/blob/master/aurelia_project/aurelia.json#L93)

**Comment by Thanood** [comment]
This is now clarified in installation instructions. At least I hope so.
@explorer2309 do you think mentioning `aurelia.json` explicitly is enough?

Looks like this: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/6095557c123b05ec347aa8736344dbfd4430e212/sample/src/installation/installation-requirejs.md

**Comment by explorer2309** [comment]
I am not a documentation expert but I think that something like this will be bit more explicit:

> 
> add this in your aurelia_project/aurelia.json to path : 
> 
> `build. bundles[with name="vendor-bundle.js].dependencies`
>

**Comment by Thanood** [comment]
Ah alright, `vendor-bundle` was missing.
Thanks. 👍

**Comment by Thanood** [comment]
Although that should be possible in any bundle, when I got this right..
