### ISSUE TITLE
[Question] Dropdown module not found

### ISSUE THREAD

**Issue by dev0x10** [aurelia-ui-toolkits/aurelia-materialize-bridge#280]
I'm moving from JSPM to Webpack
And I found this 
```
Unhandled rejection TypeError: $(...).dropdown is not a function
```
It's not bundle prod (I read about it), only dev build.
I use it on nav-bar.html which has no js

Any idea what is wrong?

**Comment by Thanood** [comment]
Is anything else from Materialize defined? Like the `Materialize` global or for example select (`material_select`)?
This seems so familiar but I don't remember it right now.

**Comment by dev0x10** [comment]
Debugging and found this
```
// The jQuery object is actually just the init constructor 'enhanced'
		// Need init if jQuery is called (just allow error to be thrown if not included)
```

**Comment by Thanood** [comment]
Are you using the webpack skeleton for that? If so, which version?
Then I can try it..

**Comment by dev0x10** [comment]
The latest one, I see the skeleton updated. I'm using that one with same problem. Could be something wrong in my code though

**Comment by Thanood** [comment]
Does this skeleton work and if so, would you compare it to yours?
https://github.com/Ullfis/materialize-aurelia-webpack-skeleton

If not, would you mind uploading your app or a reproduction of the issue?
That way I can take a direct look.

**Comment by dev0x10** [comment]
I just cloned the repo and it does work 😃  
But it is a typescript. I'm using ES6

Sorry the project

**Comment by dev0x10** [comment]
The skeleton you provided does work. But it is TS skeleton, I'm using ES6
I cannot upload my project because it only can runs on my local env.

Here is the new skeleton I use to replicate the problem:
https://github.com/dev0x10/try-aurelia-webpack-materialize.git

**Comment by dev0x10** [comment]
could be related
https://github.com/krescruz/angular-materialize/issues/96

**Comment by Thanood** [comment]
From there:
> I've got the same issue, after re-ordered js files works like a charm!

This might as well be the module order issue which is mentioned here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/168#issuecomment-247057755

It works but the buttons with waves stay dimmed. That's because (somehow) Materialize Waves are initialized twice. And my guess is that it's because of module load order. Now if Materialize is NOT loaded when Aurelia takes control (and thus the dropdown is initialized), that would probably explain your problem.

I'll have a look at your repo..

**Comment by Thanood** [comment]
Still building but this might be a problem:
https://github.com/dev0x10/try-aurelia-webpack-materialize/blob/master/package.json#L70

Try to downgrade jQuery to 2.x - Materialize doesn't play well with jQuery 3 atm.

**Comment by dev0x10** [comment]
..... I should've realize it before
Now it works. Replacing the jQuery version is not enough, I had to remove  npm_modules folder and re-install everything

I really appreciate your time for replying this post! 
Danke 😃

**Comment by Thanood** [comment]
Kein Problem, gerne. 😃 

Glad that it's not something complicated like module load order.. Still trying to solve that.
