### ISSUE TITLE
XMLHttpRequest cannot load on Google Chrome

### ISSUE THREAD

**Issue by LeoNero** [aurelia-ui-toolkits/aurelia-materialize-bridge#283]
Hi! I'm trying to run my aurelia app without using a web server. It runs on Firefox, but not on Google Chrome! I've got the following error:

```
vendor-bundle.js:4102 XMLHttpRequest cannot load file:///home/leonardo/master-the-toefl/…ent/node_modules/aurelia-materialize-bridge/dist/amd/colors/md-colors.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

vendor-bundle.js:4102 XMLHttpRequest cannot load file:///home/leonardo/master-the-toefl/…-client/node_modules/aurelia-materialize-bridge/dist/amd/well/md-well.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

How can I solve this problem?

**Comment by Thanood** [comment]
@LeoNero 
This is not a problem with this bridge or with Aurelia, it's actually a feature in Firefox. :smiley: 

Anyway, I'm not sure if I can describe this properly. I think the Chrome help has a good explanation.
When serving from the file system, Chrome doesn't allow requests of other files on that file system. If you use a local web server (this can be for example BrowserSync), you won't get these errors.

I think it is well described here:
http://stackoverflow.com/questions/8449716/cross-origin-requests-are-only-supported-for-http-but-its-not-cross-domain

**Comment by LeoNero** [comment]
@Thanood Yeah, the solution is to use a local web server... Thanks! :D
