### ISSUE TITLE
Handling fonts with the CLI

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-ui-toolkits/aurelia-materialize-bridge#284]
Hi,

I'm using the CLI and all the installation instructions work perfectly now (thanks). The one issue I'm running into is the roboto fonts not loading: 

```
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Regular.woff2 
:9000/materialize-css/fonts/roboto/Roboto-Regular.woff:1 
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Regular.woff 
:9000/materialize-css/fonts/roboto/Roboto-Regular.ttf:1 
GET http://localhost:9000/materialize-css/fonts/roboto/Roboto-Regular.ttf 
```

Any recommended approaches for handling this? 

Thanks,
Jason

**Comment by Thanood** [comment]
Hi @jasonhjohnson,

that's definitely a good question. Last time I checked (several au versions ago) you couldn't load fonts easily with Aurelia CLI. This may have changed and I need to check again. They couldn't be bundled and I think that's what causing this issue.
The workaround is to copy these fonts (via a buld task) into the directory where they are expected.
https://github.com/aurelia/cli/issues/248

When I take a look at the file system, the referenced path seems to be the correct one. So I guess this unresolved Aurelia CLI issue is related.

**Comment by Thanood** [comment]
Checked again. As of now, there doesn't seem to be a "real" solution to this.
I guess if there was a requirejs font loader you could ass fonts to the resources array. If you do that now, au throws errors because it wants to bundle `Roboto-Regular.js`..

**Comment by jasonhjohnson** [comment]
Yeah. Would there be away to bypass these errors?

**Comment by Thanood** [comment]
Well, I can't think of any "pretty" solution.. Remove all `@font-face` from `materialize.css` (build step with regular expressions?) or create a directory `materialize-css/fonts/roboto/` where a build task copies the Materialize fonts so the network requests from `materialize.css` succeed.

**Comment by kristianmandrup** [comment]
I resolved it for font awesome using custom build task, as described [here](http://stackoverflow.com/questions/39271458/how-can-i-add-font-awesome-to-my-aurelia-project-using-npm). I think same fix can be done for Roboto fonts.

**Comment by kristianmandrup** [comment]
I tried adding the following custom build tasks:

```bash
import * as gulp from 'gulp';
import merge from 'merge-stream';
import changedInPlace from 'gulp-changed-in-place';
import project from '../aurelia.json';

export default function prepareFontAwesome() {

  let source = 'node_modules\\font-awesome';

  let taskCss = gulp.src(`${source}\\css\\font-awesome.min.css`)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(gulp.dest(`${project.platform.output}\\css`));

  let taskFonts = gulp.src(`${source}\\fonts\\*`)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(gulp.dest(`${project.platform.output}\\fonts`));

  return merge(taskCss, taskFonts);
}
```

and

```js
import * as gulp from 'gulp';
import merge from 'merge-stream';
import changedInPlace from 'gulp-changed-in-place';
import project from '../aurelia.json';

export default function prepareMaterialize() {

  let source = 'node_modules\\materialize-css';

  let taskCss = gulp.src(`${source}\\dist\\css\\materialize.min.css`)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(gulp.dest(`${project.platform.output}\\css`));

  let taskFonts = gulp.src(`${source}\\fonts\\*`)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(gulp.dest(`${project.platform.output}\\fonts`));

  return merge(taskCss, taskFonts);
}
```

**Comment by jasonhjohnson** [comment]
Thanks everybody

**Comment by kristianmandrup** [comment]
Please see this [app skeleton](https://github.com/Ullfis/au-cli-skel)

**Comment by Thanood** [comment]
Finally added to the docs.
