### ISSUE TITLE
 Message: _aureliaMaterializeBridge.MaterializeFormValidationRenderer is not a constructor

### ISSUE THREAD

**Issue by AmareshKulkarni** [aurelia-ui-toolkits/aurelia-materialize-bridge#285]
I am using the aurelia-materialize-bridge in a web-pack skeleton project. All of it was working fine except for the validations. The aurelia validation itself is firing fine and capturing all errors. However the errors are not being rendered on the screen because I get the following error while adding the renderer

Message: _aureliaMaterializeBridge.MaterializeFormValidationRenderer is not a constructor

Any help is greatly appreciated.

Thank you.

**Comment by Thanood** [comment]
@AmareshKulkarni Last time I checked it just worked. Can you compare your setup to [this one](https://github.com/Ullfis/aurelia-materialize-skeleton-typescript-webpack/tree/aurelia-validatejs)?

**Comment by Ullfis** [comment]
@Thanood, I need to do some cleaning in old tests and will delete that project.

Here is a repository with [updated validation](https://github.com/Ullfis/materialize-aurelia-webpack-skeleton) :smile:

**Comment by Thanood** [comment]
Okay, thanks @Ullfis 😃 
I should really fork these repos..

**Comment by AmareshKulkarni** [comment]
@Ullfis & @Thanood - Thank you so much. I was running on an old version 0.13 and didn't realize it. Once I updated the version, everything is working fine now. In fact, the version update also addressed some other issues which I didn't care much earlier.
