### ISSUE TITLE
TypeError: Cannot redefine property: isSelected

### ISSUE THREAD

**Issue by kristianmandrup** [aurelia-ui-toolkits/aurelia-materialize-bridge#286]
I continually get this error on Chrome. Any ideas?

I'm using Aurelia CLI, following these [instructions](http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation)

```bash
DEBUG [aurelia] Loading plugin aurelia-materialize-bridge.
vendor-bundle.js:1399 Unhandled rejection TypeError: Cannot redefine property: isSelected
    at Function.Object.defineProperty (polydev/vendor/zone-microtask.js:281:12)
    at _applyDecoratedDescriptor (http://localhost:9000/scripts/vendor-bundle.js:34783:36)
```

On Firefox I am warned:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

And not all fonts are loaded...

**Comment by kristianmandrup** [comment]
Looks like this error is related to #284

**Comment by Thanood** [comment]
Interesting. I've only seen this with JSPM bundles..

Is this the repo where it happens, by any chance?
https://github.com/kristianmandrup/ai-material-app

**Comment by kristianmandrup** [comment]
Yes, now I'm getting `$` is not defined. So I need to export it for jquery. I've been trying to write a tool to automate all this configuration hell :P

**Comment by kristianmandrup** [comment]
Like this?

```js
          {
            "name": "jquery",
            "path": "../node_modules/jquery/dist",
            "main": "jquery.min",
            "exports": "$"
          },
```

**Comment by kristianmandrup** [comment]
But [here](https://github.com/aurelia/cli/issues/248#issuecomment-243483842) he uses prepend for jquery and exports from the ui lib bundle config?

```json
"prepend": ["node_modules/jquery/dist/jquery.js"],
"dependencies": [
      {
        "name":"lib/semantic",
        "path":"../semantic/dist/",
        "main":"semantic",
        "exports": "$",
        "resources":["semantic.css","themes/default/assets/fonts/icons.woff2"]
      }
]
```

"I use prepend as a workaround for issue #257"

**Comment by Thanood** [comment]
`ai run --watch`:
Is this correct? I do need to install `aurelia-installer` globally to use this, right?

Using `au run --watch` I don't get any errors.

```
$ node -v
v6.2.2

$ npm -v
3.10.5

$ au -v
0.17.0
```

(why does that CLI never update to 0.20.0 for me?)

**Comment by kristianmandrup** [comment]
Correct.

I currently only get the error in my Chrome developer console, that `$` is not defined.

**Comment by Thanood** [comment]
I don't but finally a setup where I can reproduce the "waves stay dimmed" problem.
It might be the same reason why you're getting this error. Will have to look it up in the issues.

**Comment by Thanood** [comment]
Interesting.. When I add `materialize-css` as a dependency of the bridge, I'm getting the same error.

**Comment by kristianmandrup** [comment]
I still get this font-awesome error when building:

```
Tracing font-awesome/css/font-awesome.min...
Tracing font-awesome...
error /Users/kristianmandrup/repos/aurelia-projs/ai/ai-client/ai-material-app/node_modules/font-awesome/.js
```

**Comment by kristianmandrup** [comment]
I'm looking forward to a solution to this config nightmare for Aurelia CLI!!

**Comment by Thanood** [comment]
Do you think the "redefine" and "$ is not defined" errors are directly related to missing fonts?
I'm currently looking only at the former two problems to find a setup which can be 100% reproduced.

> I'm looking forward to a solution to this config nightmare for Aurelia CLI!!

To be honest, Materialize has its role in this nightmare, too.

**Comment by Thanood** [comment]
* jQuery: no `exports`
* bridge: no `exports` and dependency only on jQuery

=>

```
Uncaught ReferenceError: $ is not defined
```

and later on

```
Unhandled rejection ReferenceError: Waves is not defined
```

**Comment by Thanood** [comment]
* bridge: added `materialize-css` to dependencies => no errors (apart from fonts=

**Comment by Thanood** [comment]
* bridge: removed `materialize-css` dependency
* jQuery: added `$` export

=> no errors but "dimmed" Waves

Does that make any sense? :smiley:

**Comment by Thanood** [comment]
Okay, when I add a console output to the generated `materialize.amd.js` I'm getting completely different errors which don't seem to have any connection to my change:

```
vendor-bundle.js:25001 Uncaught ReferenceError: $ is not defined(anonymous function) @ vendor-bundle.js:25001
materialize.amd.js:39 Uncaught ReferenceError: $ is not defined(anonymous function) @ materialize.amd.js:39
vendor-bundle.js:11211 Uncaught TypeError: Cannot read property '__useDefault' of undefined
```

This is just strange and seems totally random to me. :confused:

**Comment by kristianmandrup** [comment]
Wow! But I think you made some progress :) The investigation continues!

**Comment by kristianmandrup** [comment]
Do you have a fork you can post which demonstrates your changes? Thanks!

**Comment by Thanood** [comment]
Right! I'm glad that I could reproduce this after all.
I'll have to work a bit now bit I'll look this up again for sure. :wink: 

> Do you have a fork you can post which demonstrates your changes? Thanks!

No, but I only did what I described above. Also tried some `aurelia.loader` changes to influence module load order. I will upload the changes and post the repo here.

**Comment by kristianmandrup** [comment]
Great. Thanks!

**Comment by Thanood** [comment]
https://github.com/Thanood/ai-material-app

I think the changes in `main.ts` don't work at all.
What I really wonder is: in your original setup, how is `materialize-css` loaded at all? Didn't see any imports and the bridge itself should be independent.

**Comment by kristianmandrup** [comment]
I just tried to follow the [CLI install instructions](http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation) which I got from this [dev tutorial](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/app_developers_tutorial/setup.html)

If I go to the sources tab in Dev inspector, I see the css files loaded, and the google fonts, but no other fonts that I can see.

**Comment by kristianmandrup** [comment]
Merging your changes I now get:

- `TypeError: Cannot redefine property: isSelected` Chrome
- `Unhandled rejection TypeError: $(...).sideNav is not a function` Firefox

**Comment by Ullfis** [comment]
Update this:

```bash
npm i aurelia-animator-css aurelia-bootstrapper aurelia-fetch-client --save
npm i aurelia-testing aurelia-cli@0.20.0 --save-dev
```

**Comment by Thanood** [comment]
Works for me.. :+1: 
So, if this works for @kristianmandrup then we may have a first list of "aurelia requirements", right?

But it doesn't solve the "dimmed waves" problem so I guess there is still something wrong, maybe with load order. If that's the case, `$ is undefined` may appear again. Will keep an eye on it.

**Comment by Ullfis** [comment]
create 1 bundle for bridge to solve waves problem:

aurelia.json:

```json
{
  "name": "ai-material-app",
  "type": "project:application",
  "platform": {
    "id": "web",
    "displayName": "Web",
    "output": "scripts",
    "index": "index.html"
  },
  "transpiler": {
    "id": "typescript",
    "displayName": "TypeScript",
    "fileExtension": ".ts",
    "dtsSource": [
      "./typings/**/*.d.ts",
      "./custom_typings/**/*.d.ts"
    ],
    "source": "src/**/*.ts"
  },
  "markupProcessor": {
    "id": "none",
    "displayName": "None",
    "fileExtension": ".html",
    "source": "src/**/*.html"
  },
  "cssProcessor": {
    "id": "none",
    "displayName": "None",
    "fileExtension": ".css",
    "source": "src/**/*.css"
  },
  "editor": {
    "id": "vscode",
    "displayName": "Visual Studio Code"
  },
  "unitTestRunner": {
    "id": "karma",
    "displayName": "Karma",
    "source": "test/unit/**/*.ts"
  },
  "paths": {
    "root": "src",
    "resources": "src/resources",
    "elements": "src/resources/elements",
    "attributes": "src/resources/attributes",
    "valueConverters": "src/resources/value-converters",
    "bindingBehaviors": "src/resources/binding-behaviors"
  },
  "testFramework": {
    "id": "jasmine",
    "displayName": "Jasmine"
  },
  "build": {
    "targets": [
      {
        "id": "web",
        "displayName": "Web",
        "output": "scripts",
        "index": "index.html"
      }
    ],
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": false
        }
      ]
    },
    "options": {
      "minify": "stage & prod",
      "sourcemaps": "dev & stage",
      "rev": "stage & prod"
    },
    "bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[**/*.js]",
          "**/*.{css,html}"
        ]
      },
      {
        "name": "materialize-bundle.js",
        "dependencies": [
          "jquery",
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "deps": [
              "jquery"
            ]
          },
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "breadcrumbs/breadcrumbs.css",
              "breadcrumbs/breadcrumbs.html",
              "card/card.css",
              "card/card.html",
              "carousel/carousel-item.html",
              "carousel/carousel.css",
              "carousel/carousel.html",
              "checkbox/checkbox.html",
              "chip/chip.html",
              "collection/collection-header.css",
              "collection/collection-header.html",
              "collection/collection-item.css",
              "collection/collection-item.html",
              "collection/collection.html",
              "collection/md-collection-selector.css",
              "collection/md-collection-selector.html",
              "colors/md-colors.html",
              "dropdown/dropdown-element.html",
              "fab/fab.html",
              "file/file.html",
              "input/input.css",
              "input/input.html",
              "navbar/navbar.css",
              "navbar/navbar.html",
              "pagination/pagination.html",
              "progress/progress.html",
              "radio/radio.html",
              "range/range.html",
              "sidenav/sidenav.css",
              "sidenav/sidenav.html",
              "slider/slider.css",
              "switch/switch.css",
              "switch/switch.html",
              "well/md-well.html"
            ]
          }
        ]
      },       
      {
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "scripts/require.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-templating-binding",
          {
            "name": "text",
            "path": "../scripts/text"
          },
          {
            "name": "aurelia-templating-resources",
            "path": "../node_modules/aurelia-templating-resources/dist/amd",
            "main": "aurelia-templating-resources"
          },
          {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev"
          },
          {
            "name": "aurelia-validation",
            "path": "../node_modules/aurelia-validation/dist/amd",
            "main": "aurelia-validation"
          }
        ]
      }
    ]
  }
}

```

**Comment by kristianmandrup** [comment]
@Ullfis I get the exact same errors after installing those module dependencies

**Comment by kristianmandrup** [comment]
@Ullfis Do you have any working minimal skeleton app for materialize bridge with CLI? or could you quickly make one or tweak this one?

**Comment by kristianmandrup** [comment]
@Ullfis After using your proposed `aurelia.json` file:

`TypeError: Cannot read property '__useDefault' of undefined`

**Comment by Ullfis** [comment]
here is a repo: https://github.com/Ullfis/au-cli-skel

**Comment by kristianmandrup** [comment]
@Ullfis Awesome! Thanks :)

**Comment by kristianmandrup** [comment]
I still get the following errors:

```bash
$ au run --watch
...
Tracing materialize-css...
error /Users/kristianmandrup/repos/aurelia-projs/ai/ai-client/au-cli-skel/node_modules/materialize-css/dist/js/materialize.amd.js
```

In Chrome console:

```
DEBUG [aurelia] Loading plugin aurelia-materialize-bridge.
vendor-bundle.js:1399 Unhandled rejection TypeError: Cannot redefine property: isSelected
    at Function.Object.defineProperty (polydev/vendor/zone-microtask.js:281:12)
    at _applyDecoratedDescriptor (http://localhost:9000/scripts/materialize-bundle.js:12000:36)
  ...
```

In Firefox console

```
Unhandled rejection ReferenceError: Waves is not defined
    attached@http://localhost:9000/scripts/materialize-bundle.js:16210:7
    attached@http://localhost:9000/scripts/vendor-bundle.js:19934:9
```

It displays just fine in Firefox, and in Chrome is displays a big Aurelia header text, then goes in infinite loop with the spinner...

**Comment by Thanood** [comment]
@Ullfis 
Can you tell me what exactly does separating materialize bundle change? 

@kristianmandrup 
Did you run `./node_modules/.bin/r.js -o rbuild.js` on this repo? Forgot this myself and gut similar errors.

**Comment by Ullfis** [comment]
Could you check that your global aurelia-cli version is 0.20.0?

**Comment by Ullfis** [comment]
@Thanood, I cant. It just work this way.

**Comment by kristianmandrup** [comment]
Here my stats:

```
14:46 $ ./node_modules/.bin/r.js -o rbuild.js
Error: Error: ENOENT: no such file or directory, lstat '/Users/kristianmandrup/repos/aurelia-projs/ai/ai-client/au-cli-skel/rbuild.js'
    at Error (native)
```

global `aurelia-cli`

```
14:46 $ npm list aurelia-cli
au-cli-skel@0.1.0 /Users/kristianmandrup/repos/aurelia-projs/ai/ai-client/au-cli-skel
├── aurelia-cli@0.20.0 
└── UNMET PEER DEPENDENCY typescript@2.1.0-dev.20160928

npm ERR! peer dep missing: typescript@>=1.7.3, required by tslint@3.15.1
✘-1 ~/repos/aurelia-projs/ai/ai-client/au-cli-skel [master|✚ 3] 
14:46 $ npm i typescript -g
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
/usr/local/lib
└── typescript@2.0.3 

✔ ~/repos/aurelia-projs/ai/ai-client/au-cli-skel [master|✚ 3] 
14:47 $ npm list aurelia-cli
au-cli-skel@0.1.0 /Users/kristianmandrup/repos/aurelia-projs/ai/ai-client/au-cli-skel
├── aurelia-cli@0.20.0 
└── UNMET PEER DEPENDENCY typescript@2.1.0-dev.20160928

npm ERR! peer dep missing: typescript@>=1.7.3, required by tslint@3.15.1
✘-1 ~/repos/aurelia-projs/ai/ai-client/au-cli-skel [master|✚ 3] 
14:47 $ tsc -v
Version 2.0.3
```

**Comment by Ullfis** [comment]
@kristianmandrup sry.. copied som files from another project. run one of these commands: https://github.com/Ullfis/au-cli-skel/blob/master/package.json#L11

**Comment by Ullfis** [comment]
.. I use latest typescript build. `UNMET PEER DEPENDENCY` is present here 2 but compile and run work `at my computer`.

You can install other versions of typescript if you want: `npm i typescript@2.0.2 --save-dev`

**Comment by Thanood** [comment]
This is getting slightly confusing.. :smiley: 
I've not cloned @Ullfis repo but applied the `aurelia.json` changes. So my `rbuild.js` was still in place.

Okay so, that works and Materialize somehow does **not** initialize itself. Which - with what I currently know - doesn't make any sense at all. That's what happens when the materialize dependencies are separated.
Directly loading `materialize-css` with `aurelia.loader` doesn't work anymore in that case (`_useDefault` error). So if you have that uncommented, comment it out again.

**Comment by kristianmandrup** [comment]
Works perfectly in Firefox now. In Chrome, as always I get strange errors with Aurelia...

```
DEBUG [aurelia] Loading plugin aurelia-materialize-bridge.
vendor-bundle.js:1399 Unhandled rejection TypeError: Cannot redefine property: isSelected
    at Function.Object.defineProperty (polydev/vendor/zone-microtask.js:281:12)
    at _applyDecoratedDescriptor (http://localhost:9000/scripts/materialize-bundle.js:19618:36)
```

Same error, when I update the typescript dev dep to 2.0.2 and rebuild/restart.

**Comment by Thanood** [comment]
`polydev/vendor/zone-microtask.js` - what's that?

**Comment by kristianmandrup** [comment]
Something which is normally Angular related, so I guess it's from the E2E tester karma? But why is that in the dev build?

https://github.com/AngularClass/angular2-webpack-starter/issues/437

Can it be ignored?

**Comment by Ullfis** [comment]
Do you get same error if you close chrome dev tools?

**Comment by kristianmandrup** [comment]
Yup, the error is caused by incompatibility with a  Polymer development plugin.

https://github.com/Juicy/juicy-tile-editor/issues/147
https://github.com/PolymerLabs/polydev/issues/21

Thanks! I will just remove or disable it then :)

**Comment by Thanood** [comment]
Great! :+1: 

Reopening with "needs documentation" label. I'd like a summary for myself and put separated bundles in the docs.

**Comment by kristianmandrup** [comment]
@Thanood perfect!!! Let's get this recipe/setup documented.

**Comment by kristianmandrup** [comment]
BTW, shouldn't the `/scripts` folder be in `.gitignore` ?

**Comment by Thanood** [comment]
Yes and no..
Yes because it'd be a better structure.
No because `requirejs` and its text loader is in there.. If you gitignored that, people forking the repo would certainly miss these files.

**Comment by Thanood** [comment]
Btw. the npm version of `aurelia-installer` seems to be out of date. There is a file `aurelia-installer/lib/commands/bundle/unbundle.js` which is not present in master. Line 15 of that file loads `../vendor` which is not present, leading to `Error: Cannot find module '../vendor'`..

Shall I create an issue?
I didn't because I think you already know and fixed that, looking at your master branch.

**Comment by Ullfis** [comment]
Added a copy script to au-cli-skel. Copy require.js and text.js to tools folder. Then those will be copied to script folder when running build.

https://github.com/Ullfis/au-cli-skel/blob/master/aurelia_project/tasks/copy-scripts.ts

**Comment by kristianmandrup** [comment]
@Thanood Yes, I need to publish a fix on npm. Are you interested in this project? If so, you are most welcome to give a hand/brain.

**Comment by kristianmandrup** [comment]
Great! Thanks for all @Ullfis :)

**Comment by Thanood** [comment]
@kristianmandrup First I'm interested in *using* aurelia-installer.. :smiley: 
Sure I'm interested, it's a great concept and I liked the idea since it appeared on Monterey Gitter channel. Still interested in doing an integration, maybe. Anyway, I'll need to catch up on a few things before.

**Comment by kristianmandrup** [comment]
@Thanood Then contact me directly on @kmandrup on gmail. I have the same objective, integration with Monterey most likely. See [ai-component](https://github.com/kristianmandrup/ai-component) and siblings.

**Comment by javiercbk** [comment]
I'm having the same issue.

When sideNav is trying to initialize I get `TypeError: $dragTarget.hammer is not a function`

```js
$dragTarget.hammer({
            prevent_default: false
          }).bind('pan', function(e) {...});
```

Aurelia cli version:

```sh
$> au -v
$> 0.22.0
```

I'm using materialize-css 0.97.8 because 0.97.7 was throwing the same error.

It seems that sideNav's Jquery does not have hammerjs plugin.

This is my `aurelia.json`

```json
{
	"name": "project",
	"type": "project:application",
	"platform": {
		"id": "web",
		"displayName": "Web",
		"output": "scripts"
	},
	"transpiler": {
		"id": "babel",
		"displayName": "Babel",
		"fileExtension": ".js",
		"options": {
			"plugins": [
				"transform-es2015-modules-amd"
			]
		},
		"source": "src/**/*.js"
	},
	"markupProcessor": {
		"id": "none",
		"displayName": "None",
		"fileExtension": ".html",
		"source": "src/**/*.html"
	},
	"cssProcessor": {
		"id": "none",
		"displayName": "None",
		"fileExtension": ".css",
		"source": "src/**/*.css"
	},
	"editor": {
		"id": "atom",
		"displayName": "Atom"
	},
	"unitTestRunner": {
		"id": "karma",
		"displayName": "Karma",
		"source": "test/unit/**/*.js"
	},
	"paths": {
		"root": "src",
		"resources": "src/resources",
		"elements": "src/resources/elements",
		"attributes": "src/resources/attributes",
		"valueConverters": "src/resources/value-converters",
		"bindingBehaviors": "src/resources/binding-behaviors"
	},
	"testFramework": {
		"id": "jasmine",
		"displayName": "Jasmine"
	},
	"build": {
		"targets": [{
			"id": "web",
			"displayName": "Web",
			"output": "scripts"
		}],
		"loader": {
			"type": "require",
			"configTarget": "vendor-bundle.js",
			"includeBundleMetadataInConfig": "auto",
			"plugins": [{
				"name": "text",
				"extensions": [
					".html",
					".css"
				],
				"stub": false
			}]
		},
		"options": {
			"minify": "stage & prod",
			"sourcemaps": "dev & stage"
		},
		"bundles": [{
			"name": "materialize-bundle.js",
			"dependencies": [
				"jquery", {
					"name": "materialize-css",
					"path": "../node_modules/materialize-css/dist",
					"main": "js/materialize.amd",
					"deps": [
						"jquery"
					],
					"resources": [
						"css/materialize.css"
					],
					"exports": "Materialize"
				}, {
					"name": "aurelia-materialize-bridge",
					"path": "../node_modules/aurelia-materialize-bridge/dist/amd",
					"main": "index",
					"deps": [
						"jquery"
					],
					"resources": [
						"**/*.{css,html}",
						"index.js"
					]
				}
			]
		}, {
			"name": "app-bundle.js",
			"source": [
				"[**/*.js]",
				"**/*.{css,html}"
			]
		}, {
			"name": "vendor-bundle.js",
			"prepend": [
				"node_modules/bluebird/js/browser/bluebird.core.js",
				"node_modules/requirejs/require.js"
			],
			"dependencies": [
				"aurelia-binding",
				"aurelia-bootstrapper",
				"aurelia-dependency-injection",
				"aurelia-event-aggregator",
				"aurelia-framework",
				"aurelia-fetch-client",
				"aurelia-history",
				"aurelia-history-browser",
				"aurelia-loader",
				"aurelia-loader-default",
				"aurelia-logging",
				"aurelia-logging-console",
				"aurelia-metadata",
				"aurelia-pal",
				"aurelia-pal-browser",
				"aurelia-path",
				"aurelia-polyfills",
				"aurelia-route-recognizer",
				"aurelia-router",
				"aurelia-task-queue",
				"aurelia-templating",
				"aurelia-templating-binding",
				"text", {
					"name": "aurelia-templating-resources",
					"path": "../node_modules/aurelia-templating-resources/dist/amd",
					"main": "aurelia-templating-resources"
				}, {
					"name": "aurelia-templating-router",
					"path": "../node_modules/aurelia-templating-router/dist/amd",
					"main": "aurelia-templating-router"
				}, {
					"name": "aurelia-testing",
					"path": "../node_modules/aurelia-testing/dist/amd",
					"main": "aurelia-testing",
					"env": "dev"
				}, {
					"name": "i18next",
					"path": "../node_modules/i18next/dist/umd",
					"main": "i18next"
				}, {
					"name": "aurelia-i18n",
					"path": "../node_modules/aurelia-i18n/dist/amd",
					"main": "aurelia-i18n"
				}, {
					"name": "i18next-xhr-backend",
					"path": "../node_modules/i18next-xhr-backend/dist/umd",
					"main": "i18nextXHRBackend"
				}, {
					"name": "aurelia-validation",
					"path": "../node_modules/aurelia-validation/dist/amd",
					"main": "aurelia-validation"
				}, {
					"name": "jquery",
					"path": "../node_modules/jquery/dist",
					"main": "jquery.min"
				}
			]
		}]
	}
}
```

**Comment by javiercbk** [comment]
Just solved it with @Ullfis setup [https://github.com/Ullfis/au-cli-skel/blob/master/aurelia_project/aurelia.json](https://github.com/Ullfis/au-cli-skel/blob/master/aurelia_project/aurelia.json)

**Comment by Thanood** [comment]
Thanks, @javiercbk, I'll take a look at that.
Any other components which throw errors?

Without having the chance to look at it right now (getting late here), my guess is that you may actually have two jQueries. I've read in a CLI issue somewhere that this may happen if you add ot to two bundles in a certain way.

Could you try to remove that one `jquery` in `vendor-bundle.js`, since none of its dependencies actually depend on jQuery?

**Comment by Thanood** [comment]
Wow, that was fast. 😃

**Comment by Thanood** [comment]
Maybe my assumption was even correct, he only has one jQuery defined in 'vendor-bundle` (it's essentially the same).

**Comment by javiercbk** [comment]
Something worth noticing (for future visitors)

As @Thanood noticed, jquery was as a dependency twice. Fixing that did not solve the issue

I had this bundle configuration
```json
{
			"name": "materialize-bundle.js",
			"dependencies": [
				"jquery", {
					"name": "materialize-css",
					"path": "../node_modules/materialize-css/dist",
					"main": "js/materialize.amd",
					"deps": [
						"jquery"
					],
					"resources": [
						"css/materialize.css"
					],
					"exports": "Materialize"
				}, {
					"name": "aurelia-materialize-bridge",
					"path": "../node_modules/aurelia-materialize-bridge/dist/amd",
					"main": "index",
					"deps": [
						"jquery"
					],
					"resources": [
						"**/*.{css,html}",
						"index.js"
					]
				}
			]
		}
```

I've replaced with this one:

```json
{
        "name": "materialize-bundle.js",
        "dependencies": [
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "deps": [
              "jquery"
            ]
          },
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "**/*.{css,html}"
            ]
          }
        ]
      }
```

Hope it helps

**Comment by Thanood** [comment]
@javiercbk 
I was curious and tried this:

>  jquery was as a dependency twice. Fixing that did not solve the issue

When I tried (the "fixing that" part), it actually solved the sidenav issue.
