### ISSUE TITLE
Chips editor + backspace

### ISSUE THREAD

**Issue by ctjhoa** [aurelia-ui-toolkits/aurelia-materialize-bridge#287]
Chips editor don't prevent browser backspace behavior.

Browsers affected:
- Firefox 49.0.1
- MS Edge

_Chrome is not affected_

Reproduction steps:
- Go to https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/chip/editor
- Click at the end of the input
- Press backspace
- Your browser redirect you to the previous page

**Comment by Thanood** [comment]
It happens here, too: http://materializecss.com/chips.html#basic
Not sure how to approach this. Maybe it's better when we post an issue at Materialize repo.

**Comment by ctjhoa** [comment]
NOTE: It happens only if you have page history in your browser. For example, if you open links in a new tab it will work fine.

**Comment by Thanood** [comment]
https://github.com/Dogfalo/materialize/issues/3923

**Comment by ctjhoa** [comment]
@Thanood it seems fixed upstream. Can you confirm

**Comment by Thanood** [comment]
@ctjhoa It seems to work for everyone but me, strangely.. I'm using Vivaldi browser, maybe that's my problem. 😃 

I've tried with Edge and Chrome and it works there.
