### ISSUE TITLE
Tabs style is broken in documentation

### ISSUE THREAD

**Issue by ctjhoa** [aurelia-ui-toolkits/aurelia-materialize-bridge#288]
Tabs style is broken in some part of the documentation.

Browsers: 
All

Steps:
- Go to https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/badge/
- Look at tab style of the "Code Preview"

![capture](https://cloud.githubusercontent.com/assets/1716173/19020288/1f582e12-88a5-11e6-956c-a5afa66490b0.PNG)

instead of 

![capture](https://cloud.githubusercontent.com/assets/1716173/19020297/36b4d0f6-88a5-11e6-9fed-b34f8b798de2.PNG)

Page list with this issue:
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/badge
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/breadcrumbs
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/chip
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/collections
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/footer
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/navbar
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/pagination
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/progress
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/dialogs
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/dropdown
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/modals
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/file
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/range
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/datepicker
- https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/autocomplete

**Comment by Thanood** [comment]
Thanks for pointing that out. It seems to happen in a `<compose>` context but I'm not sure. I couldn't resolve this so far.

**Comment by Thanood** [comment]
Interesting observation:
When using the same with a card in a card, it's not broken at all..

**Comment by Thanood** [comment]
Seems to be fixed with Materialize`s new tabs implementation.
