### ISSUE TITLE
Chips style is broken in documentation

### ISSUE THREAD

**Issue by ctjhoa** [aurelia-ui-toolkits/aurelia-materialize-bridge#289]
2nd chip is not correctly aligned/centered

Browsers:
All

https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/chip/

![capture](https://cloud.githubusercontent.com/assets/1716173/19020285/f733b956-88a4-11e6-86c3-433e0e5c6129.PNG)

**Comment by Thanood** [comment]
Hmm, Materialize site seems to have a css set but only for their site, not in the framework.
```css
float: right;
line-height: 32px;
font-size: 16px;
```

Adding this style to `md-chip`

**Comment by Thanood** [comment]
Not closing this because somehow it won't close anymore when you click the `X`.
I wonder how this actually worked last month (or so).
