### ISSUE TITLE
Range input thumb bugs

### ISSUE THREAD

**Issue by ctjhoa** [aurelia-ui-toolkits/aurelia-materialize-bridge#290]
#1 - Thumb stay active in firefox

Browser:
- Firefox 49.0.1

Steps:
- Use range one time
- Thumb stay active and follow the mouse

![capture](https://cloud.githubusercontent.com/assets/1716173/19020351/61beb5ea-88a6-11e6-9f26-e9c294aa148b.PNG)
#2 - MS Thumb not hidden

Browser:
- MS Edge

Steps:
- Use range and stay mouse down
- MS default thumb shows up in front of the material one

![sans titre](https://cloud.githubusercontent.com/assets/1716173/19020393/8e7b18a2-88a7-11e6-8034-76f8d5791cda.png)

**Comment by Thanood** [comment]
Any idea how to hide the MS thumb?

**Comment by ctjhoa** [comment]
```
input[type="range"]::-ms-tooltip {
  display: none;
}
```
this seems to do the trick

**Comment by Thanood** [comment]
Thanks. :smiley: 
Not sure what to do with the thumb following the mouse in Firefox. This may as well be an issue for Materialize itself. I'll check this out.

**Comment by Ullfis** [comment]
To hide the focus ring from range control in FireFox, add this to style:

```css
input[type=range]::-moz-focus-outer {
  border: 0;
}
```
