### ISSUE TITLE
Datepicker advanced options is broken in documentation

### ISSUE THREAD

**Issue by ctjhoa** [aurelia-ui-toolkits/aurelia-materialize-bridge#291]
Resource is missing

Browsers:
All

Steps:
- Go to https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/datepicker/advanced-options
- Resource `https://aurelia-ui-toolkits.github.io/src/aurelia-materialize-bridge/datepicker/datepicker.default-parser.js` 404 not found 

![capture](https://cloud.githubusercontent.com/assets/1716173/19020414/6b3cb7a0-88a8-11e6-9887-4f8dfaf8c5c9.PNG)

**Comment by Thanood** [comment]
Looks like a bundle error. I'll check this next time I prepare the catalog app. It doesn't happen in the unbundled app.

**Comment by Thanood** [comment]
Interesting, if I bundle without minifying, it works..

**Comment by Thanood** [comment]
These may be related:
https://github.com/aurelia/skeleton-navigation/issues/672
https://github.com/aurelia/bundler/issues/141

**Comment by Thanood** [comment]
I've updated the catalog app (bundler, aurelia-tools, the bridge) and now it works.
I will keep this open for a while to see if it occurs again.

**Comment by Thanood** [comment]
This is just wild.. I didn't change *anything* (I promise) and it doesn't work now..?

**Comment by Thanood** [comment]
Fixed. It was due to a relative path reference which didn't exist in the bundled version.
No idea why this actually worked from time to time..
