### ISSUE TITLE
md-select: initial selected value is not selected

### ISSUE THREAD

**Issue by tdamir** [aurelia-ui-toolkits/aurelia-materialize-bridge#292]
This works well on Chrome but on FF, Edge and IE11 the selected option is not selected. If I display the hidden select element, the option is selected.
```
<select md-select="label: Label" value.two-way="model.value">
    <option repeat.for="item of model.items" model.bind="item.id">${item.name}</option>
</select>
```
If I bind to selected attribute then the selected option will be selected on the first render on all browsers:
```
<select md-select="label: Label" value.two-way="model.selectedValue">
    <option repeat.for="item of model.items" model.bind="item.id" selected.bind="item.id == model.selectedValue">${item.name}</option>
</select>
```

**Comment by Thanood** [comment]
@tdamir I'm not sure if I got this right. What does this mean:
> If I display the hidden select element

What's the hidden select element? :smiley: 
Would you mind creating a gist with a reproduction of this issue? It's easier for me to see what's wrong.
Here's a base: https://gist.run/?id=e8eed34e8bba17f5213535bcdd004a9e

Does this work with a native select?

**Comment by Thanood** [comment]
Oh, now I understand what you mean with the hidden select. It's the native element which is wrapped by Materialize, right?

**Comment by Thanood** [comment]
This works:

https://gist.run/?id=598658b48d36328f52bd406c986ff6a6

**view**:

```html
<template>
  <select md-select="label: Label" value.two-way="model.value">
    <option repeat.for="item of model.items" model.bind="item">${item.name}</option>
  </select>
  <div>
    selected: ${model.value.id}
  </div>
</template>
``´

**view model**:

```javascript
export class App {
  items = [
    { id: 0, name: 'Option A' },
    { id: 1, name: 'Option B' },
    { id: 2, name: 'Option C' },
    { id: 3, name: 'Option D' }
  ];
  model = {
    items: this.items,
    value: this.items[1]
  };
}
```

**Comment by Thanood** [comment]
According to this hub entry, `model.bind` should be an object, not an object's property:
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/3

There's another description which describes how to use a matcher function. You could use the id there if you really need to match by id.

**Comment by tdamir** [comment]
I apologize for the confusion. Correct, I was referring to the native element by hidden select. The following is working as expected on native elements in all browsers. If you run this on Chrome the wrapper will also select the option but on Edge, IE and FF only native element is selecting correctly the option (according to the DOM inspector).
```
<template>
  <select md-select="label: Label" value.two-way="model.selectedValue">
    <option repeat.for="item of model.items" model.bind="item.someId">${item.name}</option>
  </select>
  <div>
    selected: ${model.selectedValue}
  </div>
</template>
```
```
export class App {
  items = [
    { someId: 0, name: 'Option A' },
    { someId: 1, name: 'Option B' },
    { someId: 2, name: 'Option C' },
    { someId: 3, name: 'Option D' }
  ];
  model = {
    items: this.items,
    selectedValue: 2
  };
}
```

**Comment by tdamir** [comment]
According to the doc this should work because we are working with numbers:
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/2

**Comment by Thanood** [comment]
I've copied your code into a gist and called it in Firefox 49:
https://gist.run/?id=2a45ef96c356828b51684937baa8fe8d

It seems to work there. The gist displays "selected: 2" and "Option C" is selected when I run it.
When I change the selected element, it updates the selected id.
Is that the expected behaviour?

I don't have access to Edge here and IE11 won't run gist.run. I'll try this in Edge when I get home.

And of course you're right with binding to numbers. I've overlooked that, sorry. :smiley:

**Comment by tdamir** [comment]
I tried your code on FF (49) and it works.  My colleague said that on FF sometimes it works and sometimes not. He is not sure about FF version. He will try the sample at home. On Edge it is not working for sure because I tried it.

**Comment by Thanood** [comment]
> On Edge it is not working for sure because I tried it.

That would be great, indeed. That way I may actually be able to find a reason for that. :wink: 
Will try it again on FF, too. Maybe I'm lucky and it doesn't work.

Did I get this right that this is only an issue when binding to a number? So our ["food" example](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/binding-to-objects) in the catalog app will work? I'd like to know because I think in that case we should add an example which binds to an index.

**Comment by tdamir** [comment]
I tried the food sample and option in the native element is selected (if initially set) but wrapper is not showing it on IE11 and Edge. As for the FF we figured out that it didn't worked because id was a number and selectedValue was a string (in our project) and in that case aurelia cannot match the element (probably they are using === for equality). So it looks like there are only issues with IE and Edge,

**Comment by Thanood** [comment]
Okay, thanks for the additional info! :smiley:

**Comment by Thanood** [comment]
Confirmed.. This is the starting status of a changed food sample in Edge (changed to have the second item selected):

![image](https://cloud.githubusercontent.com/assets/677826/19086598/1cd49b3c-8a6f-11e6-8ab1-038bc18b0f35.png)

**Comment by Thanood** [comment]
The difference between Chrome and Edge is: at the time the component is created, Chrome has `this.element.selectedIndex` set to "2", which is correct (the sample's view model set this).

The value of `this.element.selectedIndex` in Edge is, at this point, still "1" although the view model class is initialized before this happens. So this should really be "2" instead.

I couldn't really track this down further but I guess the `selectedIndex` is set to "2" after that, without firing a `change` event - in which case the Materialize select would have been updated.

I'm not sure how to approach this now but I'll try further. 😃

**Comment by Thanood** [comment]
Seems to be fixed when wrapping the initialization in a `taskQueue.queueTask()`.

**Comment by Thanood** [comment]
Released in [0.17.1](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/releases/tag/0.17.1).

**Comment by Thanood** [comment]
@tdamir About Firefox: I guess the reason why it sometimes works and sometimes doesn't is there's something running asynchronously. That should be gone with this change since the taskQueue runs at specific points in time.

Please try it with this change in Firefox. If it still happens, we can reopen this issue.

**Comment by tdamir** [comment]
@Thanood I think the Firefox issue was because of our code but I'll let you know if the issue persist. 
Thanks for the fix!
