### ISSUE TITLE
skeleton-typescript-webpack: duplicate identifier `a` since last skeleton update

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#295]
:point_up: [15. Oktober 2016 23:06](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=58029a6978bd0d0363c7fb7d)

Apparently the minified version of VelocityJS 1.2.3 in Materialize leads to an error:

```
ERROR in [default] D:\skeleton-typescript-webpack\node_modules\materialize-css\bin\materialize.js:1:6433
Duplicate identifier 'a'.
```

Reason (left: Velocity 1.2.3, right: Velocity 1.3.0):

![image](https://cloud.githubusercontent.com/assets/677826/19430583/0704b6ee-9455-11e6-9d3a-af072440c4a8.png)

This is probably due to TS update in the skeleton and could be solved by creating an own materialize-css with Velocity 1.3.0.

While this has no impact on the resulting app and we probably cannot solve this by ourselves (maybe try custom minification though), it's good to have this documented.

**Comment by Thanood** [comment]
:point_up: [17. Oktober 2016 17:08](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=5804e96780020cc608eac523)

**Comment by Thanood** [comment]
@kennyfowler wrote:

i would recommend to extend the installation instruction for webpack where you mention to exclude materialize from uglify (which is used in the production build of the aurelia-webpack-skeleton): you have to add a separate bundle (entry) for materialize (or other multiple modules), then you can exclude this bundle from uglify.

```javascript
const baseConfig = {
  entry: {
    'app': [/* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1),
    'materialize': ['materialize-css']
  },
  output: {
    path: outDir,
  }
}
```

and then

```javascript
require('@easy-webpack/config-uglify')
        ({debug: false, exclude: ['materialize']})
```

**Comment by MaximBalaganskiy** [comment]
Not relevant in the light of v1
