### ISSUE TITLE
aurelia-i18n not working with aurelia-materialize-bridge?

### ISSUE THREAD

**Issue by mar9000** [aurelia-ui-toolkits/aurelia-materialize-bridge#298]
with `t="[md-label]email"` in an `md-input` element the md-label seems to be set correctly but only after the label element gets created indeed the label content does not come from translation. The original md-input:

``` html
<md-input t="[md-label]email" md-label="E" md-type="email" md-value.bind="email"></md-input>
```

The result:

``` html
<md-input t="[md-label]email" md-label="Email" md-type="email" md-value.bind="email" class="au-target" au-target-id="96">
  <div class="input-field">
    [snip]
    <label ref="label" class="au-target" au-target-id="87" for="md-input-0">E</label>
  </div>
</md-input>
```

The label should show "Email" instead of "E".
I'm quite sure this is a bug of this project, can someone in case confirm it's a bug of the aurelia-i18n project instead?

**Comment by mar9000** [comment]
In fact (after investigation) i18n.js just use Element.setAttribute() on the node, in the above example set the attribute "md-label" is set to "Email". Still not sure if this is an aurelia-i18n bug or an aurelia-materialize-bridge bug.

**Comment by Thanood** [comment]
@Ullfis posted this in Gitter:

```html
<md-input
  md-type="password"
  md-label="${i18n.tr('admin:users.auth.create.Password')}"
  md-value.bind="password & validate">
</md-input>
```

I didn't try it, yet and I will try to find a way to make something like `t="[md-label]email"` possible.

**Comment by mar9000** [comment]
It's working but only when page is loaded. If you call i18n.setLocale() to change the language, the `label` element does not get changed.
The setAttribute() that changes the md-label attribute of `md-input` when using `t="...` is in i18n.js, at the end of the `updateValue()` method, in case you want further investigate.

**Comment by Ullfis** [comment]
md-label is [bindable](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/input/input.js#L14) and label should update if bound.

```html
<md-input md-label.bind="variable" ..
```
Could you try to bind it to a variable and change it in code?

**Comment by Ullfis** [comment]
I tried with a custom element:

```html
<template>
  <h1>${value}</h1>
</template>
```

```javascript
import {bindable} from 'aurelia-framework';

export class FooElement {
  @bindable() value;
}
```

And: 

```html
<foo-element t="[value]FirstName" value="s"></foo-element>
```

That work

But changing to this:

```html
<template>
  <h1>${mdValue}</h1>
</template>
```

```javascript
import {bindable} from 'aurelia-framework';

export class FooElement {
  @bindable() mdValue;
}
```

And: 

```html
<foo-element t="[md-value]FirstName" md-value="s"></foo-element>
```

Does not work. I don't think it is an error in the bridge.

**Comment by Thanood** [comment]
Maybe
```
<foo-element t="[mdValue]FirstName" md-value="s"></foo-element>
```
?

**Comment by Ullfis** [comment]
If changing to

```html
<foo-element t="[mdValue]FirstName" md-value="s"></foo-element>
```

This is generated in html:

```html
<foo-element t="[mdValue]FirstName" md-value="s" class="au-target" au-target-id="105">[mdValue]FirstName</foo-element>
```

btw.. this is generated with `[md-value]FirstName`:

```html
<foo-element t="[md-value]FirstName" md-value="First name:" class="au-target" au-target-id="105">
  <h1>s</h1>
</foo-element>
```

md-value attribute is correctly translated but component content is not updated.


This is output when using `[value]FirstName`:

```html
<foo-element t="[value]FirstName" value="s" class="au-target" au-target-id="105">
  <h1>First name:</h1>
</foo-element>
```

value attribute is not translated but content is

**Comment by Ullfis** [comment]
Here is an example project without bridge: https://github.com/Ullfis/esnext-i18n-errors

**Comment by mar9000** [comment]
Well done!
In fact the bug is in `i18n.updateValue()`, I'll add a comment on the aurelia-i18n bug.
In `node.au.controller.viewModel[attr]` the attribute exists but as `mdValue` instead of the actual value of `attr` that is `md-value`.
For me you can close this issue.

**Comment by Thanood** [comment]
Not yet.. I'd like to read through it again. 😃 

Well done, thanks @Ullfis and @mar9000 👍
