### ISSUE TITLE
[md-carousel] when option: md-slider is set to "true" nothing happen and in console log you can find errors. When md-slider i set to "false" everthing is ok.

### ISSUE THREAD

**Issue by niedarek** [aurelia-ui-toolkits/aurelia-materialize-bridge#299]
in md-carousel when option:  md-slider is set to "true" nothing happen and in console log you can find errors. When md-slider i set to "false" everthing is ok.

Here is gist: 

https://gist.run/?id=2001f34c6aa98023e6723853d9736d77

**Comment by Thanood** [comment]
Thanks for the gist. 👍 
It works in [the sample](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/media/carousel-special). I will have a look at it.

**Comment by Thanood** [comment]
Maybe a (gist-)bundle problem. The sample doesn't work in a gist either.

**Comment by Thanood** [comment]
This should work with 0.17.2 now.
But I can't load the gist bundle. It doesn't find `config2.js` - which is strange because it finds `config.js` in the same directory.

**Comment by Thanood** [comment]
Okay, just took some time.
It works: https://gist.run/?id=f2b61723e2f0990fd088d25037cbf528

😃

**Comment by niedarek** [comment]
I hit this problem during development my app :)

23 paź 2016 16:07 "Daniel Bendel" <notifications@github.com> napisał(a):

**Comment by niedarek** [comment]
Big thanks,
now it's working :)

Pozdrawiam

Darek Niedziałek


2016-10-24 18:55 GMT+02:00 Daniel Bendel <notifications@github.com>:

**Comment by niedarek** [comment]
Hey,
i find another bug ?
try add image to item
<md-carousel-item md-href="#one!" md-image="
http://lorempixel.com/250/250/nature/1"></md-carousel-item>

Pozdrawiam

Darek Niedziałek


2016-10-25 18:21 GMT+02:00 Dariusz Niedziałek <dzikpress@gmail.com>:

**Comment by Thanood** [comment]
Oh, that seems to be jQuery 3, right? Why do I have jQuery 3 in my bundle? Reopening because of this. 😃 

If you've installed jQuery 3, try downgrading to jQuery 2. I've had a look at the code, `img.load()` doesn't seem to accept a callback as url but Materialize sends one.

**Comment by Thanood** [comment]
Bundles updated with jQuery 2
