### ISSUE TITLE
Issues running unit-tests

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#30]
I've encountered some issues with Materialize while I was trying to run unit-tests for elements. I will document them here.

1. aurelia-pal-browser was missing - easy to solve: ```jspm install aurelia-pal-browser``` :smile: 
2. Materialize ```require```d "jQuery" (capital Q) while jQuery is registered as jquery - easy to solve if you know jspm maps: add ```"jQuery": "github:components/jquery@2.2.0",``` to the map
3. Materialize wants ```picker.js``` which is bundled. Systemjs looks in ```/base/jspm_packages/npm/materialize-css@0.97.5/bin/picker.js``` - don't know how to fix that

Note: the bridge (and thus karma/jasmine) now pulls Materialize from it's "source": npm:materialize-css. The dist version of materialize doesn't have this issue (point 3) itself.

Can we add a map to "jQuery" without mentioning its version? To be able to up/downgrade jQuery and still keep the map intact. (there are some documented issues with Materialize and jquery 2.2)

What would be a good solution for 3.?

**Comment by Thanood** [comment]
Tests work when using materialize from github.. Since the npm version seems to be incomplete/misconfigured (not sure) I wonder of we should just use the github version on the bridge.

**Comment by JeroenVinke** [comment]
```
  meta: {
    "materialize/bin/materialize": {
      "format": "system"
    }
  },
```

This seems to fix that problem, but now it can't find Waves :)

**Comment by Thanood** [comment]
Thanks.. I still need to learn System.js.. :-)
Is it "Waves" (capital W)? maybe it's the same issue as with jQuery.

**Comment by JeroenVinke** [comment]
It's a different error

```
Chrome 47.0.2526 (Windows 10 0.0.0): Executed 1 of 2 SUCCESS (0 secs / 0.001 secChrome 47.0.2526 (Windows 10 0.0.0) Waves applies waves-effect class FAILED
        ReferenceError: Waves is not defined
            at MdWaves.attached (D:/Development/aurelia-materialize-bridge/src/waves/waves.js:9:1596 <- D:/Development/aurelia-materialize-bridge/src/waves/waves.js:24:4)
            at Object.<anonymous> (D:/Development/aurelia-materialize-bridge/test/unit/waves.js:30:11)
```

**Comment by Thanood** [comment]
Interesting. When you use the github version it works.

Btw the github version should - from my understanding - be the same as what's in bin. Agreed? It isn't. It seems, Waves is not included and I'm pretty sure hammerjs and Velocity aren't included either.

Now that may be done on purpose to be able to include the original libs.

**Comment by JeroenVinke** [comment]
Instead of including the entire materialize library (bundled), have you thought about including individual files from the `js` directory (which is the source and thus unminified)? That way, we can debug easier, and users can minify and bundle these individual files using aurelia-bundler

**Comment by Thanood** [comment]
Yes, I've thought about it. It is generally a good idea but there are at least some parts of materialize which seem to depend on a "Materialize" global. These are at least toasts and modals.

When I tried that, first hammerjs was missing, then Velocity (needing a Vel variable which was required and globally defined but empty).

So maybe we cannot do it "as it is" and instead find a way to build that global requirements or find a way around these issues.

The way I see it atm is: Materialized is not made for a module system. There are even issues about that (some include workarounds).
**But**: That may be my lack of understanding their structure.

Btw: I had a quick look through the materialize grunt file and it seems everything is bundled in "dist".

**Comment by JeroenVinke** [comment]
OK, then I agree with using the dist folder. No idea why the npm version differs from the github version btw.

**Comment by Thanood** [comment]
Cannot get an override to stick.. It's overwritten on ```jspm install```.
```json
"overrides": {
    "npm:materialize-css@^0.97.5": {
      "main": "dist/js/materialize"
    }
  },
```

Is that wrong? Did it successfully with code-prettify this way.

**Comment by JeroenVinke** [comment]
you did put this in the jspm section right?

**Comment by adriatic** [comment]
### On GitHub versus npm
In nearly all cases, npm distribution lags behind GitHub, so I see all reasons to stick with GitHub until we understand the reasons for the difference

**Comment by Thanood** [comment]
@JeroenVinke 
> you did put this in the jspm section right?

Both package global and jspm section. Of course, the global entry does not get overwritten but it also has no effect.

@adriatic 
Alright. Then I'll use another branch for experiments with npm.
