### ISSUE TITLE
Select issue on iPhone

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#300]
:point_up: [23. Oktober 2016 15:06](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=580cb5c3015db84e6fbb7aad)

@robinchesterman wrote:

> Not sure if this is the place to mention, but selects don't work very nicely on my iphone. The wrapper appears, but the input box gets focused, so there's a big blue cursor blinking through and there's the iPhone selection control appears at the bottom (with nothing in it)
> Multiple select is particularly troublesome, as I can't even tap out of it.
> 
> ordinary materialisecss seems ok and doesn't have the problem

**Comment by Thanood** [comment]
https://github.com/Dogfalo/materialize/issues/2598
https://github.com/Dogfalo/materialize/issues/3790

**Comment by Thanood** [comment]
I totally did not realize that the second link I've posted contains a fix/workaround! 😃

**Comment by Thanood** [comment]
:point_up: [31. Oktober 2016 22:27](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=5817b75f806316005ddeff3a)

Documentation: redirect `touchstart` events to trigger a `click` on iOS.
:point_up: [31. Oktober 2016 22:27](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=5817b75f806316005ddeff3a)

**Comment by Thanood** [comment]
Added the css changes to md-colors..
Maybe it's time to split that file up, because this has nothing to do with colors.

Still need to check on an iPhone, so I'm keeping this issue open.

**Comment by GLedoussal** [comment]
Also, it seems that select multiple doesn't close properly. It's really hard for me to test it because I don't have an iPhone. Could you give a look @Thanood ?
