### ISSUE TITLE
Strange behavior with md-select

### ISSUE THREAD

**Issue by Ganbin** [aurelia-ui-toolkits/aurelia-materialize-bridge#301]
I'm submitting a bug report

Library Version: 0.17.1

Please tell us about your environment:

Operating System: OSX 10.11.5

Node Version: 6.9.1

NPM Version: 3.10.8

Browser: Chrome 53

Language: ESNext

Expected/desired behavior:
I want to have two select. The second select is disabled until we select a value in the first one. All this in a form which contain other fields (datepicker, number and text field)

Current behavior:
The current behavior is really weird and imply many behaviour depending if I add or remove a attribute in the `md-select`, if I set a default value, if I uncomment the datepicker, so I don't know if I have to open different issue but I think to put them all in one is more relevant because surely they are relative to each other.

First let me show you my code : 
`form.html`

```
<!-- <form submit.delegate="save()"> When I add the form tag, my page is not displaying anymore -_-' -->
  <div>
    <md-card md-title="Client">
      <div class="input-field col s12 m6"> <!-- the grid system seems not to work even when I have add the require in the app.html like says in the doc -->
        <select md-select="label: Client" value.two-way="selectedClient">
          <option value="" disabled selected>Select a client...</option>
          <option repeat.for="client of clients" value.bind="client.ID">${client.name}</option>
        </select>
      </div>
      <div class="input-field col s12 m6">
        <!-- <select md-select="disabled: disableCategorySelect; label: Category" value.two-way="selectedCategory">
          <option value="" disabled selected>Select a category...</option>
          <option repeat.for="category of categories" value.bind="category.ID">${category.name}</option>
        </select> -->
      </div>
    </md-card>
    <md-card md-title="Time">
      <div>
        <!-- <date-picker ID="startDate" label="Date" date.bind="worktime.start"></date-picker> -->
        <!-- if I uncomment the previous line, it will be render in between my two select -->
      </div>
    </md-card>
  </div>
<!-- </form> -->
```

`form.js`

```
export class Form {
    worktime;
    clients;
    //categories;
    //disableCategorySelect;
    selectedClient;
    //selectCategory;

    constructor() {
        //this.selectedClient = ''; //if I set my default selectedClient to '' then the value are not render anymore even if in the inspector I can see the values
        // this.selectCategory = '';
        // this.disableCategorySelect = true;
    }

    activate() {
            this.worktime = {ID: 1, name: 'test', start: new Date(), client: {ID: 1, name: 'My Company1'}};
            this.clients = [{ID: 1, name: 'Client 1'}, {ID: 2, name: 'Client 2'}];
    }
}
```

`datepicker.html`

```
<template>
  <label for.bind="ID">${label}</label>
  <input id.bind="ID" type="date" class="datepicker" value.bind="date | dateFormat: 'YYYY-MM-DD'" />
</template>
```

`datepicker.js`

```
import {bindable, bindingMode, decorators} from 'aurelia-framework';

export const DatePickerCustomElement = decorators(
    bindable({ name: 'date', defaultBindingMode: bindingMode.twoWay }),
    bindable({ name: 'ID', defaultBindingMode: bindingMode.oneTime }),
    bindable({ name: 'label', defaultBindingMode: bindingMode.oneTime })
).on(class {
    constructor() {
    }
    attached() {
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 3 // Creates a dropdown of 15 years to control year
        });
    }
});
```

I have put some comment directly in my code to keep a trace of the problems I have. But here are the main issues : 
1. The datepicker field is not well render when I have a `md-select`. Sometimes I see it in between the to select, sometime I see only the label of the datepicker and I cannot select a date.
2. The items are not displayed when I try to set the default value to `''`
3. If I add a `<form>` tag, the whole page is not displayed anymore, but no error in the console.

So the main issue is a rendering issue, I don't know where to investigate to fix this issue.

**Comment by Thanood** [comment]
> If I add a form tag, the whole page is not displayed anymore, but no error in the console.

Did you also call your custom element `form` or is that just an example?
Because this `<form>` inside of your custom `<form>` element is *not* an HTML form at that point but *your* custom element. It's recursive and so it's empty. 😃 

Call your custom element anything else, preferable something with a dash (for example `<my-form>`).

I've put the code into a gist here: https://gist.run/?id=e5af535897f7b6e03bd41b047ed0c252

> The items are not displayed when I try to set the default value to ''

I could not reproduce this in the gist but that was *after* renaming `<form>` to `<my-form>`.

Btw. there are some minor drawbacks when you use the "vanilla" Materialize datepicker. I've changed this to the bridge's datepicker. For example it doesn't show up again automatically when the page loses focus.

> The datepicker field is not well render when I have a md-select. Sometimes I see it in between the to select, sometime I see only the label of the datepicker and I cannot select a date.

I think this is because of `md-card` but I'm still looking at that.

**Comment by Thanood** [comment]
I forgot this:

> The items are not displayed when I try to set the default value to ''

I had to put the clients array in the class constructor. That way, setting the default value is set *after* `clients` is initialized. When you set it before `clients` is initialized, the select is refreshed and the default value is practically gone.

I still wonder why it didn't work to set `clients` in `attached()`, though. Still looking at it. 😃

**Comment by Thanood** [comment]
> the grid system seems not to work even when I have add the require in the app.html like says in the doc

A `col` needs to be in a `row`. Then it should work.

**Comment by Thanood** [comment]
Wow, this is ... strange.

> The datepicker field is not well render when I have a md-select. Sometimes I see it in between the to select, sometime I see only the label of the datepicker and I cannot select a date.

When I remove the `ID` attribute from both `date-picker` and the `input` inside `date-picker` it's displayed as it should.

I'm suspecting the use of two identical `ID`s. In general, be careful when you use bound attributes with the same name as HTML attributes. Again, call it something with a dash, that should be safe.

In this case, rename `datepicker`'s `ID` f.i. to `dp-id` (also rename the bindable, of course) and set the "real" `id` in the template and you should be good. I'll add this to the gist.

**Comment by Thanood** [comment]
Setting `clients` in `attached()` instead of `activate()` works. I overlooked that, sorry.
`activate()` is too early.

The gist is now in a state where I think it works as you would expect it. 😃 
https://gist.run/?id=e5af535897f7b6e03bd41b047ed0c252

**Comment by Ganbin** [comment]
Wow thanks a lot for the debug. I feel really like I'm so poor in knowledge.

I have change the name of my custom datepicker attributes names by `dpid` `dplabel` and `dpdate` and now I can make it work. How I have forget to put a `class="row"` around my col -_-. Sorry for the disturbance for this idiotie.

Finally I use your `md-datepicker` instead of my customElement to avoid the datepicker to open when I change from on tab to another in chrome. 

Actually my `form.js` is the name of my compoenent to display the form, it is not a custom element. I use the `form` as a normal `form` tag to do `<form submit.delegate="save()">` and still I have a empty page displayed. So it should not be a problem to use a `form`tag.

But still I have a problem when I try to set the default value to the `select a client...` option when I try to set the default value via the form class. SO I will try different things to see how I can do. I'm not sur if it on my side or a bug.

But thanks a lot for the feedback.

**Comment by Thanood** [comment]
No problem. 😃 
Please don't hesitate to edit the gist and relink it here if there seems to be any error/bug.

The gist I linked has "select a client" active but that's on Chrome/Windows. I don't know if it behaves differently on OSX.

**Comment by Ganbin** [comment]
I have to look what's wrong in my code because I have the same on my machine and it doesn't work like expected. On your gist it work nicely.

I still have a problem when putting a `form` tag all the page is not render. I use a routing to display my module.

And the client list is still not display even when putting my code in the attached. Weird. I don't know what could be the difference between my code and the gist...

**Comment by Thanood** [comment]
Try `md-select.ref="select"` on the select and `this.select.refresh()` after assigning the clients.
And (maybe) make sure that you use at least `0.17.1`.

**Comment by Ganbin** [comment]
Thanks a lot that make the things. Because in my example I show you I use static value when in my code I get data from a server so it come inside a promise. Thanks You save my day. :)

**Comment by Thanood** [comment]
Here's another one simulating a service call. 😃 
https://gist.run/?id=39fc63052657e67bdd10a69be01633ad

That one somehoe works without `refresh`.. Seems like I've lost track of my own project. 😉

**Comment by Ganbin** [comment]
Yes I don't know why on my side it was not working without the refresh. Sometimes it good to force the programme to do the things instead of expecting to work by itself. I gain knowledge from you thanks a lot. I love Aurelia way.
