### ISSUE TITLE
Validation issue in Chrome

### ISSUE THREAD

**Issue by andlebed** [aurelia-ui-toolkits/aurelia-materialize-bridge#302]
**I'm submitting a bug report**
- **Library Version:**
  0.17.2
- **Aurelia-validation Version:**
  0.13.1
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  6.7.0
- **NPM Version:**
  3.10.8
- **Browser:**
  Chrome 54.0.2840.71 (64-bit)
- **Language:**
  ESNext

view-model.js

```
import {inject, NewInstance} from 'aurelia-framework';
import {ValidationController, ValidationRules} from 'aurelia-validation';
import {MaterializeFormValidationRenderer} from 'aurelia-materialize-bridge';

@inject(NewInstance.of(ValidationController))
export class ViewModel {

  email = '';
  isDisabled = false;

  constructor(controller) {
    this.controller = controller;
    this.controller.addRenderer(new MaterializeFormValidationRenderer());

    ValidationRules
      .ensure('email')
      .required().withMessage('We need your email')
      .email().withMessage('Wrong email')
      .on(this);
  }

  submit() {
    this.isDisabled = true;
  }

}
```

view.html

```
<template>
  <form submit.delegate="submit()">
    <md-input md-label="Email" md-value.bind="email & validate" md-disabled.bind="isDisabled" md-validate="true"></md-input>
    <button md-button="disabled.one-way: isDisabled; flat: true;">Send</button>
  </form>
</template>
```

**Current behavior:**
Type valid email into input, click "Send" button. Input contains "valid" in the class name.
![screen shot 2016-10-25 at 03 09 18](https://cloud.githubusercontent.com/assets/18438857/19668472/c226aaca-9a60-11e6-977f-d0c805375cd6.png)

Type valid email into input and press Enter. Input contains "invalid" in the class name.
![screen shot 2016-10-25 at 03 09 35](https://cloud.githubusercontent.com/assets/18438857/19668483/d0ab8e62-9a60-11e6-9d60-e13146714bac.png)

**Expected/desired behavior:**
Input should remain valid after form submission by Enter.

Without md-validate="true" works fine.

**Comment by Thanood** [comment]
Hmm, this seems to happen because the input field doesn't lose focus on Enter (it doesn't `blur`?)..
In [the catalog example](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input/aurelia-validation) you can even see the success message on top of the failure message.

![image](https://cloud.githubusercontent.com/assets/677826/19755861/e2797be0-9c18-11e6-8b4e-a31d5b1e38f9.png)

Making the input field lose focus in any way (clicking outside the input field, switching browser tab) seems to trigger the correct validation.

**Comment by Thanood** [comment]
Tbh I think with aurelia-validation this is totally up to the user. That means if you configure `blur` as the validation trigger (it's the default)  it won't trigger on `change` or `keyup`. Native input elements don't blur on enter, either..

However, I know from personal experience that such a `blur-on-enter` functionality comes in very handy. I will add an additional option as a custom attribute `md-blur-on-enter` which does that. It will blur the input on enter and thus trigger validation.
