### ISSUE TITLE
md-select: Setting a disabled default value does not work when value is bound

### ISSUE THREAD

**Issue by FreakenK** [aurelia-ui-toolkits/aurelia-materialize-bridge#303]
See following GistRun:
https://gist.run/?id=478d9a86b3e0e505f264cda4c3743794

Current behavior: First option from the list is selected

Expected behavior: Default option should be selected

Workarounds: Remove _value.two-way="selectedValue"_ from the md-select element OR remove the _disabled_ attribute from the default option.

Thanks for the awesome work!

**Comment by Thanood** [comment]
Not sure why this doesn't work with `null`. But matching the exact value with the default item works:

```javascript
export class App {
  selectedValue = '';

  ...
}
```

Or even `selectedValue = 'nothing'` if the select option is defined by `value="nothing"`.

**Comment by FreakenK** [comment]
I could have sworn I tried that before opening this issue... Thanks, it works!
