### ISSUE TITLE
make md-disabled bindable for switch.js

### ISSUE THREAD

**Issue by JanJordan** [aurelia-ui-toolkits/aurelia-materialize-bridge#306]
Afaik right now something like this does not seem to work:

`<md-switch md-disabled.bind="! configuring" md-checked.bind="eco"></md-switch>`

The switch can only be set disabled initially with something like: md-disabled="! configuring"

Maybe something like this could work (in switch.js) to make this dynamic?

`mdDisabledChanged(newValue) {
    if (this.checkbox) {
      this.checkbox.disabled = !!newValue;
    }
  }
`

**Comment by Thanood** [comment]
Yep, good catch! 👍 
Will do that.

If you want, you can also issue a PR and I will merge it.

**Comment by JanJordan** [comment]
Thank you @Thanood, great!
sorry but i was submerged in work, no time to create the pr
