### ISSUE TITLE
migrate to "registry" structure for simpler contributions

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#308]
migrate to registry:
- [x] button
- [x] card
- [x] checkbox
- [x] collapsible
- [x] ~~color~~
- [ ] media
- [ ] parallax
- [ ] pushpin
- [ ] radio
- [ ] scrollfire
- [ ] scrollspy
- [ ] sidenav
- [ ] tabs
- [ ] transitions

Had to revert color changes..

**Comment by Kukks** [comment]
Should I fork a specific branch to help out on this? I might have some free time today :)

**Comment by Thanood** [comment]
No specific branch, it's all on master. 😃 
Thanks!

**Comment by Thanood** [comment]
@Kukks I'm going to rewrite the samples to run as external gists. So there will not be a need for "registry" types anymore and the samples will each be runnable by gist.run with a button click.

Another advantage of that will be that all samples can be integrated in external sites, f.i. blog posts or something like builtwithaurelia.com
