### ISSUE TITLE
Implement button

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#31]
There are no stand-alone buttons in the catalog app but many examples will use them: button (of course), dropdown, modals (to trigger the modals), toasts, waves and so on.

Usage example:
```html
<button md-button="disabled.bind: someVariable; flat: true;">
  my button
</button>
```
Which translates to
(someVariable = true):
```html
<button class="btn-flat disabled">
  my button
</button>
```

(someVariable = false):
```html
<button class="btn-flat">
  my button
</button>
```

**Comment by adriatic** [comment]
Given the fact that `button` is a "sub-class" of the HTML 5 <input> element, there is no reason to create it as a custom element in any bridge related context.

**Comment by Thanood** [comment]
That is one of the reasons why it is a custom attribute and not an element. :smile: 
The others being: react to native events, use other elements as a button (```<a md-button>```)

**Comment by adriatic** [comment]
Agreed - I clearly misunderstood your intent - sorry :-)

**Comment by Thanood** [comment]
I could have written it in the original issue like I did with #21. Actually I like to do that more: state explicitly why attribute/element.

**Comment by Thanood** [comment]
While buttons themselves are simple components, floating action buttons (FAB) are not. They have a set of classes and methods which only apply to FABs, for example:
* horizontal (css)
* openFAB(), closeFAB()
* click-to-toggle (css)
* positioning (for fixed FABs)

I think we should introduce a separate attribute for them.
Any thoughts?
