### ISSUE TITLE
Aurelia-CLI unit tests warn about hammerjs etc.

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#316]
See here:
http://stackoverflow.com/questions/40143563/using-aurelia-materialize-bridge-with-karma-testing

I've tried it and `materialize-bundle.js` contains these files.

**Comment by Thanood** [comment]
ATM I'm suspecting requirejs path shenanigans.

**Comment by Thanood** [comment]
The generated AMD compatible version bundles `hammerjs` like this:

```javascript
define.amd?define('hammerjs',[],function(){return hc}
```

This works for using it in an app. The `materialize-bundle.js` also contains this definition.
However, when using this in tests, the bundle suddenly defined `hammerjs` like this:

```javascript
amd?define('    hammerjs',[],function(){return hc}
```

I made the whitespace visible here since pasting that part from the source (Chrome dev-tools) did omit the whitespace.

**Comment by Thanood** [comment]
As mentioned in [this SO answer](http://stackoverflow.com/questions/40143563/using-aurelia-materialize-bridge-with-karma-testing), it works when modifying `karma.conf.js` like this:

```javascript
let otherBundle = path.join(output, 'materialize-bundle.js');
let entryBundle = appSrc.splice(entryIndex, 1)[0];

let files = [entryBundle, otherBundle].concat(testSrc).concat(appSrc);
```

**Comment by MaximBalaganskiy** [comment]
Latest instructions on CLI are working perfectly
