### ISSUE TITLE
sidenav overlay on top of the sidenav

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#319]
I think this only happens on a fixed sidenav which is hidden due to screen size.
In that case, when you click the collapse button, the overlay is above the sidenav, although its `z-index` is lower.

**Comment by Thanood** [comment]
Seems to be fixable by using a specific nav structure..
https://github.com/Dogfalo/materialize/issues/3918

> You can put navbar-fixed class on nav and close nav as soon as top navigation bar code ends

http://fiddle.jshell.net/oepn5ccc/

**Comment by MaximBalaganskiy** [comment]
Not sure why this is still open
