### ISSUE TITLE
Implement panel bar

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#32]
This is not exactly part of the basic user interface but the side-bar navigation on the Materialize website behaves a lot like the side-navigation of the current help section in this materialize-bridge.

Also it's quite similar to the [variations](http://materializecss.com/side-nav.html) section of the SideNav component on Materialize website.

No usage example yet and I'm not sure if it really fits in this early milestone.

**Comment by adriatic** [comment]
The basic user interface (which is to be implemented in Twitter Boostrap for already explained reasons - part of which is that all Aurelia Skeletons are built this way) use the `accordion` for the side-bar. There is no reason that should prevent you to switch to native Materialize alternative

**Comment by Thanood** [comment]
You're right, i've kind of switched the original meaning a little to "implement for **this** bridge". But then this is also a good starting point for anyone doing aurelia-xxx-bridge, including me. :smile:

**Comment by Thanood** [comment]
Removed from milestone as this is more of a "bonus" component.

**Comment by Thanood** [comment]
reference:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/32
