### ISSUE TITLE
Preloader not displaying before router.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#321]
Again I not sure this is a bug . It's not even that important as the fontawesome spinner works fine. I have just become obsessed with why it wont work :)

I have a really simple project at https://github.com/glennpierce/preloader_test
that shows the preloader not loading as the splash screen.

I think materialize has loaded fine as if you comment out

config.map([
      { name: 'test',  route: ['', 'test'],  moduleId: './test',   title: 'About' },
    ]);

The preloader shows. 
 
What is really frustrating is I have another project where it works. Same node_modules same webpack.config.js. Not sure what could be different.

Any tiips on debugging issues like this. So far I have just about removed everything I can to simplfy.

Thanks

**Comment by Thanood** [comment]
This is more of a question about Aurelia load order when a router in involved. I cannot answer that, though. :smiley:

In your `index.html` you have `<require>`-ed the Materialize css file. I guess this is only processed when the router is ready and finished navigating. But that's only a guess.
What happens if you use an ordinary `<link>` tag there to reference the css?

**Comment by glennpierce** [comment]
Yep the ordinary link worked.

**Comment by Thanood** [comment]
If you want to rely on the module system, I did this with SystemJS and `System.import('materialize/css/materialize.css!');` in [the index file](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/index.html#L91). Not sure how this would work with webpack, probably direct `require()` in a script tag.

But that will inject the css anyway..

**Comment by glennpierce** [comment]
Not sure I mind. I was just curious. 
I did just manage to get most of my project ported to aurelia cli which not too many issues so I may go that route. I am guessing in the future there will be more help and guides made for that workflow. In a way I wish Aurelia would just standardise on one setup.

Thanks for the help. Loving materialize bridge.

**Comment by Thanood** [comment]
> In a way I wish Aurelia would just standardise on one setup.

Yeah that would be very convenient, especially for beginners (of Aurelia). When there was only JSPM really supported (although they always said, it's going to run with anything) I think it was a bit easier. But then you would "lose" all the webpack folks and whatever is the next bis thing. :smiley: 

> Thanks for the help. Loving materialize bridge.

Thanks a lot! :smiley:
