### ISSUE TITLE
Checkbox using objects

### ISSUE THREAD

**Issue by williamfelippe** [aurelia-ui-toolkits/aurelia-materialize-bridge#323]
I'd like to know how to do to use the md-checkbox with objects.

Basically I want to do the example of the Aurelia doc, but is not working properly.

app.html
```
<template>
  <form>
    <h4>Products</h4>
    <label repeat.for="product of products">
      <input type="checkbox" model.bind="product" checked.bind="selectedProducts">
      ${product.id} - ${product.name}
    </label>

    Selected products:
    <ul>
      <li repeat.for="product of selectedProducts">${product.id} - ${product.name}</li>
    </ul>
  </form>
</template>
```

app.js
```
export class App {
  products = [
    { id: 0, name: 'Motherboard' },
    { id: 1, name: 'CPU' },
    { id: 2, name: 'Memory' },
  ];

  selectedProducts = [];
}
```

I'm trying this way below, but is not working.

```
<form>
   <p repeat.for="product of products ">
      <md-checkbox md-checked="false" model.bind="product.id" checked.bind="selectedProducts ">
         ${product.name}
      </md-checkbox>
    </p>
</form>

<p>${ selectedProducts }</p>
```

Sorry by the bad english

**Comment by Thanood** [comment]
While your sample is a bit different from the one in the docs (not sure if binding to `id` would work in this case), I think that it is not the problem. I guess it's because the `md-checkbox` doesn't have a model binding.

That's bad. I'll implement it.

> Sorry by the bad english

Don't worry about that. It's not my native language, either. :smiley:

**Comment by Thanood** [comment]
Probably need to forward `matcher` , too.

**Comment by williamfelippe** [comment]
Thank you. It will be great! 
I didn't understand the second reply.

**Comment by Thanood** [comment]
You can also bind checkboxes by using a "matcher", which is basically a compare function that checks if one element matches another. See here for details: http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-checkboxes/5

And I think to have complete support, I would need to add this "matcher", too. :smiley:

**Comment by williamfelippe** [comment]
Hmm... but this needs the model.bind too =(

**Comment by Thanood** [comment]
Yes. I mean to add both.

**Comment by williamfelippe** [comment]
Hahah ok
Thank you! I'll wait

**Comment by Thanood** [comment]
This change works internally but it's a bit tricky. We didn't bind `checked` directly and I need to look up why. I don't remember.. This will take a little more time, I guess.

**Comment by Thanood** [comment]
Okay, I didn't find it and my tests were all positive.
So I'm going to release this.. I hope I don't break anything. 😃

**Comment by Thanood** [comment]
@williamfelippe http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/checkbox/binding-to-objects

😃

**Comment by williamfelippe** [comment]
Thanks @Thanood!
