### ISSUE TITLE
Error creating amd compatible version of materialize

### ISSUE THREAD

**Issue by rosshigh** [aurelia-ui-toolkits/aurelia-materialize-bridge#326]
I'm following the process at:  [https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html).  I've gotten to this command:

`./node_modules/.bin/r.js -o rbuild.js`

I'm getting this error:

`Error: Error: Build file C:/Development/UCCSS/material/uccss/rbuild.js is malformed: SyntaxError: Unexpected token <
    at Function.build.createConfig (C:\Development\UCCSS\material\uccss\node_modules\requirejs\bin\r.js:26821:23)`

I have aurelia-cli version 0.22 and I've tried both versions of rbuild.js.

Any suggestions would be greatly appreciated.

Ross

**Comment by Thanood** [comment]
Are you using a bash-compatible shell to run this command?

**Comment by rosshigh** [comment]
I tried with git bash and the Windows command prompt.

**Comment by Thanood** [comment]
Hmm, how did you retrieve the `rbuild.js` file? I'm only guessing now but if you open it, is it html by any chance?

**Comment by rosshigh** [comment]
A bit embarrassing but that was it.  Thanks!

**Comment by Thanood** [comment]
No need to be embarrassed. :smiley: 
Maybe the documentation is not clear at that point. I guess it won't hurt to either describe explicitly what to do or provide doenloadable files.

**Comment by Thanood** [comment]
fixed the docs 😉
