### ISSUE TITLE
[Pagination] when visiblePageLinks or number of pages is set to 3, the display is not correct

### ISSUE THREAD

**Issue by Ganbin** [aurelia-ui-toolkits/aurelia-materialize-bridge#327]
When using the pagination, I have found a stange behaviour when dealing with a small pagination.

You can test the behaviour on this page : [Pagination Test Page](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/pagination/options) by setting the `Number of pages` or the `Number of visible links` to `3`, you will see that the selected page is not correctly display.

**Comment by Thanood** [comment]
Wow.. Nice catch. I will have a look at this. :+1:
