### ISSUE TITLE
Modal cannot open when placed in activate()

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#328]
I am trying to display a modal by calling

this.loginDialog.open(); in activate but I get 

TypeError: Cannot read property 'open' of undefined.
This is to display a login dialog.

In the template I have 

```
<div id="loginModal"  md-modal="dismissible: false;" md-modal.ref="loginDialog">
    <div class="modal-content">
      <h2>Username:</h2>
      <input value.bind="auth.username" attach-focus="true" />
      <br />
      <h2>Password:</h2>
      <input type="password" value.bind="auth.password" attach-focus="false" />
      <br /><br />
      <span innerhtml.bind="auth.error">No Error</span>
    </div>
    <div class="modal-footer">
      <a click.delegate="tryLogin()" md-button="flat: false;" md-waves="color: accent;" class="modal-action modal-close">Sign In</a>
    </div>
  </div>
```

Open works in a button callback like in the demos.
Is there a workaround for this ?

Thanks

**Comment by Thanood** [comment]
@glennpierce 
Please try `TaskQueue` in `attached()` like in this gist:
https://gist.run/?id=47b3007527a735abd3e3edbc5ccd3d58

**Comment by glennpierce** [comment]
Yep that works. Thanks.
Why is that necessary? I am reading up on TaskQueue now.

**Comment by Thanood** [comment]
I'm not really sure *when* the view and the component is attached. If the view is attached after the component then there is nothing to open, yet.

That's a guess, though. :smiley:

**Comment by Thanood** [comment]
Btw. you can use "manual close" to prevent the dialog from closing automatically so you can check credentials in `tryLogin()` and only close the modal if the user logged in successfully..
Sample: http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/modals/manual-close

Just remove the `modal-close` css class and call `this.loginDialog.close()` from `tryLogin()`.

**Comment by glennpierce** [comment]
Seems to work. Thanks
