### ISSUE TITLE
Find a replacement for Bootstrap's well

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#33]
To be able to completely implement the samples section, there should be some equivalent of Bootstrap's well.

![image](https://cloud.githubusercontent.com/assets/677826/12464694/911c6904-bfca-11e5-821c-d2306e6e7f2d.png)

Or, maybe, put these links into the side-bar.

**Comment by Thanood** [comment]
I will try [pushpin](http://materializecss.com/pushpin.html)

**Comment by Thanood** [comment]
Any opinions on this?

![image](https://cloud.githubusercontent.com/assets/677826/12506480/7af5d5ea-c0ef-11e5-8943-d158571cc352.png)

Unfortunately it looks funny on phones.

**Comment by JeroenVinke** [comment]
So materialize doesn't have a control like Bootstrap's well?

If that's the case, can we create an Aurelia custom element which renders a menu? So with `repeat.for` on a list item and styles via css (and js for waves)

**Comment by Thanood** [comment]
Materialize doesn't but their website has something like it on its right edge. The above is a copy of that (with borders) and it works like you said:

> So with repeat.for on a list item and styles via css (and js for waves)

You're right, we should make a custom element of it.

**Comment by JeroenVinke** [comment]
Does that work? If so, very nice :)

**Comment by Thanood** [comment]
Why should it not work? :smile:
It is just html/css with a bound router.

**Comment by JeroenVinke** [comment]
Then look no further :)

**Comment by Thanood** [comment]
Alright then.. :smile:
