### ISSUE TITLE
refactor md-colors

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#331]
The `md-colors` component should help with using color schemes and themes. At the moment it contains some other css, not related to colors but needed for certain features to work correctly. For example it contains [validation styles](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/colors/md-colors.html#L246-L271) which lead to validation error messages being black instead of red if the user chooses to not use `md-colors`.

**Comment by Thanood** [comment]
Also see #344 for an idea to include more colors derived from accent/primary.

**Comment by MaximBalaganskiy** [comment]
md-colors or some other element with the fixes should be included any way, so why split them up.
Anyhow, most of the fixes are removed now
