### ISSUE TITLE
Textarea autoresize workaround does not work anymore

### ISSUE THREAD

**Issue by eikaramba** [aurelia-ui-toolkits/aurelia-materialize-bridge#333]
Regarding https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/103, the sample on http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input/textarea does not autoresize anymore.

Tested on latest FF and Chrome.

**Comment by Thanood** [comment]
Confirmed. I will have a look into that.

**Comment by Thanood** [comment]
Interesting.. This still works in my current development catalog. It's not bundled but apart from that, no big differences.

**Comment by eikaramba** [comment]
thx, that also solves the problem at hand. I actually didn't even tried the workaround locally when i saw it didn't worked online

**Comment by Thanood** [comment]
Sample fixed (if cache doesn't trick you). 😃
