### ISSUE TITLE
skeleton-webpack issue Materialize.updateTextFields is not a function

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#337]
:point_up: [13. Dezember 2016 21:50](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=58505f0baeb490080485a576)

Materialize seems not to be initialized (again) before the bridge loads.
Using `md-input` in the skeleton-navigation project leads to the error in the title.

**Comment by Thanood** [comment]
md-select doesn't work either.

**Comment by Thanood** [comment]
Sometimes brute-force helps finding a way... 😏 

```typescript
function waitForMaterialize() {
  return new Promise((resolve, reject) => {
    let iterations = 0;
    const handler = window.setInterval(() => {
      iterations++;
      let ma = (window as any).Materialize;
      if (
        ma.elementOrParentIsFixed &&
        ma.escapeHash &&
        ma.fadeInImage &&
        ma.guid &&
        ma.scrollFire &&
        ma.showStaggeredList &&
        ma.toast &&
        ma.updateTextFields
      ) {
        console.log(`waited ${iterations} iterations for Materialize to finish loading`);
        window.clearInterval(handler);
        resolve();
      }
    }, 1);
  });
}
```

At the top of `configure()`:

```typescript
await waitForMaterialize();
```

**Comment by Thanood** [comment]
Seriously, `Materialize` is not finished initializing itself when Aurelia kicks in. No wonder some functioins cannot be found. Need to find a (prettier)  way to wait for it.

**Comment by HIRANO-Satoshi** [comment]
I'm having this issue. The brute-force work around seems working.

**Comment by Thanood** [comment]
Great that it works. Thanks for you feedback. :+1:

**Comment by sboyd** [comment]
I'm assuming that (window as any).Materialize is TypeScript what would this same line look like in vanilla js?

Thanks!!

**Comment by Thanood** [comment]
> I'm assuming that (window as any).Materialize is TypeScript

Yes, it is. It's used so the TypeScript transpiler doesn't complain about it.
In vanilla JS it would simply be `window.Materialize`. 😃

**Comment by sboyd** [comment]
Thank you for such a quick response.
That got rid of the error I was seeing "Materialize.updateTextFields is not a function", but the date picker still doesn't do open a calendar when I click in the field. Let me make sure I'm not missing some other step.

Thanks again --Steve

**Comment by Thanood** [comment]
Hmm, are there any errors? How are you using it? 😃 
Maybe you can create a gist based on this one: https://gist.run/?id=e8eed34e8bba17f5213535bcdd004a9e

I've had that once in a modal and the way to solve it was to remove the `container` option completely.

**Comment by sboyd** [comment]
Thanks! I may take you up on that. I'm in the process of seeing which components work and which ones don't. Things like text fields, radio buttons, checkboxes, and the accordion are working. The datepicker isn't (not seeing any errors in the console), and I just tried a Card and it isn't displaying correctly. I'm assuming I'm not doing something write and don't want to use any more of you time then I need to, so I'll struggle around with it for a bit and reach out. I appreciate the support!!
![worth1000](https://cloud.githubusercontent.com/assets/219548/25750864/4ff05e72-3170-11e7-83cc-0281db320a25.png)

**Comment by Thanood** [comment]
The `md-card` component is very limited compared to what materialize cards can do. But I guess it will always be since their card is very versatile.

If you find something regarding datepicker, I would like to here that. 😃

**Comment by sboyd** [comment]
Ok..so I'm not sure what I'm missing, but I forked your gist https://gist.run/?id=27d937255675fee9d1200bab259940d0 and took the code from [here](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/datepicker-basic-use) and the date picker does the same thing that I'm seeing locally on my box which is nothing. I'm using the skeleton-esnext-webpack as my starting point which has bootstrap. I've had to remove it in order to get the modal to work correctly and I was hoping there was a conflict with the date picker but removing bootstrap didn't resolve my datepicker issue. I really appreciate your help, and I probably should start a new thread now that I think about it. Looking forward to your thoughts. Thank you!!

**Comment by Thanood** [comment]
Hmm, remove `container: body; ` - but I definitely need to look into that. It shouldn't happen.

**Comment by sboyd** [comment]
LOL something so simple!! Thank you so much it's working well now :0) 
I think that was my last hurtle in deciding whether or not I'd be able to use these controls in my app.
Have a wonderful day

**Comment by Thanood** [comment]
You, too! 😃
