### ISSUE TITLE
Should this library now change to just be a plug-in wrapper around Google's newly released Material Components?

### ISSUE THREAD

**Issue by drub0y** [aurelia-ui-toolkits/aurelia-materialize-bridge#339]
This _just_ happened AFAICT, but just wanted to start a discussion and hear what the thoughts of the maintainers are.

Google has released a preview of their [Material Components](https://github.com/material-components) which effectively offers first class implementations for the web and other platforms, should this library switch directions and throw out its proprietary implementations and just focus on being a pure "wrapper" around that library in the form of an Aurelia plug-in?

**Comment by Thanood** [comment]
MDC really surprised me (this is an understatement)..

That project seems to be basically MDL v2 (Material Design Lite). There's an [open question](https://github.com/google/material-design-lite/issues/4984) on the MDL repo which asks about the relationship of the two projects.
I had a look and it really looks the same, same maintainers, same principles, even my [Aurelia example](https://github.com/material-components/material-components-web/tree/master/framework-examples/aurelia) is copied (and renamed).

While this is really an interesting project, the only relation to *Materialize* is that both implement Material Design principles. I think Materialize users will expect a "Materialize bridge" to implement wrappers for Materialize, not MDL/MDC (there are some Aurelia plugins for MDL). 😃 

MDC would probably be a good candidate for another bridge of its own.
Now that the catalog app infrastructure relies on gist.run for samples this wouldn't even take a lot of time, I guess (apart from writing the docs). If anyone wants to take a shot at that, I'd be glad to help.

But this project here (Materialize bridge) will continue providing Materialize wrappers. 😃

**Comment by drub0y** [comment]
@Thanood Awesome! Thanks for taking the time to do a deeper analysis and for giving such a thoughtful response. I totally agree, based on both your analysis and further analysis of my own later last night, that it makes sense that this lib (AMDB) should continue to provide its own full implementation of Materialize.
