### ISSUE TITLE
datepicker icon

### ISSUE THREAD

**Issue by ariovistus** [aurelia-ui-toolkits/aurelia-materialize-bridge#340]
I'm trying out the datepicker component with option showIcon: true, and the icon wraps to the next line.
In the demo it doesn't, because there is some custom css that fixes it up, which I included in my app. Is this css going to be included in the project at some point?

Also, with option showIcon: true, and validation hooked up, validation messages display above the input rather than below it. Is this expected?

**Comment by Thanood** [comment]
You're right. Thanks for pointing that out..
Maybe `showIcon` could add another class so it's distinct in css.
I should at least add the css to the sample page.

I will have a look at the validation issue.

**Comment by Thanood** [comment]
@ariovistus 
As for the icon issue, I've decided against adding it to the bridge statically. I just can't expect users to provide a certain structure. But I've added the necessary css to the gist and thus it now appears on the sample page.

But I'm open for arguments. 😃

**Comment by Thanood** [comment]
@ariovistus 
Updated the bundles.
Is this what you'd like to achieve? https://gist.run?id=0857ed09491c1e551fcf68cb49723574

**Comment by ariovistus** [comment]
Looks about right, except the css for the error message (font color, size) seems to have disappeared.

For the icon, materialize sets the width of the input to 100% by default, and the developer has to go out of their way to override this. The icon in this widget is styled improperly by default for when the width is 100%, and the developer has to go out of their way to fix this. It seems like the latter part should be reversed - the default styling should work for the default case. If the developer chooses to do something other than the default, it seems reasonable to expect that they will have to do any fixups, but this library should make it easy for them to do that.

I think an additional class on the icon would work if the developer can override it, eg

```javascript
     showIcon: true,
     iconClass: "icon-fixup-2", /* defaults to std-icon-fixup */
```

then this library would provide the styling for `std-icon-fixup`, and perhaps stylings for other common cases as they are found, but the developer is provided the flexibility to do what they need to.

**Comment by Thanood** [comment]
Agreed. I'll try that. Thanks. 😃

**Comment by Thanood** [comment]
I've added this. Keeping the issue open to remind myself to update the gist.

**Comment by Thanood** [comment]
Gist updated and documented: http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/datepicker-advanced-options
