### ISSUE TITLE
add md-tabs custom element

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#342]
Like custom attribute - and in addition to the existing one - but used like this:

```html
<md-tabs>
  <md-tab md-title="the tab title">tab content</md-tab>
</md-tabs>
```

**Comment by Thanood** [comment]
Started work here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/9091f2875e6b26af920aa096c677246c4ffa7aea

This is even without Materialize's JS but still using jQuery and (global) Velocity.
@swalters If you'd like to have a look, clone the `au-md-tabs` branch. 😃

**Comment by MaximBalaganskiy** [comment]
Not sure what we're gaining with this. Staying close to the original framework for now
