### ISSUE TITLE
Color Variables

### ISSUE THREAD

**Issue by joshua1** [aurelia-ui-toolkits/aurelia-materialize-bridge#344]
Hi Aside md-primary-color md-accent-color and that of error, there are a host of color variables one would like to change like 
```
.dark-primary-color    { background: #455A64; }
.default-primary-color { background: #607D8B; }
.light-primary-color   { background: #CFD8DC; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #009688; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }```
how does one go about changing them. Are there bindings for these?

**Comment by Thanood** [comment]
Are these really css classes? I've searched the (compiled) `materialize.css` for `dark-primary-color` and `divider-color` and there were no hits.

Or are these the color vars in the SASS source?

**Comment by joshua1** [comment]
This are variables for colors, check here https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss

**Comment by Kukks** [comment]
What I did in my projects was that I excluded the materialize CSS files from loading as per installation instructions, and then importee the scss from the node modules into my own scss index.

You ll also need to move the fonts to your root however.

**Comment by Thanood** [comment]
Ah great, so these variables are essentially shades derived from primary and accent colors, right? I mean you don't input all of these colors when using the materialpalette app. It calculates them.. 😃 
Btw: is that list complete? Does it mention every Material color?

Similarly, I didn't include every color hue in the configuration of `md-colors` but instead calculated them.
Maybe not the best approach in the world but it was easy enough.

[The Material Design spec](https://material.io/guidelines/style/color.html#) also mentions these colors and how to derive them. For example `divider-color` would be changed by adding 12% opacity to the text.

That would be an interesting addition.
On the other hand, Materialize itself doesn't use these colors. So if we add f.i. `divider-color` to the css, existing dividers wouldn't change as you would have to add the class to every divider.
(I know there's a `divider` class in Materialize css)

Having said that, `md-colors` was never meant to be a replacement for importing and tweaking the SASS source (what @Kukks mentioned). If you want full control, changing SASS is still the recommended way.
Finding all of these colors in Materialize seems to be a lot of work which is okay but there are some bugs to handle before that. 😃 

Btw. it's very simple to provide your own `md-colors` for your app. [See here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/app-colors.html) for an example on how I changed `nprogress` style to adapt to the app's accent color.

You can put style overrides in such a file and load it in your app. Also, if you'd like to do some bindings for the colors you mentioned, post the file and we can have a look at how to integrate them into `md-colors`. I need to refactor that anyway. 😃

**Comment by joshua1** [comment]
@Thanood Thanks for your response, i will look at the option of importing the scss into my own style file
