### ISSUE TITLE
Validation message issue

### ISSUE THREAD

**Issue by RoMe0s** [aurelia-ui-toolkits/aurelia-materialize-bridge#346]
Messages are not displayed correctly when i use validation from JS. I took the test code here: https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input-aurelia-validation
Sorry for my english :)

![image](https://cloud.githubusercontent.com/assets/14824296/21459893/5b079d4e-c94b-11e6-80a3-c16805bed927.png)

**Comment by Thanood** [comment]
I think you're missing `md-colors`. I need to refactor this, sorry.
Atm it's mandatory, please try this in your main view:
```html
<md-colors></md-colors>
```

If you'd like to customize colors, have a look here:
https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/color-basic-use

**Comment by RoMe0s** [comment]
Yes, this was a mistake, thank you for the help)

**Comment by Thanood** [comment]
I've added a note to the sample. 😃
