### ISSUE TITLE
pickadate is not a function

### ISSUE THREAD

**Issue by RoMe0s** [aurelia-ui-toolkits/aurelia-materialize-bridge#347]
Hello, i need your help again 
`<input md-datepicker.ref="datepicker" element.ref="referenced" md-datepicker="container: body; value.two-way: selectedDate" type="date" placeholder="Placeholder"/>`
and
`export class Profile{
	selectedDate = null;
}`
Error:
![image](https://cloud.githubusercontent.com/assets/14824296/21496285/15b3f426-cc26-11e6-9b0f-514bb701a2af.png)

My init:
`.plugin('aurelia-materialize-bridge', bridge => bridge.useAll())`

And it would work, but for some reason does not want to. Sorry for my english :)

**Comment by Thanood** [comment]
Interesting..
Did you also load `materialize` itself somewhere?
Could you try to reproduce this with a gist? Use this as a base: https://gist.run?id=e8eed34e8bba17f5213535bcdd004a9e

This may also depend on the loader you used (CLI, JSPM, Webpack).

**Comment by RoMe0s** [comment]
My application works with CLI and I changed bundles for materialize in aurelia.json
`{
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "resources": [
              "css/materialize.css"
            ],
            "exports": "Materialize"
          },`

The problem was in jquery in the deps part. 
I left dependent only aurelia-materialize-bridge:
`          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery",
              "hammerjs"
            ],
            "resources": [
              "**/*.{css,html}",
              "index.js"
            ]
          }`

And everything works now. Sorry for my english

**Comment by Thanood** [comment]
I see.. Thanks for mentioning. 😃 
That sounds even familiar..
