### ISSUE TITLE
CLI 0.24.0 aborts tracing (again)

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#353]
See also https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/293#issuecomment-271464934

The trace log:

```
Tracing materialize-css/css/materialize...
Tracing aurelia-materialize-bridge/index...
Tracing aurelia-materialize-bridge/click-counter...
Tracing aurelia-materialize-bridge/breadcrumbs/breadcrumbs...
Tracing aurelia-materialize-bridge/breadcrumbs/breadcrumbs...
Tracing aurelia-materialize-bridge/card/card...
Tracing aurelia-materialize-bridge/card/card...
Tracing aurelia-materialize-bridge/carousel/carousel...
Tracing aurelia-materialize-bridge/carousel/carousel-item...
Tracing aurelia-materialize-bridge/carousel/carousel...
Tracing aurelia-materialize-bridge/checkbox/checkbox...
Tracing aurelia-materialize-bridge/chip/chip...
Writing app-bundle.js...
```

It stops after `chip`..

Maybe there's a regression (from https://github.com/aurelia/cli/pull/369) in the current version of the CLI.

Also ping @darienford, let's continue this here instead of the PR you posted in. 😃

**Comment by Thanood** [comment]
Created a PR:
https://github.com/aurelia/cli/pull/459

**Comment by alpox** [comment]
@Thanood sorry for that, seems there has been a commit in between my creation of the PR and the referenced commit https://github.com/aurelia/cli/pull/369 which i have overseen.

Thanks for the correction with your PR.

**Comment by Thanood** [comment]
@alpox No problem at all.
I was just wondering what had happened. I hope for a test setup in the future so we can add some unit tests. 😃

**Comment by Thanood** [comment]
Fixed in latest CLI release.
