### ISSUE TITLE
[Info] Release 20.6

### ISSUE THREAD

**Issue by djensen47** [aurelia-ui-toolkits/aurelia-materialize-bridge#354]
When you released 20.6 it had a breaking change. It required an upgrade to aurelia-validation 1.0.0-beta-1.0.1

Just wanted to make a note of this. Feel free to close this after reading.

**Comment by Thanood** [comment]
Thank you. 😃 

Actually I've had a tiny discussion with @MaximBalaganskiy who contributed the PR for this update and we came to the conclusion that until aurelia-validation is at a 1.0 release we assume users will update to the most recent version.

However the changelog for 0.20.6 just mentioned "Update validationRenderer to comply with aurelia-validation@1.0.0" and did not point out explicitly that this introduces a breaking change.
I will be more careful in the future and point it out more explicitly should something like this happen again. 😃
