### ISSUE TITLE
mdSelect: Unable to have indeterminate value when using a model

### ISSUE THREAD

**Issue by mttmccb** [aurelia-ui-toolkits/aurelia-materialize-bridge#359]
I've created a [GistRun](https://gist.run/?id=3940de0f4c5a9e959f33e66c9a0fdd03), you'll see that the first item should be selected and the select value is undefined (tried null too) but instead the first item is selected.

**Comment by Thanood** [comment]
Interesting, it works when not disabling the "select your meal" option..
Native HTML select seems to behave the same.

I think the selected value must match the *reference*  of the option value. Hmm but that should work with `null`.

**Comment by Thanood** [comment]
Note to myself: Try with this PR released: https://github.com/aurelia/binding/pull/576

**Comment by Thanood** [comment]
It's released: https://github.com/aurelia/binding/releases/tag/1.2.0
