### ISSUE TITLE
md-chips two-way binding not working

### ISSUE THREAD

**Issue by aviram26** [aurelia-ui-toolkits/aurelia-materialize-bridge#363]
playing with the md-chips gist: https://gist.run/?id=3fc5244efdde52fa68d25220a443359c
- adding/deleting a chip does not effect the displayed list
- changing binding to two-way,  `md-chips="data.two-way: chips;"`, also have no effect

**Comment by Thanood** [comment]
Whoops.. Not sure how I didn't ssee that. 😃 
Thanks. 👍
