### ISSUE TITLE
updateTrigger in md-input

### ISSUE THREAD

**Issue by ApRoland** [aurelia-ui-toolkits/aurelia-materialize-bridge#368]
Can't use updateTrigger in md-input:

ERROR [app-router] Error: The updateTrigger binding behavior can only be applied to two-way bindings on input/select elements.
    at UpdateTriggerBindingBehavior.bind (eval at aurelia-templating-resources/update-trigger-binding-behavior.js (aurelia.bundle.js:1321), <anonymous>:38:13)
    at BindingBehavior.bind (eval at 3 (aurelia.bundle.js:303), <anonymous>:1221:19)
    at Binding.bind (eval at 3 (aurelia.bundle.js:303), <anonymous>:4825:29)
    at Controller.bind (eval at 1 (aurelia.bundle.js:7), <anonymous>:3399:17)
    at View.bind (eval at 1 (aurelia.bundle.js:7), <anonymous>:1443:22)
    at Controller.bind (eval at 1 (aurelia.bundle.js:7), <anonymous>:3421:17)
    at View.bind (eval at 1 (aurelia.bundle.js:7), <anonymous>:1443:22)
    at

By Aurelia documentation (http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-binding-behaviors/4): "Update trigger allows you to override the input events that cause the element's value to be written to the view-model. The default events are change and input."
`<input value.bind="firstName & updateTrigger:'blur'>`
 
My md-input: 
`<md-input md-value.bind="firstName & updateTrigger:'blur'">`

It's not two-way binding issue, but input issue.

Please advise. Thanks in advance.

**Comment by Thanood** [comment]
Sorry for the delay..
I'm not sure how to fix this. The only thing that came to mind would be a custom `updateTrigger` which works on `md-input`..

**Comment by ApRoland** [comment]
Our decision now is a new @bindingBehavior, inheritance from ValidateManuallyBindingBehavior.
Also we can set validateTrigger in ValidationController for more simple cases.
Of course only you can decide - whether to add this enhancement to native or not. If it's possible..

In any case - thanks for the answer!

**Comment by R74NN** [comment]
We are facing the same issue. Could anyone provide a sample of a workaround to be able to use `updateTrigger: 'blur'` on `md-input`, please?

**Comment by frances-brussee** [comment]
Same here. We have some custom controls that we'd like to put 'updateTrigger' on

**Comment by Thanood** [comment]
I'll try something with the hints @ApRoland gave. Probably tomorrow..

**Comment by ApRoland** [comment]
Hi,  if it helps someone, You can change default trigger behavior via ValidationController in view-model:

`this.validator.validateTrigger = validateTrigger.changeOrBlur;`

where validator is NewInstance.of(ValidationController) from aurelia-validation module.

For more complex tasks you can try to inherit ValidateManuallyBindingBehavior (https://github.com/aurelia/validation/blob/master/src/validate-binding-behavior.ts) 
bind and unbind methods.

**Comment by Thanood** [comment]
Thanks, @ApRoland - that's a good workaround for validation. I'm looking for a more general approach because I'm not sure if the update trigger should be limited to validation.

I've tried something along this: ` md-update-trigger="blur"`, which is bound to the input's `value` attribute: `value.bind="mdValue & updateTrigger:mdUpdateTrigger"`

The downside of this approach is that it doesn't work with multiple update-triggers. Input has `change` and `input` by default.

Looking for another solution. I'll probably need to use a custom `bindingBehavior` which resembles the functionality of `updateTrigger` close enough. As far as my understanding of `updateTrigger` goes (which may not be too far), it might probably work with `value` instead of `md-value` but I'd like to prevent renaming.

**Comment by jasoncarreira** [comment]
This seems like a bug with the Aurelia updateTrigger. Here's the code that's throwing this message from the updateTrigger:

```
if (binding.mode !== bindingMode.twoWay) {
      throw new Error(notApplicableMessage);
    }

    // ensure the binding's target observer has been set.
    let targetObserver = binding.observerLocator.getObserver(binding.target, binding.targetProperty);
    if (!targetObserver.handler) {
      throw new Error(notApplicableMessage);
    }
    binding.targetObserver = targetObserver;
```

I'm guessing it's the `if (!targetObserver.handler)` check that's failing, but I don't know enough about Aurelia binding to know why. Anyone have any ideas?

**Comment by MaximBalaganskiy** [comment]
Please reopen if still relevant
