### ISSUE TITLE
aurelia-materialize-bridge@0.23.0 and unmet peer dependency materialize-css@0.98.0

### ISSUE THREAD

**Issue by lebolo** [aurelia-ui-toolkits/aurelia-materialize-bridge#369]
When I try to upgrade to `aurelia-materialize-bridge@0.23.0` and `materialize-css@0.98.0`, npm complains with

```
npm ERR! peer dep missing: materialize-css@^0.97.6, required by aurelia-materialize-bridge@0.23.0
```

I can confirm that `materialize-css@0.98.0` is installed and my Aurelia app runs without problems (so I guess this isn't a big deal =P).

I think it has to do with how [npm/semver treat caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) with "pre-release" versions like `0.X.X`. Specifically, `"materialize-css": "^0.97.6"` does not cover `materialize-css@0.98.0` :crying_cat_face:

**Comment by Thanood** [comment]
Oh.. Thanks for the hint. I guess updating the peer dependency to 0.98.0 would do the trick? It would be recommended with 0.23.0 anyway.

**Comment by lebolo** [comment]
I *think* so =)

**Comment by Thanood** [comment]
This should fix it. 😃
