### ISSUE TITLE
add select inDuration

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#370]
And check for other missing options.

**Comment by Thanood** [comment]
Is that even documented? 😂 
No wonder I missed that option...

**Comment by siabuba121** [comment]
it's done ?

**Comment by Thanood** [comment]
Hi @siabuba121..
I've already asked in Gitter because I was confused about what you actually meant by this.
I didn't find any duration parameters either in the Materialize documentation or in the sources.

Tbh, as there was no answer for a week I just closed this issue.

Could you point me to the docs or source where it's mentioned?

**Comment by Thanood** [comment]
@siabuba121 
I can't see how this would work. I think I'm getting what you mean because the select uses dropdown and dropdown has `inDuration`. But Materialize calls it with static parameters and it's not passing these options in (see [here](https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L610)).

So if this is a feature you're using with vanilla Materialize... How do you do it? 😃

**Comment by MaximBalaganskiy** [comment]
Please review changes in v1
