### ISSUE TITLE
input[number] non-default accent color doesn't work

### ISSUE THREAD

**Issue by priceinjector** [aurelia-ui-toolkits/aurelia-materialize-bridge#371]
non default accent colors doesn't work on input type number. It displays the default teal accent color

md-colors.html should include the following for this to work:

```
md-input .input-field input[type=number]:focus {
    border-bottom: 1px solid ${mdAccentColor};
    box-shadow: 0 1px 0 0 ${mdAccentColor};
  }
  md-input .input-field input[type=number]:focus + label {
    color: ${mdAccentColor};
  }
```

I suppose that time input have the same problem

Thank you

**Comment by Thanood** [comment]
Thanks! 👍 
Number, floating number and time input have the same problem.
