### ISSUE TITLE
label for select from model variable?

### ISSUE THREAD

**Issue by rgwch** [aurelia-ui-toolkits/aurelia-materialize-bridge#373]
I'm trying to create a label for &lt;select&gt; from the model. consider this gist:

https://gist.run/?id=15d9556e1bab270dcd888e4d366c1a39

The first &lt;select&gt; works as expected. In the second &lt;select&gt;, I'm trying to set the Label from the model, similar to the &lt;input&gt; below. But this doesn't work. 

Is it only possible to have the label hard-coded in the HTML?

Thanks for any ideas or hints on this!

**Comment by Thanood** [comment]
@rgwch try:

```html
   <select md-select="label.bind: labelForSelect;">
      <option value="one">one</option>
     <option value="two">${two}</option>
  </select>
```

**Comment by rgwch** [comment]
It works! Thank you very much.
