### ISSUE TITLE
Chips placeholder text doesn't populate when data starts as empty array

### ISSUE THREAD

**Issue by thrillstone** [aurelia-ui-toolkits/aurelia-materialize-bridge#374]
I've modified this gist from the component catalog to illustrate: https://gist.run/?id=09bd910c79091c89d8e2f4b35305951b

The chips input does not contain any placeholder text. The original example from the component catalog does show the placeholder text when chips are present on initialization. Adding a chip and removing it will result in the placeholder text being present when there are no chips present (as expected).

Also, the secondaryPlaceholder option never seems to take effect (I suspect that may be a materialize bug).

**Comment by thrillstone** [comment]
Thanks @Thanood. It does seem like the placeholder issue is rooted in the materialize code.

Also, the secondary placeholder issue is my fault. In the gist, I passed the value as secondaryPlaceholder instead of secondary-placeholder. My mistake.

**Comment by Thanood** [comment]
Seems I always forget about that, too. 😃
