### ISSUE TITLE
CLI with TS: Collapsible not initialized correctly

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#375]
:point_up: [16. Februar 2017 13:10](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=58a596d221d548df2c18a7bf)

repro: https://github.com/Thanood/md-collapsible-issue

If a collapsible panel is set `active` it renders with inline styles featuring a wrong padding value:

```html
<div class="collapsible-body" style="display: block; padding-top: 0px; margin-top: 0px; padding-bottom: 0px; margin-bottom: 0px;"></div>
```

The element should not have any inline styles.
It looks as if the expand animation was cancelled.

This only happens with a TypeScript project created by Aurelia CLI. A js project works as expected.

A workaround:

```ts
import {inject, TaskQueue} from 'aurelia-framework';
declare var $;

@inject(TaskQueue)
export class App {
  activeHeader: HTMLDivElement;
  message = 'Hello World!';
  taskQueue: TaskQueue;

  constructor(tq) {
    this.taskQueue = tq;
  }

  attached() {
    this.taskQueue.queueTask(() => {
      $(this.activeHeader).trigger('click');
    });
  }
}
```

**Comment by MaximBalaganskiy** [comment]
Not observed when using collapsible open method
