### ISSUE TITLE
md-chips not working as expected

### ISSUE THREAD

**Issue by mvelt** [aurelia-ui-toolkits/aurelia-materialize-bridge#377]
I am trying to get md-chips to work in my project. 

When I add data to the model (i.e. chips) using javascript, the md-chips element does not reflect the changes. 

I made a gist that shows what I mean: 
[https://gist.run/?id=a52672a1ecccd3f7332315f78cef8dec](https://gist.run/?id=a52672a1ecccd3f7332315f78cef8dec)

It seems the two-way binding is not working correctly, or did I miss something?

I found this previous issue: [https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/363](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/363), which also addresses the two-way binding of md-chips. I made sure I used version 0.24.0 where that issue was addressed.

**Comment by Thanood** [comment]
Thanks for the gist @mvelt! 😃 
There is no direct way to refresh Materialize chips. I'll try something, though..

**Comment by Thanood** [comment]
This seems to work but I'm not sure about performance/memory leaks etc. because it's reinitializing the chips plugin.

https://gist.run/?id=88627b078c726f0918fd43571185d52e

I'm leaving this here to remind me to add it to the bridge.

**Comment by mvelt** [comment]
Hi @Thanood, thanks for your quick reply. The workaround is good enough for me at the moment.

**Comment by MaximBalaganskiy** [comment]
Implemented. Checkout the latest demo http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/chip/editor
