### ISSUE TITLE
input-textarea auto resize fix [documentaion fix]

### ISSUE THREAD

**Issue by avrahamcool** [aurelia-ui-toolkits/aurelia-materialize-bridge#383]
the reason that the [demo](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input-textarea) does not work is because you applyed `aurelia-app` twice.
that causes the hidden div to be in the scope of the `aurelia-app` (not as intended).
```
<body aurelia-app="main"> <!-- HERE - SHOULD BE REMOVED -->
    <div class="hiddendiv"></div>
    <div aurelia-app="main"> <!-- HERE -->
      <h1>Loading...</h1>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.6/system.js"></script>
      <script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js"></script>
      <script>
        System.import('aurelia-bootstrapper');
      </script>
    </div>
  </body>
```

[Here](https://gist.run/?id=3ed9f44a041492be0afed794ef1a9d97) is the updated gist.

**Comment by Thanood** [comment]
Oh, wow.. How yould I not see this? 😂 

Thanks a lot, @avrahamcool! Original gist is updated now.
