### ISSUE TITLE
Double Title Printed on md-card

### ISSUE THREAD

**Issue by willypt** [aurelia-ui-toolkits/aurelia-materialize-bridge#384]
```html
<md-card md-title="Card title" md-size.bind="size" md-reveal="true">
	<div>
    	I am a very simple card. I am good at containing small bits of
        information. I am convenient because I require little markup to
        use effectively.
    </div>
    <div slot="reveal-text">
    	asdasds
    </div>
</md-card>
```
Having this code yields into double card-title if `<md-card/>` has `md-reveal="true"`  but doesn't have `md-image` set
![image](https://cloud.githubusercontent.com/assets/1708055/23947006/5bdfcaee-09af-11e7-8b23-89c967385451.png)

**Comment by willypt** [comment]
@Thanood Yes, you did. :laughing:. I've created the PR, please review it.

**Comment by Thanood** [comment]
Okay. 😃 
I will check it tomorrow. A lot to do today.

**Comment by willypt** [comment]
Yes, please take your time. :-D
As I don't have any access to edit the gist for documentation preview, I attached the result and the code I used to test
![image](https://cloud.githubusercontent.com/assets/1708055/24026799/408942a0-0af6-11e7-93d1-b354c2a33664.png)

```html
<div class="row">
    <md-card class="col s3" md-title="Card title" md-size.bind="size" md-reveal="true">
      <div>
        This card has reveal true and no image
      </div>
      <div slot="reveal-text">
        Reveal Text
      </div>
    </md-card>
    <md-card class="col s3" md-title="Card title" md-size.bind="size" md-reveal="true" md-image="http://aurelia-ui-toolkits.github.io/demo-materialize/images/card-sample-1.jpg">
      <div>
        This card has reveal true and image
      </div>
      <div slot="reveal-text">
        Reveal Text
      </div>
    </md-card>
    <md-card class="col s3" md-title="Card title" md-size.bind="size" md-image="http://aurelia-ui-toolkits.github.io/demo-materialize/images/card-sample-1.jpg">
      <div>
        This card has reveal false and image.
      </div>
    </md-card>
    <md-card class="col s3" md-title="Card title" md-size.bind="size">
      <div>
        This is simple card
      </div>
    </md-card>
  </div>
```

**Comment by Thanood** [comment]
Thanks. 👍 
Just for info: it's okay if you fork the gist and link it here I can fork it again or copy it over.

But I can use your example code as well. 😃

**Comment by Thanood** [comment]
I've added your sample to the catalog as is.
Atm it will show double titles, which will go away once I update the catalog app.

Thanks again. 👍
