### ISSUE TITLE
opening modal from `attached` event isn't working

### ISSUE THREAD

**Issue by avrahamcool** [aurelia-ui-toolkits/aurelia-materialize-bridge#386]
I have a component that includes a `modal`.
this component is not always visible (I'm using the `if.bind` on it).
I want the contained modal to open when the component comes into view,
so in the `attached` event of the component I put `this.modal.open()` (the modal is bounded to a variable named `modal`).

the component comes into view, and the `this.modal` variable is correctly initialized, but the modal do **NOT** show.

if I put the `this.modal.open()` statement in a `setTimeout` (even with 0 ms) - it works.
when I hide the component and reshow it, it also works.

I created a [gist ](https://gist.run/?id=ffcc9c205465193c61a6579335c2c098)to demonstrate this issue.
I'm not sure what causes this behaveiour.

**Comment by Thanood** [comment]
Maybe this is related? https://github.com/Dogfalo/materialize/issues/4330
At least it behaves the same way..

**Comment by Thanood** [comment]
So, do you set a timeout now?
Btw. I don't think we can work around this as there is no separate "init modal" in Materialize.

**Comment by avrahamcool** [comment]
yes, I'm using the `setTimeout(...,0)` trick.
but I`d love to get rid of it for a better solution.

**Comment by Thanood** [comment]
Maybe slightly more elegant.. Using the TaskQueue. 😃 

```js
import {inject, TaskQueue} from 'aurelia-framework';

@inject(TaskQueue)
export class Working {
  constructor(tq) {
    this.tq = tq;
  }
  
  attached()
  {
    this.tq.queueTask(() => this.modal.open());
  }
}
```

Gist:
https://gist.run/?id=353f832f996ea5fe5f81a9018d064e1d

**Comment by avrahamcool** [comment]
thanks.
