### ISSUE TITLE
Datepicker input labels disappear

### ISSUE THREAD

**Issue by daneps** [aurelia-ui-toolkits/aurelia-materialize-bridge#388]
When using datepicker, I can't see a way to have the labels appear as they do for md-label.

**Comment by Thanood** [comment]
Do you mean something like this?
https://gist.run/?id=d00ab12cd283a0e6d6f7ff2f91495a69

You can't click the label to activate the picker, though. Maybe we can find a workaround for that.

**Comment by daneps** [comment]
That's great, thanks!
It doesn't work in Firefox 52.0 on Windows, the label and input overlap.
Also having the label separate means you have to manually generate ids and
link them between the label and the input.

**Comment by Thanood** [comment]
We can refine the idea, though. :)

**Comment by Thanood** [comment]
Uhm, interesting.. I didn't notice but the ID I've used is actually pretty useless.
Which means it works without the ID.

**Comment by MaximBalaganskiy** [comment]
@daneps http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/recipes-datepicker-label
something like this?

**Comment by daneps** [comment]
beautiful!

**Comment by Thanood** [comment]
Ah, that hurts.. Sorry, I probably should have known that one. 😃
