### ISSUE TITLE
create the materialize-demo app hosted at GitHub (gh-pages)

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-materialize-bridge#39]
This task has to wait on new jspm needed by [plugin builder](https://github.com/aurelia-ui-toolkits/plugin-builder)

**Comment by Thanood** [comment]
:point_up: [23. Februar 2016 18:21](https://gitter.im/jspm/jspm?at=56cc9534e0e309b435d19a7d)

> I have to call it a day here, will aim to release tomorrow

:smile:
