### ISSUE TITLE
md-tabs don't work as expected

### ISSUE THREAD

**Issue by avrahamcool** [aurelia-ui-toolkits/aurelia-materialize-bridge#392]
[the original gist is runing against 0.20.2](https://gist.run/?id=6a238e618806289a3800dd4560cf1959)
[this gist is running against 0.25.0](
https://gist.run/?id=73bead0298961fe04d94444adbd30ec5)

**Both** dont work as expected
clicking on the button should select the second tab, but this is not working (and no error in the console)

navigating between tabs works, but the indicator dont move to the selected tab.

**Comment by Thanood** [comment]
Hmm, I thought I had this fixed..

**Comment by Thanood** [comment]
Of course!
I had to rename the tab IDs to not conflict with tabs used in the catalog app and I didn't rename the reference in the gist.

Thanks for mentioning this! 👍 
Fixed now.
