### ISSUE TITLE
Button Groups

### ISSUE THREAD

**Issue by dmason511** [aurelia-ui-toolkits/aurelia-materialize-bridge#394]
I am in the need of a button group and toggle functions like the Angular md-button-toggle
 and md-button-toggle-group. I see you have button groups for aurelia-kendoui-bridge but not for aurelia-materialize-bridge.  Is this in the works?
Thanks.

**Comment by Thanood** [comment]
This project currently only mirrors components which are already present in materialize (like the kendo bridge but kendo has button groups). But maybe it's not hard to do..

**Comment by dmason511** [comment]
It would be greatly appreciated.

**Comment by Thanood** [comment]
Maybe something like this:
https://gist.run/?id=b44037b650c5190f002a52d1295bfbfe
