### ISSUE TITLE
How to translate md-select label with i18n?

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-materialize-bridge#398]
I dont know how to translate the md-select label
Neither of them
```html
<select md-select="label: ${i18n.tr('text')}">
```
```html
<select tr="[md-select-label]text">
```
are working. Is there any working solution or I'm missing something?

**Comment by Thanood** [comment]
That's an interesting question since string interpolation won't work in custom attribute properties.. I think it is by design but unfortunately, I've lost the link.
I guess this would be done in code.. I'll try to come up with an example.

**Comment by Thanood** [comment]
https://gist.run/?id=19da3700c486ed6692fb1c11b00e8ceb

Please note that **this won't work** because the label is never updated..
Thus I'm labelling this issue as a bug since I'd like to find a solution.

**Comment by mreiche** [comment]
What do you means that this won't work? Your Gist works as expected.

**Comment by Thanood** [comment]
It does? But the placeholder label was never updated when I tested it.

**Comment by mreiche** [comment]
It works in my browser Chrome 57.0.2987.133 (64-bit) on MacOSX.

**Comment by Thanood** [comment]
Interesting.. I'll check it again when I come home.

**Comment by mreiche** [comment]
I appreciate that.

**Comment by Thanood** [comment]
With Chrome 57.0.2987.133 (64-bit) on Windows, it doesn't work.
The string below the text field is translated but not the select label. It always stays at "placeholder" for me.

**Comment by Thanood** [comment]
This gist uses a patched version of `md-select` which is able to change its label (even on my browser 😃 ):
https://gist.run/?id=19da3700c486ed6692fb1c11b00e8ceb

I'll prepare the same for the bridge.

**Comment by Thanood** [comment]
It's in 0.26.0 😃

**Comment by SvetlozarValchev** [comment]
Is there a way to do this without writing custom modified versions of the md-select?

**Comment by MaximBalaganskiy** [comment]
Have you tried aurelia-i18n plugin?

`md-select="label.bind: 'translation' | t"`
