### ISSUE TITLE
md-chip close event

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-materialize-bridge#399]
How to delegate the 'close' event in a md-chip?
The basic example with a single ```<md-chip>``` doesn't provide an example.
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/chip-basic-use

**Comment by Thanood** [comment]
Well, it doesn't.. 😃 
But it should raise the event. Good catch!

**Comment by mreiche** [comment]
My colleague wrote an ugly workarround
```html
<md-chip click.delegate="chipClicked($event)">
```

```javascript
chipClicked(event) {
    if(event.target.innerText === 'close'){
        // Propably closed
    }
}
```

**Comment by Thanood** [comment]
Not sure why, but I need to use `trigger` to receive the event. The `CstomEvent` which is fired, is configured to bubble.
