### ISSUE TITLE
Cannot focus() md-input programatically

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-materialize-bridge#400]
I cant focus my md-input element like
```html
<md-input ref="inputElement">
```

```javascript
doSomething() {
   // Does actual nothing
    this.inputElement.focus();
}
```

**Comment by Thanood** [comment]
That would be `view-model.ref="inputElement"` but that only fires the `focus()` event:
https://gist.run/?id=33129796dff66080f16f0850a7903b20

I'll add it in the next "round" of changes (which is maybe tomorrow but I'm not sure).
