### ISSUE TITLE
md-char-counter isn't applied to textarea elements

### ISSUE THREAD

**Issue by dwarry** [aurelia-ui-toolkits/aurelia-materialize-bridge#404]
Given an element such as 

```html
<md-input md-label="put some text here" md-value.bind="textAreaValue" md-text-area="true" md-char-counter="length: 200;"></md-input>
```

I'd expect the character count to be rendered, but it is not. There's a gist at https://gist.github.com/dwarry/95b5f201c8adb0765dafa011b55c2275 .

**Comment by Thanood** [comment]
I've merged your PR.. Thanks again. 😃
