### ISSUE TITLE
improve cards

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#41]
Just a note to myself as I find this not really obvious to find:
http://materializecss.com/helpers.html

Add ```hoverable``` property to cards (as it is quote: "meant for use on cards").
Anyway, check possibility to implement as a separate attribute.

**Comment by Thanood** [comment]
Setting ```display: inline-block;``` on cards enables to just use the ```hoverable``` class on demand. It also enabled theming the cards. :smile:

**Comment by adriatic** [comment]
I **love** your systematic approach dealing with any issues!!

**Comment by Thanood** [comment]
That's what happens when I get feedback from actual users of this bridge. :smile: 
vdangwal wanted to use hoverable but couldn't because it had no height (can't apply box-shadow to things without a height).

**Comment by adriatic** [comment]
Yes, I saw that conversation - and was bitten by that bug more than once (in different scenarios)
