### ISSUE TITLE
SideNav items shift on hover for Desktop size

### ISSUE THREAD

**Issue by djensen47** [aurelia-ui-toolkits/aurelia-materialize-bridge#425]
Known browsers affected: Chrome, Firefox
Known browsers not affected: Edge

1. Increase the size of your browser to "desktop" size or larger
2. Load a page with a SideNav
3. Hover over a elements

Expected behavior:
Elements highlight and don't shift.

Actual behavior:
The elements shift about one pixel down as you hover over them.

![side-nav-bug](https://cloud.githubusercontent.com/assets/527865/26186092/eb167ad0-3b43-11e7-92df-97cbe09749eb.gif)

**Comment by Thanood** [comment]
This seems to be because of setting `display: block;` in a catalog-specific stylesheet.
Is that correct or does that happen with "non-catalog" apps, too? 😃 

Anyway, I will fix that. Thanks. 👍
