### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#427]
Hi. So I copied an older project to start a new one using Aurelia cli. (Don't know why I do this it always fails :)

Anyway after correcting things I am having issue with aurelia-materialize-bridge.

I have updated to
"aurelia-cli": "^0.24.0",
"materialize-css": "^0.98.2",
"aurelia-materialize-bridge": "^0.28.0",

the project starts but when going to the page I get the error

vendor-bundle.js:25663 GET http://127.0.0.1:9000/scripts/materialize-bundle.html 404 (Not Found)
vendor-bundle.js:1395 Unhandled rejection Error: src/../scripts/materialize-bundle.html HTTP status: 404
    at XMLHttpRequest.xhr.onreadystatechange (http://127.0.0.1:9000/scripts/vendor-bundle.js:25649:31)
From previous event:
    at DefaultLoader._import (http://127.0.0.1:9000/scripts/vendor-bundle.js:14203:14)

...

I have gone through the installation instructs again and can't see the I am going wrong.
Any idea what could cause this ?

thanks

**Comment by Thanood** [comment]
Which version of aurelia-cli is actually installed?
I don't remember the exact version right now (I'll look it up) but there are two versions which would not bundle everything if it's referenced with `*.{html,js,css}` in `aurelia.json`.

That's usually the cause of errors like `vendor-bundle.js:25663 GET http://127.0.0.1:9000/scripts/materialize-bundle.html 404 (Not Found)`.

**Comment by Thanood** [comment]
It happens with aurelia-cli versions before 0.21.0 and with 0.24.0..

**Comment by glennpierce** [comment]
0.24.0

However, I did add the files as a long list as per the instructions.

I just upgraded to 0.26 and things are fine.

Thanks

**Comment by Thanood** [comment]
> However, I did add the files as a long list as per the instructions.

Maybe I've missed some files in the instructions..
I will check that. Thanks for pointing that out. 👍

**Comment by glennpierce** [comment]
I spoke too soon about it being fine. 
I was still getting undefined errors. So I commented the navbar and sidebar I had and now just see the error

deep-extend.ts:148 Uncaught ReferenceError: Materialize is not defined
    at MdInputUpdateService.materializeUpdate (materialize-bundle.js:13650)
    at TaskQueue.flushTaskQueue (deep-extend.ts:148)
    at deep-extend.ts:148
    at handleFlushTimer (deep-extend.ts:148)

**Comment by Thanood** [comment]
Hmm.. Can you compare to this repo? 
https://github.com/Thanood/md-todo

**Comment by glennpierce** [comment]
working.

I must have forgot to run

./node_modules/.bin/r.js -o rbuild.js

when I was trying newer versions.

Thanks

**Comment by Thanood** [comment]
Of you knew how often I forget that. ;-)

**Comment by MaximBalaganskiy** [comment]
See updated CLI documentation
