### ISSUE TITLE
[Question] MDC?

### ISSUE THREAD

**Issue by djensen47** [aurelia-ui-toolkits/aurelia-materialize-bridge#429]
@Thanood Sorry to use issues to contact you but I don't have any other means to reach you.

I saw that you contributed a framework example for Aurelia for the material-components/material-components-web project. Is there any change that you'll start an aurelia-mdc-bridge project? Something fully featured like aurelia-materialize-bridge?

**Comment by Thanood** [comment]
@djensen47 No problem at all. 😃 

When I have some more time to commit to another project I'm certainly interested in doing an MDC bridge. I just don't have the time at the moment.

MDC is a very interesting project. If someone (maybe you 😏 ) wants to give it a shot I can help with it.

**Comment by djensen47** [comment]
I think I might do that. @arabsight has done a good job with arabsight/aurelia-mdc-plugin but the primary purpose of that repo is to upgrade components as opposed to a bridge.

I'll let you know if/when I set something up.

**Comment by Thanood** [comment]
@djensen47 I just found this: https://github.com/Ullfis/aurelia-mdc-bridge - seems to be very fresh but in case you'd still like to do an MDC bridge, maybe join forces. 😃

**Comment by djensen47** [comment]
Very cool. I'll have to check it out. I probably won't have much time for contributions until the Winter but I'll definitely be tracking this.
