### ISSUE TITLE
MdSelect label color does not respect focus

### ISSUE THREAD

**Issue by carusology** [aurelia-ui-toolkits/aurelia-materialize-bridge#437]
**Background**

Using any `<select>` element, utilize the `md-select` attribute and specify a `label` property. For example:

```html
<select md-select="label: My Label" value.two-way="someValue">
  <option value="foo">Foo</option>
  <option value="bar">Bar</option>
</select>
```

[Here is a gist](https://gist.run/?id=54e4b0d19c1da1786d9b5daff87ce11f) where the label is always grey.

**Expected Behavior**
When the `<select>` element is focused and the `<option>` elements are visible in the `<select>` element, the label is the "accent color" to show that the element has focus. When the `<select>` element is no longer focused / blurred, the label becomes grey. 

**Actual Behavior**
The label is either always the "accent color" or always grey. I can't seem to get consistent behavior. For example, it is consistently teal when I go to [this page](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select-basic-use), and grey when I go to [the gist that you visit](https://gist.run/?id=1ac1e348fa4e362183d5706aaa01fcf7) when you click "Try This."

**Comment by Thanood** [comment]
Good catch! It worked before the wrapper was added. I'll check that. 👍
