### ISSUE TITLE
An example of RTL support

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia-ui-toolkits/aurelia-materialize-bridge#441]
Hi,

Since Dogfalo hesitates to support RTL (right to left writing such as Arabic), Materialize and AMB do not support RTL. 

The following gist.run is a very simple example that illustrates how to change directions of writing using materialize_rtl.css. 

https://gist.run/?id=3526eacc3ed1e5a7f6b4388099ee177e

*Toggle direction* button should change the direction of writing in the gist.run. Unfortunately it does *not* run because of "require is not a function" on Gist.run, though it works in my app. (Does anyone fix it?)

Here is the core part of the example.

```
    @observable direction;   // rtl or ltr
    directionChanged() {    
        if (this.direction === 'rtl') {
            require('./materialize_rtl.css');
        } else {
            require('materialize-css/bin/materialize.css');
        }
        document.getElementsByTagName('body')[0].setAttribute('dir', this.direction);
    }
```

Get materialize_rtl.css from [this repository by @vahid-almasi](https://github.com/vahid-almasi/materialize-rtl/blob/master/materialize_rtl.css). 

Comment out *direction* for *body*, since we use *dir* attribute of *body*.

```
/*body {
	direction: rtl;
}*/

.input-field label {
	right: 0.75rem;
...
```

The example also illustrates how to combine with aurelia-i18n. Remove comments in locale-manager.js and do *this.localeManager.locale = 'ar'* for Arabic.  (You need to setup aurelia-i18n in main.js and prepare locale files)

I hope this helps somebody who needs RTL support.

**Comment by HIRANO-Satoshi** [comment]
Note that SideNav fails with this approach. The following example does not work, because md-edge is not dynamic. 

```
  <md-sidenav view-model.ref="sideNav"
         md-edge = ${localeManager.direction === 'rtl' ? 'right' : 'left'}"
         md-close-on-click="true">
```

**Comment by Thanood** [comment]
@HIRANO-Satoshi Cool, thanks! 😃 

In theory it should work with Aurelia loader. I can't demonstrate it in the gist right now because `aurelia-pal` is missing in the bundles.

Like this:

```javascript
import { bindable, computedFrom, inject, observable, Aurelia, Loader } from 'aurelia-framework';
import { DOM } from 'aurelia-pal';

@inject('Loader')
export class LocaleManager {
  constructor(loader) {
    this.loader = loader;
  }

    @observable direction;   // rtl or ltr
    directionChanged() {    
        if (this.direction === 'rtl') {
            this.loadStyle('./materialize_rtl.css');
        } else {
            this.loadStyle('materialize-css/bin/materialize.css');
        }
        document.getElementsByTagName('body')[0].setAttribute('dir', this.direction);
    }
    
    loadStyle(path) {
      this.loader.loadText(path).then(css => {
        DOM.injectStyles(css);
      });
    }
}
```

I can add ths to the bridge's contribution/recipes section if you like.

**Comment by HIRANO-Satoshi** [comment]
Thanks, but there must be other problems.

*row col* seems incorrect.

materialize_rtl.css has

```
.row .col {
	float: right;
}
```

while materialize.css has

```
.row .col {
	float: left;
        ...
}
```

After switching from rtl to ltr, *float: right* remains.  (I'm not an expert of CSS and HTML.)

**Comment by Thanood** [comment]
It's switching correctly for me in the gist. I've used `<require from="./materialize_rtl.css"></require>` instead of clicking the button to try that.

**Comment by MaximBalaganskiy** [comment]
Please reopen if still needed
