### ISSUE TITLE
materialize-css v0.99.0 removed files from NPM module

### ISSUE THREAD

**Issue by sabinrimni** [aurelia-ui-toolkits/aurelia-materialize-bridge#442]
This is related to this [issue](https://github.com/Dogfalo/materialize/issues/4871) over on the materialize-css repo.

Basically in version 0.99.0 some files were removed from the NPM module (apparently related to their internal documentation) and the `rbuild.js` file from [aurelia-materialize-bridge](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html) doc doesn't work any more.

Here is my fix for this. I just removed the unneeded files from the `rbuild.js` file.

```
({
  baseUrl: 'node_modules/materialize-css/js',
  name: '../../../materialize-css',
  out: 'node_modules/materialize-css/dist/js/materialize.amd.js',
  paths: {
    'jquery': '../../jquery/dist/jquery',
    'initial': 'initial',
    'global': 'global',
    'animation': 'animation',
    'buttons': 'buttons',
    'cards': 'cards',
    'carousel': 'carousel',
    'character_counter': 'character_counter',
    'chips': 'chips',
    'collapsible': 'collapsible',
    'dropdown': 'dropdown',
    'forms': 'forms',
    'hammerjs': 'hammer.min',
    'jquery.easing': 'jquery.easing.1.4',
    'jquery.hammer': 'jquery.hammer',
    'modal': 'modal',
    'materialbox': 'materialbox',
    'parallax': 'parallax',
    'picker': 'date_picker/picker',
    'picker.date': 'date_picker/picker.date',
    'pushpin': 'pushpin',
    'scrollFire': 'scrollFire',
    'scrollspy': 'scrollspy',
    'sideNav': 'sideNav',
    'slider': 'slider',
    'tabs': 'tabs',
    'toasts': 'toasts',
    'tooltip': 'tooltip',
    'transitions': 'transitions',
    'velocity': 'velocity.min',
    'waves': 'waves'
  },
  shim: {
    'jquery': { exports: '$' },
    'animation': ['jquery'],
    'buttons': ['jquery'],
    'cards': ['jquery'],
    'carousel': ['jquery'],
    'character_counter': ['jquery'],
    'chips': ['jquery'],
    'collapsible': ['jquery'],
    'dropdown': ['jquery'],
    'forms': ['jquery', 'global'],
    'global': { deps: ['jquery'], exports: 'Materialize' },
    'hammerjs': {},
    'jquery.easing': ['jquery'],
    'jquery.hammer': { deps: ['jquery', 'hammerjs', 'waves'] },
    'modal': ['jquery'],
    'materialbox': ['jquery'],
    'parallax': ['jquery'],
    'pushpin': ['jquery'],
    'scrollFire': ['jquery', 'global'],
    'scrollspy': ['jquery'],
    'sideNav': ['jquery'],
    'slider': ['jquery'],
    'tabs': ['jquery'],
    'toasts': {
      deps: ['global', 'hammerjs', 'velocity'], init: function(Materialize, Hammer, Vel) {
        window.Hammer = Hammer;
        window.Vel = Vel;
      }
    },
    'tooltip': ['jquery'],
    'transitions': ['jquery', 'scrollFire'],
    'waves': { exports: 'Waves' }
  },
  optimize: 'none',
  exclude: ['jquery'],
  include: [
    'initial',
    'global',
    'animation',
    'buttons',
    'cards',
    'carousel',
    'character_counter',
    'chips',
    'collapsible',
    'dropdown',
    'forms',
    'hammerjs',
    'jquery.easing',
    'jquery.hammer',
    'modal',
    'materialbox',
    'parallax',
    'picker',
    'picker.date',
    'pushpin',
    'scrollFire',
    'scrollspy',
    'sideNav',
    'slider',
    'tabs',
    'toasts',
    'tooltip',
    'transitions',
    'velocity',
    'waves'
  ]
});
```

**Comment by Thanood** [comment]
Thanks! 😃

**Comment by sabinrimni** [comment]
I should also mention that the `materialize-css.js` file should exclude those files like so:
`//
// https://github.com/Dogfalo/materialize/issues/634#issuecomment-113213629
//  and
// https://github.com/noodny/materializecss-amd/blob/master/config.js
//
//
require([
  'global',
  'initial',
  'animation',
  'buttons',
  'cards',
  'carousel',
  'character_counter',
  'chips',
  'collapsible',
  'dropdown',
  'forms',
  'hammerjs',
  'jquery.easing',
  'jquery.hammer',
  'modal',
  'materialbox',
  'parallax',
  'picker',
  'picker.date',
  'pushpin',
  'scrollFire',
  'scrollspy',
  'sideNav',
  'slider',
  'tabs',
  'toasts',
  'tooltip',
  'transitions',
  'velocity'
],
  function(Materialize) {
    return Materialize;
  }
);`

**Comment by Thanood** [comment]
@sabinrimni That works without `tapTarget`?

**Comment by Thanood** [comment]
Fixed the build scripts but I kept `tapTarget`. 😃 
I'm still curious if it works without.

**Comment by sabinrimni** [comment]
Yeah, I don't think that was deleted intentionally. For me it built without it and ran the application...but it might have consequences further down the line 😄

**Comment by Thanood** [comment]
Alright, thanks. 😃 
I've tested the AMD script now and it works. So I'm closing this issue.
