### ISSUE TITLE
No way to add asterisk to required inputs

### ISSUE THREAD

**Issue by wjbarber3** [aurelia-ui-toolkits/aurelia-materialize-bridge#443]
Is there no property that can be added to show an asterisk for required fields?  Been struggling with this for a while now.

**Comment by Thanood** [comment]
How do you mean exactly? You can always add an asterisk to the label of an input, for example.
But I don't think that's what you mean. 😃

**Comment by wjbarber3** [comment]
Thanks for the response!  And I definitely wasn't clear enough.  I am aware that I could just add the asterisk in the 'md-label' property but then I would have no way of styling it.  I would like to style it differently than the label itself.  That is all I'm really going for, any idea what the best route is for that?

**Comment by wjbarber3** [comment]
Good grief.  Never mind, just asking the question helped me nail it down.  For anyone who stumbles here, just add a class to md-input and then use that class to target the label and add the asterisk in a pseudo element.  Thanks for your time and work!

**Comment by Thanood** [comment]
> just asking the question helped me nail it down

A thing that happens to me all the time! 😂

**Comment by Thanood** [comment]
For anyone who stumbling here, an example:

```css
md-input label:before {
  content: '*';
  color: red;
  font-weight: bold;
}
```
