### ISSUE TITLE
Problem when bundling the bridge with materialize-css

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-materialize-bridge#444]
I'm not sure, if this problem is new since materialize-css 0.99, but when I try to bundle the bridge with materialize-css like

```javascript
const materialComponents = [
	'materialize-css',
	"[aurelia-materialize-bridge]",
	"[aurelia-materialize-bridge/**/*.js]",
	"aurelia-materialize-bridge/**/*.css!text",
	"aurelia-materialize-bridge/**/*.html!text"
];
```

I get the following error when loading ``materialize.min.js``

```
Uncaught (in promise) Error: (SystemJS) Cannot set property 'Picker' of undefined
	TypeError: Cannot set property 'Picker' of undefined
```

```javascript
"function" == typeof define && define.amd ? define("picker", ["jquery"], a) : "object" == typeof exports ? module.exports = a(require("jquery")) : this.Picker = a(b)
```

Any ideas?

**Comment by mreiche** [comment]
I think I got the answer here: https://github.com/Dogfalo/materialize/issues/3146

**Comment by Thanood** [comment]
Did you use an override [like descripbed here](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/jspm.html)?

It works at least for unbundled apps and for bundled apps using v0.98.0 (current bridge catalog).

**Comment by mreiche** [comment]
Yes I'm using the overrides, but thats not the reason. I fixed that by removing ``"use strict";`` from beginning of the bundle as described in https://github.com/Dogfalo/materialize/issues/3146

It seems that this is a bug addressed to SystemJS. Maybe we should mentioned that in the bundling guide.

**Comment by Thanood** [comment]
Yes, I agree. 👍 
And therefore I'll reopen the issue. 😃

**Comment by mreiche** [comment]
I wonder that there's still my open PR: https://github.com/Thanood/materialize-bridge-docs/pull/1
Anyway. I've slightly updated the documentation for "on bundling". Added a note for jQuery bundling AND a workarround for this issue here.

**Comment by Thanood** [comment]
Oh, you're right of course. We settled the dependency issues a few days ago, I think. 😃 
Thanks for the update, I'll merge it when I come home.

**Comment by Thanood** [comment]
I've merged the PR but somehow the GitBook is not linked to the repo anymore.. 😕 
Anyway, the description is in now.

**Comment by mreiche** [comment]
The SystemJS/JSPM developer answered in the references issue:

> Right, this is exactly cause by the 'use strict' statement in the npm:aurelia-materialize-bridge@0.29.0/common/polyfills.js file. This is something that could be fixed through SystemJS builder potentially, but it might be quicker to just ensure that isn't present in that file.

**Comment by Thanood** [comment]
That's unfortunate.. It's generated by (gulp-)babel and `use strict` is everywhere.. 😕 
Maybe there's a setting which can prevent that.

**Comment by mreiche** [comment]
Maybe you should tell that @guybedford directly here https://github.com/systemjs/systemjs/issues/75

But I'm not sure if babel is part of SystemJS or not.

**Comment by Thanood** [comment]
It's ... well, an optional part, but not directly. The thing is, SystemJS will probably have to load libs generated by babel from time to time. I wonder what others do different.

THanks for the link, I'm looking for some more babel options.

**Comment by Thanood** [comment]
Maybe it helps when I switch back to `amd` for the [`directories` field](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L33)..

**Comment by Thanood** [comment]
I don't believe it.. 😂 
[There actually is a plugin for that!](https://github.com/genify/babel-plugin-transform-remove-strict-mode)

I'll add it into the build process. The output looks okay in my tests, the only `'use strict'` in inside the `System.register` call.

**Comment by Thanood** [comment]
The next build should not contain double `"use strict"` anymore.
