### ISSUE TITLE
Accent color is not taken for input controls in 0.29.0

### ISSUE THREAD

**Issue by priceinjector** [aurelia-ui-toolkits/aurelia-materialize-bridge#449]
Steps to reproduce:
In official catalog select non default accent color from the color switcher:
 [ http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input-placeholder]( http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/input-placeholder)

See that when the input control is focused it is still teal color and not the one you have chosen in the colors switcher

This happens to many other forms controls

**Comment by Thanood** [comment]
Hmm, they must have changed the css. I wonder how I missed that.
Thanks! 👍

**Comment by Thanood** [comment]
Input and textfield borders, labels and prefix icons added.
I didn't find more today but I will keep looking. 😃

**Comment by Thanood** [comment]
I think I got them all now.
