### ISSUE TITLE
Remove dropdown-fix? (useDropdownFix)

### ISSUE THREAD

**Issue by vulvulune** [aurelia-ui-toolkits/aurelia-materialize-bridge#458]
Hello,

When I added the stopPropagation property to dropdown, I discover the dropdown-fix.js file. And the .useDropdownFix() is commented in the main.js file.

I think it's an artefact with an old version of materialize. Can we delete it safely to reduce the size of the library?

If yes, I can provide a PR with the fix removed.

**Comment by Thanood** [comment]
I suppose we can remove that, yes..
