### ISSUE TITLE
track for 1.0

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#465]
- [x] button
- [x] navbar
- [x] sidenav
- [x] tabs
- [x] checkbox
- [x] switch
- [x] tooltip
- [x] select
- [x] validation
- [x] colors
- [x] dropdown
- [x] badge
- [x] toast
- [x] box
- [x] card
- [x] well
- [x] waves
- [x] tap-target
- [x] slider
- [x] scrollspy
- [x] input
- [x] char-counter
- [x] ~~scrollfire~~
- [x] range
- [x] breadcrumbs
- [x] radio
- [x] pushpin
- [x] progress
- [x] parallax
- [x] pagination
- [x] carousel
- [x] chip
- [x] collapsible
- [x] collection
- [x] common
- [x] fab
- [x] file
- [x] footer
- [x] modal
- [x] ~~transitions~~
- [x] datepicker
- [x] timepicker
- [x] autocomplete

**Comment by kayle** [comment]
Any wild estimates on when there will be a branch targeting Materialize 1.0? When they announce a v1.0-beta release?

I happened to try the v1.0 alpha of materialize to see if it would help with some build issues (it did), but there's a lot of breaking changes with this package.

To start with, see https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

**Comment by MaximBalaganskiy** [comment]
I'm in contact with Daniel about this. We will need to coordinate the upgrade and (in my opinion) conversion to TypeScript.
