### ISSUE TITLE
aurelia-cli + materialize.amd.js and uglify

### ISSUE THREAD

**Issue by tdamir** [aurelia-ui-toolkits/aurelia-materialize-bridge#466]
I'm having issues with uglify and transformed (amd) materialize-css.js file. This is what I get if I try to uglify transformed file: 

````
node .\node_modules\uglify-js\bin\uglifyjs .\node_modules\materialize-cs
s\dist\js\materialize.amd.js
Parse error at .\node_modules\materialize-css\dist\js\materialize.amd.js:3295,6
  let _defaults = {
      ^
SyntaxError: Unexpected token: name (_defaults)
    at JS_Parse_Error.get (eval at <anonymous> (--- skpiped ---\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
````

When I try to uglify the original file, there are no errors (ie. node .\node_modules\uglify-js\bin\uglifyjs .\node_modules\materialize-css\dist\js\materialize.js).

Versions: 
materialize-css@0.100.1
aurelia-materialize-bridge@0.30.0
uglify-js@2.8.28

**Comment by tdamir** [comment]
It looks like es6 is not supported by uglifyjs. Using the uglify-es instead and it looks like it solves the problem.

**Comment by Thanood** [comment]
Thanks for mentioning. 👍  😃

**Comment by tdamir** [comment]
I'm wondering if we could somehow transpile the input files to es5 before packing them into amd modules? I'm using aurelia-cli and uglify-js dependency is hard coded in it so I have to manually replace uglify-js with uglify-es on every cli update.

**Comment by Thanood** [comment]
Maybe once they're done with porting everything to es6 - or are they even done? I didn't check the last week.. Anyway, the `0.100.1` release still has a lot of es5 constructs and the point is: I'm unsure of what comes out of that.

It would mean for users to install a dev dependency of babel for the creation of an AMD compatible Materialize. Which may be better than replacing uglify-js on every cli update.

Tbh I'm even unsure why Materialize's `dist` folder contains untranspiled es6 code. 😕 

Maybe we could just provide the output of the script for each version? It will be the same anyway, right?
Hmm, why didn't I think of that before?

Reopening for discussion. 😃

**Comment by tdamir** [comment]
Sorry for a late response - I've been busy with other stuff. 
I agree, in my opinion the dev dependency on babel is much better, than modifying aurelia-cli every time the new version comes (#https://github.com/aurelia/cli/issues/490).
Since we already have to take steps for materialize-css to work with aurelia-cli (ie: ./node_modules/.bin/r.js.cmd -o rbuild.js), I was thinking maybe we could integrate also the transpilation in the workflow somehow.

**Comment by Thanood** [comment]
> I've been busy with other stuff.

Me, too! 😃 

What do you think about hosting the resulting `materialize.amd.js` for each Materialize version?
It's a little more work to always create a new version but I think it's the easiest possible way for users.

**Comment by tdamir** [comment]
If I understand correctly, that could cause problems if user updates materialize-css package independently of materialize-bridge. If we provide script for generating es5 version it would be better in my opinion (first run babel to transform es6 to es5 and then r.js.cmd -o rbuild.js. What do you think?

**Comment by Thanood** [comment]
Both solutions have their drawbacks, IMO.
I'm not comfortable with the additional babel dependency, to be honest. Somehow that doesn't "feel" right to me.

You're right but in the end the user who updates materialize-css separately has to do something anyway, create the AMD script or download a new version.

Sorry, I need to attend a meeting now. Very busy lately. -.-

**Comment by swalters** [comment]
@tdamir how do you use uglify-es  with cli?  What steps does it take?  Thanks!!

**Comment by tdamir** [comment]
@swalters 
1.  install the uglify-es (npm install uglify-es --save-dev)
2.  open the node_modules\aurelia-cli\lib\build\bundle.js file and replace require('uglify-js') with require('uglify-es')

**Comment by swalters** [comment]
thanks @tdamir 

Here's a quick hack aurelia task I created.
1. npm install gulp-replace --save-dev
2. create a file in aurelia_project tasks named fix-aurelia-cli
3. au fix-aurelia-cli

```
var gulp = require('gulp');
var rename = require('gulp-rename');
var replace = require('gulp-replace');
/**
 * replaces uglify-js with uglify-es
 */
export default function fixAureliaCli() {

  return gulp.src('./node_modules/aurelia-cli/lib/build/bundle.js', {base: './'})
             .pipe(replace("require('uglify-js')", "require('uglify-es')"))
             .pipe(gulp.dest('.'))

}

```
