### ISSUE TITLE
add sample for card action

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#467]
see https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/434

**Comment by vulvulune** [comment]
I'm trying to add the sample, but I can't have the latest version (0.29 or more for this sample) of aurelia-materialize-bridge.
https://gist.run/?id=8ce0d3ac7ca2029f932c3dde1937fc6f 

I have only this version of the materialize bridge: https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js

Is there somewhere a new version of the bundle available?

**Comment by Thanood** [comment]
Sorry, forgot about the bundle somehow..
I will get a new version out as soon as I can. Probably today.

**Comment by Thanood** [comment]
Okay, I've updated the bundles.
There's a link [Gist.run playground](https://gist.run/?id=e8eed34e8bba17f5213535bcdd004a9e) which is always updated with the latest version. TBH I don't update all of the samples on every version change. 😃 

I've forked your gist and updated it:
https://gist.run/?id=bc9e178e2e3ce42d23245331c31563b1

Make sure you also have the Materialize css import in `index.html`:

```js
System.import('materialize/dist/css/materialize.css!');
```

**Comment by vulvulune** [comment]
@Thanood Thank you.

I see there are some issues in my gist... I will update it.

**Comment by vulvulune** [comment]
A sample is here:
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/card-actions

**Comment by Thanood** [comment]
You're right, I should close this issue then. Apologies.
