### ISSUE TITLE
Card: add an attribute for css classes

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#471]
`<md-card md-class="grey lighten-2">`

The `md-class` value should then be used as `class` for the `.card` element of the template.

**Comment by vulvulune** [comment]
You can assign me this issue if you want. I know well the cards now.

**Comment by Thanood** [comment]
Thank you. 👍 

Somehow I can't, though. You're not in my "assignees" list.
But I guess you can take it on without an assignment, if you like to. 😃
