### ISSUE TITLE
AMD script doesn't work with Materialize v0.100.2

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#473]
Somehow, Velocity doesn't seem to initialize a global anymore. Or something along that lines, I couldn't quite see the reason behind it.

Tried several tweaks to the AMD script, moving velocity to the top, tweaking shims to have the `initial` module load velocity etc. but no avail.

The reason in in [this](https://github.com/Dogfalo/materialize/blob/master/js/global.js#L164-L177) global script in `global.js`. Velocity itself seems to be aware of AMD but since AMD is processed via callbacks, these lines run before Velocity introduces itself.

I wonder how that worked before. I didn't find any significant changes ... yet.

**Comment by Thanood** [comment]
I don't get it, really.. There doesn't seem to be any change to velocity in Vanilla materialize or the load sequence. At least if I didn't overlook it three times at least.

Still experimenting with that...

**Comment by k2s** [comment]
I don't have solution, but the problem comes in 0.100.2 with this code:

```
// Velocity has conflicts when loaded with jQuery, this will check for it
// First, check if in noConflict mode
var Vel;
if (jQuery) {
  Vel = jQuery.Velocity;
} else if ($) {
  Vel = $.Velocity;
} else {
  Vel = Velocity;
}

if (Vel) {
  Materialize.Vel = Vel;
} else {
  Materialize.Vel = Velocity;
}
;
```

The variable `Vel` is undefined at this point, but later `Materialize.Vel` is used. In 0.100.1 it is done differently so it worked.

I think it is problem with bundlingm because `VelocityJS.org (1.2.3)` should be loaded sooner then the code above is executed.

Hope my finding helps to fix this issue.

**Comment by Thanood** [comment]
Thanks a lot, you're right! 👍 
I didn't see that this was different in 0.100.1..

So Velocity must be loaded before that part of the code - in a module environment without actually using the module environment. Hmmm.. 😃

**Comment by swalters** [comment]
maybe this commit?
https://github.com/Dogfalo/materialize/commit/82fae629b04a426e0fc5cf3a005e61ddebaa05e4

**Comment by tdamir** [comment]
I'm wondering, instead of building/hacking an AMD version which is not AMD at all, maybe the recommended (or alternative) way of integrating materialize-css could be to prepend jquery.js and materialize.js files to the vendor-bundle?

**Comment by Thanood** [comment]
@tdamir  👍 
Maybe that's the best solution until Materialize works in a modular environment.

**Comment by MaximBalaganskiy** [comment]
Will check later with M v1 and open a new issue if needed
