### ISSUE TITLE
How to use timepicker ?

### ISSUE THREAD

**Issue by swiftanthony** [aurelia-ui-toolkits/aurelia-materialize-bridge#475]
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/timepicker-basic-use

The code from example does not work in latest version.
Moreover `$(node).pickatime(options)` does not seem to be available

**Comment by Thanood** [comment]
@swiftanthony Do you mean latest Materialize version or bridge version?
Strange, it works in the catalog app, though.

Do you mean `$.fn.pickatime` (console) is undefined?
If so, the component might not be included in the bundle or configuration.

Which bundler do you use?

**Comment by swiftanthony** [comment]
@Thanood I am using materialize 0.100.1, with aurelia-cli AMD packager.

What I found is that 'picker.time' is not a part of provided rbuild.js and materialize-css.js scripts:
* https://raw.githubusercontent.com/aurelia-ui-toolkits/aurelia-materialize-bridge/master/build/tools/rbuild.js
* https://raw.githubusercontent.com/aurelia-ui-toolkits/aurelia-materialize-bridge/master/build/tools/materialize-css.js

I tried to add 'picker.time' to both of them and `$.fn.pickatime` is now available for me but does not seem to work.

**Comment by Thanood** [comment]
Confirmed. And ... a little embarassing, too.

Please try:

```js
aurelia.use.plugin('aurelia-materialize-bridge', b => b.useAll().useTimePicker());
```

I forgot to add the timepicker to `useAll()` -.-

**Comment by Thanood** [comment]
reopening for confirmation 😃

**Comment by swiftanthony** [comment]
Yes, this fixes the issue, thanks
