### ISSUE TITLE
Timepicker: the bind value is not updated when click on "clear"

### ISSUE THREAD

**Issue by vulvulune** [aurelia-ui-toolkits/aurelia-materialize-bridge#480]
In the timepicker, when we click on the button "Clear", the value isn't updated.

Currently, the value is updated by the afterdone event:
`afterDone: this.afterDone.bind(this)`

But this event is called only when click on "OK".

In my opinion, we should you an `$(this.element).on('change', ...);` to update the value. It seems to work with the "OK" and "Clear" button. And the `afterdone` event is useless.

What do you think?

**Comment by Thanood** [comment]
I'd rather stick to the timepicker API instead of listening for change events on the input.
`afterHide` seems to be triggered by `clear` as well.

**Comment by Thanood** [comment]
Actually, your idea works better. 👍

**Comment by vulvulune** [comment]
I hope they will update the timepicker API in the version 1.0 to avoid this "hack". Thanks for the change.
