### ISSUE TITLE
Create the bridge package importer/installer

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#481]
As a means to solve several installation-related issues (#466, fonts handling, custom css), create an Aurelia-CLI package importer. Starting here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/au-import/importer.js

**Comment by Thanood** [comment]
@JeroenVinke If you're willing and have some time you might want to check if there's something completely awkward in the file mentioned above. I'm sure there is. 😃 

I've derived most of the processing from the CLI sources.

The importer applies a patch to `aurelia.json`, copies some scripts, installs dependencies because the bridge doesn't defined a "hard" dependency on `materialize-css` anymore to allow forks. After that it runs the AMD generation scripts.

Maybe there's a better way to use the CLI api for installing dependencies. I'd also like to bring in babel to transpile the AMD generation result and to add some tasks (couldn't find an `addTask` method). Any hints appreciated. 😃

**Comment by JeroenVinke** [comment]
Sure, its on my list. Not sure when i'll get to it though

**Comment by MaximBalaganskiy** [comment]
Not relevant anymore.
Solved this by creating a materialize-amd package and adding dependencies to aurelia project metadata.
