### ISSUE TITLE
md-select will not render correctly inside of md-tabs

### ISSUE THREAD

**Issue by emcga** [aurelia-ui-toolkits/aurelia-materialize-bridge#482]
When placing an md-select element inside of a content div that is associated with a md-tabs element, the select element will not initialize/render properly. I'm assuming this may be due to how materialize handles select elements. I will investigate more into this, but if anyone has a suggestion please let me know.

Thanks

**Comment by Thanood** [comment]
In which way is it not rendered properly?
Would you mind preparing a gist?

In this one it seems to be okay: https://gist.run/?id=4b3cc8e914e2d642854037f35dd9708b

**Comment by MaximBalaganskiy** [comment]
Cannot reproduce. Works with the lates version
https://gist.run/?id=4aee648de2d5bbb52567ee90b74f61ba
