### ISSUE TITLE
Cannot specify min/max to md-input when type is number

### ISSUE THREAD

**Issue by Kukks** [aurelia-ui-toolkits/aurelia-materialize-bridge#489]
We should be able to specify the min/max for md-input to pass along to the input element

**Comment by Thanood** [comment]
Agreed 👍

**Comment by Thanood** [comment]
Another attribute which should be forwarded: #487

**Comment by Thanood** [comment]
Whoops, reopening until I added an example. 😃

**Comment by MaximBalaganskiy** [comment]
Fixed via https://github.com/aurelia-ui-toolkits/demo-materialize/commit/c20c9a99199baa745a8ae425e96c34fb52889194
