### ISSUE TITLE
Error running with aurelia-client again.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#490]
Hi I am having trouble running with aurelia-cli again

I have one system (debian) that runs fine but my local Fedora gives errors in the browser.

vendor-bundle.js:45516 GET http://127.0.0.1:9000/scripts/materialize-bundle.html 404 (Not Found)
vendor-bundle.js:1398 Unhandled rejection Error: src/../scripts/materialize-bundle.html HTTP status: 404
    at XMLHttpRequest.xhr.onreadystatechange (http://127.0.0.1:9000/scripts/vendor-bundle.js:45502:31)
...

I see no errors on the command line with au run.

The source is the same git checkout on both systems so the only difference could be node or npm I guess.

Versions are

 "aurelia-bootstrapper": "^1.0.0",
 "aurelia-materialize-bridge": "^0.30.0",
 "materialize-css": "^0.99.0",
 "requirejs": "^2.3.2",
 "aurelia-cli": "^0.22.0",

I have removed my node_modules directory and reinstalled.
I have done
./node_modules/.bin/r.js -o rbuild.js

Any theories ?

Thanks

**Comment by glennpierce** [comment]
Ok I used

"resources": [
        "**/*.{css,html}",
        "index.js"
      ]

Instead of the big list of resources.
I don't now why this works on the other system. Odd.

**Comment by Thanood** [comment]
Aurelia CLI had a bug where you had to explicitly include the `index.js` in the bundle. I'm guessing either `^0.22.0` installed that version for you or that issue is back..

**Comment by MaximBalaganskiy** [comment]
Checkout the updated installation docs. The bridge works with latest CLI.
