### ISSUE TITLE
md-input bind a function issue ?

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#491]
Hi

I am having trouble with md-input.

I am trying to attach an enter key press to a search md-input field located in a side nav.
Now if I bind to a variable in my App class like the demo

<md-input md-label="put some text here" md-value.bind="textValue" md-disabled.bind="disabledValue"></md-input>

Things work ok.

However, I want to attach to a function so I can check for an enter key press.

I have tried 

<md-input md-type="search" md-label="Search:" keypress.delegate="onSearchEnter($event)" autofocus></md-input>

This however returns the error
ncaught Error: onSearchEnter is not a function

onSearchEnter is defined in the App class . The same class I had my bound textValue which worked.

What am I doing wrong here ?

Thanks

**Comment by MaximBalaganskiy** [comment]
Could you please post a snippet of your html or a gist?

**Comment by glennpierce** [comment]
Sorry. It is something like this.

https://gist.run/?id=307c9e4f19d454b1f61763f1c16e56f9

My original  code is a quite large typescript project. I have shrunk in down but the Gist does not fully work. I don't know why the console in the debug tools gives a pretty obscure error that I don't follow.

**Comment by glennpierce** [comment]
Ah Here you go https://gist.run/?id=6366931a15600c3880587db3b7884ccc

The onSearchEnter function does not get called.

**Comment by MaximBalaganskiy** [comment]
I think the issue here is that `md-input` does not propagate `keypress` event

**Comment by MaximBalaganskiy** [comment]
Bind to `$this.$parent.onSearchEnter($event)`. Your `nav-bar` does not have a view model. Not sure, may be this does not set the context correctly. But even if it did, you would need `$parent` anyway

**Comment by glennpierce** [comment]
Ok the event handler works when using $this.$parent.onSearchEnter($event) thanks.
However, the actual md-input no long shows text now. The keypress be swallowed ?

**Comment by glennpierce** [comment]
Ah just had to return true from handler.

Thanks
