### ISSUE TITLE
missing rbuild.js and materialize.js (install docs)

### ISSUE THREAD

**Issue by dennismi** [aurelia-ui-toolkits/aurelia-materialize-bridge#497]
Hey

The Aurelia CLI installation documentation is really out of wack.  (https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html)

It states that you need to get rbuild.js and materialize.js, but these two files cannot be found in master. 

Is this still needed?

**Comment by MaximBalaganskiy** [comment]
Nope. `Au install materialize-amd` and `au install
aurelia-materialize-bridge` should be enough

I just haven't got time to update the docs

**Comment by MaximBalaganskiy** [comment]
Please note the use of materialize-amd package - it's an AMD rebuilt version

**Comment by dennismi** [comment]
Ok, kewl Will look into it later

\\dennis

Den søn. 8. apr. 2018 00.52 skrev Max <notifications@github.com>:

**Comment by MaximBalaganskiy** [comment]
I've updated the docs, please see if it works for you.
Note that it's a bit more than just two installs.

**Comment by dennismi** [comment]
Got it installed, Thanks ...
