### ISSUE TITLE
Webpack installation guide contains dead link (manual bootstrapping)

### ISSUE THREAD

**Issue by FINDarkside** [aurelia-ui-toolkits/aurelia-materialize-bridge#498]
[Webpack installation guide](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/webpack.html) links to [dead page](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/4) about manual bootstrapping.

**Comment by MaximBalaganskiy** [comment]
Fixed
