### ISSUE TITLE
Using keyboard to select autocomplete doesn't clear validation

### ISSUE THREAD

**Issue by rokadias** [aurelia-ui-toolkits/aurelia-materialize-bridge#514]
On the autocomplete input boxes if you start typing and then use the keyboard arrows to select a value from the dropdown then hit enter. The change event isn't fired, and it looks like the change is swallowed. In such a way that validation will remain even though the option has been chosen.

I tried creating an example of this by adding an example of the validation to the autocomplete. However, I'm not sure if the gist from the demo site is running from 0.34.2 and with materialize css 0.100.2

I basically created an input with autocomplete and validation logic making sure the option selected was from the autocomplete drop down. However the validation is not updated when choosing an option in the dropdown using the keyboard.

Here's the example code, but for some reason it works differently in the gist. The change event doesn't fire while typing, but does fire for the mouse and keyboard situation.
https://gist.run/?id=15238eccc50150f292e021375bab916e

Also noticed the documentation in the demo mentions a property `md-on-autocomplete` that doesn't seem to work, and I don't see a reference for it in the code. To solve this issue I've used that property from materialize, I'll create a PR for the branch where I've fixed it for myself.

**Comment by MaximBalaganskiy** [comment]
The gist is based on v1. And you have a typo there `this.controller.valdiateTrigger = validateTrigger.change;`
With it fixed it works fine.

**Comment by MaximBalaganskiy** [comment]
The `md-on-autocomplete` event also works fine in the original gist for autocomplete
