### ISSUE TITLE
Missing docs for breadcrumb usage

### ISSUE THREAD

**Issue by MrTango** [aurelia-ui-toolkits/aurelia-materialize-bridge#518]
From the demo and the docs it's not clear how to use the Breadcrumb component in aurelia. The original Breadcrumb component is quite simple and flexible, as it's only a list. How can we create a custom Breadcrumb?

**Comment by MaximBalaganskiy** [comment]
Bridge's breadcrumbs uses routers chain information to build the list. You can always use original materialize classes and calls to build the one that suits your needs

**Comment by MaximBalaganskiy** [comment]
Only routes end up in crumbs, not parameters. You can use whatever examples
you might find on pure materialize though to build your own control

**Comment by MaximBalaganskiy** [comment]
Please reopen if needed
