### ISSUE TITLE
set packages as dependencies

### ISSUE THREAD

**Issue by Virrum** [aurelia-ui-toolkits/aurelia-materialize-bridge#520]
Hi,
Tried to install this plugin today, and had to install aurelia-typed-observable-plugin and aurelia-validation manually to get it to build. Would it help to set them as a dependency instead of a devDependency? Also, perhaps materialize-css@next could be added as a dependency?

Looking forward to test it out now :) Thanks for your effort!

**Comment by MaximBalaganskiy** [comment]
This answer summarises the use of peer dependencies - typed plugin and
materialize are external to the bridge and may also be used outside of the
bridge

**Comment by Virrum** [comment]
Do you know if perhaps Webpack isn't handling peer dependencies in the same way?

**Comment by Virrum** [comment]
Ok, I then suggest to add the two packages to the first npm install in the docs: https://aurelia-ui-toolkits-1.gitbook.io/materialize-bridge-docs/2.-installation/webpack :)

**Comment by MaximBalaganskiy** [comment]
Thanks for the suggestion, I've updated the docs.
I've just realised I never pasted the link to the SO answer. Here it is
https://stackoverflow.com/a/34645112/944182

**Comment by MaximBalaganskiy** [comment]
I'll keep peer dependencies for now as this seems to be the right way of doing it.
Please reopen if find more issues with this.
