### ISSUE TITLE
Transitions in v 1.0.0

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#523]
We are upgrading from AMB 0.27 to 1.0.0. It is a JSPM and TypeScript 3 based solution.

So far I have noticed that there is no transitions folder in jspm_packages\npm\aurelia-materialize-bridge@1.0.0 and during app start I see an error:

> .useTransitions() is not a function

I can exclude `bridge.useTransitions()` but it should be supported considering installation guide:
https://aurelia-ui-toolkits-1.gitbook.io/materialize-bridge-docs/2.-installation/jspm

Do I miss something or something is missing?

**Comment by MaximBalaganskiy** [comment]
Transitions have been removed in Materialize v1

**Comment by MaximBalaganskiy** [comment]
I'll update the docs shortly...

**Comment by nndevstudio** [comment]
I understand. Thanks.

**Comment by MaximBalaganskiy** [comment]
Docs updated
