### ISSUE TITLE
options.bind in v 1.0.0

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#524]
Considering 
https://stackoverflow.com/questions/43225208/how-to-set-default-mddatepicker-options-translations-for-weekdays-months-fo

We have used `options.bind` by now.

I tried with i18n
```
 <md-datepicker container="body" value.two-way="fromDate" i18n.bind="languageService.mdDatePickerOptionsTran"                                          placeholder=${dtPickTitle}>
</md-datepicker>
```
and did my best to find the same or similar property but without success :-(

Any help?

**Comment by MaximBalaganskiy** [comment]
Please look at the demo gist https://gist.run/?id=bc15df536942eb546d2fdc7f038b2c0e
