### ISSUE TITLE
Datepicker: auto-close causes not binded value.

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#526]
https://gist.run/?id=8ece24bc12015ad169c914cedec3c771

If ` auto-close=true` then value (`value.two-way or value.bind`) is not binded.

**Comment by MaximBalaganskiy** [comment]
it should be ` auto-close="true"`

**Comment by MaximBalaganskiy** [comment]
It was a bug after all
