### ISSUE TITLE
aurelia-materialize-bridge.d.ts

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#527]
Our project is based on Aurelia TS Skeleton and JSPM.
By now we have used in typings.json this line:
`"aurelia-materialize-bridge": "github:aurelia-ui-toolkits/aurelia-materialize-bridge/dist/aurelia-materialize-bridge.d.ts",` just like for all `aurelia-...` libraries.

We are migrating to AMB v1 so, for now, we can use already downloaded version to avoid "Cannot find module aurelia-materialize-bridge" in .ts files

Will `aurelia-materialize-bridge.d.ts` file be generated and where or there is another approach that we should apply considering mentioned settings?

**Comment by MaximBalaganskiy** [comment]
The easiest way to solve this is to mirror install the bridge with npm.
See https://github.com/jspm/jspm-cli/issues/1344 for details.

**Comment by MaximBalaganskiy** [comment]
I suspect you could also point typings to `index.d.ts` in one of the dist sub-folders.

**Comment by nndevstudio** [comment]
Thanks for great feedback, but now I have some new errors in both cases.

1. I tried mirroring:
`npm install  aurelia-materialize-bridge --save-dev` has resolved  "Cannot find module aurelia-materialize-bridge" in .ts files but now there is an compilation error for every bridge module like e.g. Tooltip:
`/node_modules/aurelia-materialize-bridge/dist/commonjs/tooltip/tooltip.d.ts`
`error TS2694: Namespace 'M' has no exported member 'Tooltip'.`

Btw `npm install aurelia-typed-observable-plugin --save-dev` was requested during compilation so I installed this too.

2. Uninstalled npm mirorring and pointed typings:
```
 "aurelia-materialize-bridge": "github:aurelia-ui-toolkits/aurelia-materialize-bridge/dist/commonjs/index.d.ts",
 "aurelia-typed-observable-plugin":"github:aurelia-contrib/aurelia-typed-observable-plugin/dist/types/index.d.ts",
```
In this case I have "only" one error 
```
Error: typings\modules\aurelia-materialize-bridge\index.d.ts(401,15): 
error TS2503: Cannot find namespace 'M'.
```
but for almost every bridge component e.g.
```
 instance: M.Collapsible;
 instance: M.Datepicker;
i18n: Partial<M.InternationalizationOptions>;
```
I would like 2. approach with typings to became a solution :-) 

Any clue about `M.`?

**Comment by MaximBalaganskiy** [comment]
You need to install materialise typings

**Comment by MaximBalaganskiy** [comment]
Or setup typescript to not check lib modules

**Comment by nndevstudio** [comment]
In this moment, а second approach   `"skipLibCheck": true` seems more convenient because we try to avoid new dependencies when possible.
It works now.
