### ISSUE TITLE
Select, Edge, Gist and the newest Aurelia

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#528]
We are facing very strange behaviour  of `select` component  with the newest Aurelia components in the Edge browser. 
Only the first selection of any element in list is ok, any next selection without focus change causes page reload. So I want to prepare a Gist example:
https://gist.run/?id=79bd16bb78646370ee70b93e97287e88

Where can we find the newest bundle of Aurelia? I want to change at least this line:
` <script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.30.0/config2.js"></script>` and try to cause the same behaviour.

**Comment by MaximBalaganskiy** [comment]
Run any example from the demo app, it will generate a gist with latest
bundles

**Comment by MaximBalaganskiy** [comment]
I cannot reproduce this in Edge with the demo app

**Comment by nndevstudio** [comment]
For some reason, in the last few days, whenever (in any browser) I click on PLAY button (on this page, for example: https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/binding-to-objects) I get this redirection error: http://aurelia-ui-toolkits.github.io/demo-materialize/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch.

I am signed in on Github but no Gist page opens.

Btw,  Select demo is working fine in Edge but when we copy the same code and do jspm update in our project then we face mentioned problem. We will investigate more what is happening, I've just wanted to check is Gist updated.

**Comment by MaximBalaganskiy** [comment]
There is an issue at the moment with my Azure Function which generates auth tokens for gists. I'll look into this tomorrow.

**Comment by nndevstudio** [comment]
I have updated our example https://gist.run/?id=79bd16bb78646370ee70b93e97287e88. It is derived from Aurelia demo app now. 
In Gist version we are facing `<select>` component blocking and automatic page reload issue when try to change selected list element without focus change. Sometimes we can change max. 2-3 times selected item and than it blocks but usually only the first selection works.
It is tested in 3 Edge instances. No console errors.

It is interesting that in demo app it works ok.

**Comment by MaximBalaganskiy** [comment]
Can you please create a simple jspm (no bundling) reproduction repository?
Something is not right with Edge+Jspm...

**Comment by nndevstudio** [comment]
Can't make it today but I will try tomorrow.

**Comment by MaximBalaganskiy** [comment]
Not sure why this fixes the issue for Edge - probably some weird timing. But anyway...
