### ISSUE TITLE
Compilation problems when using npm install

### ISSUE THREAD

**Issue by lpkruse** [aurelia-ui-toolkits/aurelia-materialize-bridge#530]
When I do a 
> npm i aurelia-materialize-bridge --save

Which gives me aurelia-materialize-bridge-1.1.10, and then build my project with the latest material-css-1.0.0-rc.2, I get a lot of the following errors:

--------------------------------
ERROR in [at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/select/select.d.ts:6:17
    TS2694: Namespace 'M' has no exported member 'FormSelect'.

ERROR in [at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/dropdown/dropdown.d.ts:21:17
    TS2694: Namespace 'M' has no exported member 'Dropdown'.

ERROR in [at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/autocomplete/autocomplete.d.ts:9:17
    TS2694: Namespace 'M' has no exported member 'Autocomplete'.
.
.
.
---------------------------------------

But if I "Download ZIP" using "Clone or Download" , and then copies that folder into my node_modules/aurelia-materialize-bridge then the build works.
When I look at this code it does not make use of references to 'M', but the latest code does, so this must be older code that works, and the latest code is broken or what am I missing  ?

**Comment by MaximBalaganskiy** [comment]
Please install @types/materializecss or set skipLibCheck in tsconfig

**Comment by lpkruse** [comment]
Thanks, worked like a charm 🥇
