### ISSUE TITLE
Errors in bundling with  aurelia-bundler ^0.7.0 and "systemjs-builder": "^0.16.9".

### ISSUE THREAD

**Issue by nndevstudio** [aurelia-ui-toolkits/aurelia-materialize-bridge#533]
Considering this issue: https://github.com/aurelia/bundler/commit/98215c1c4e1fad84803fe7366c27a453a93f1ddb#commitcomment-30808714 is there any workaround so we can bundle aurelia-materialize-bridge 1.1.0 properly?

**Comment by MaximBalaganskiy** [comment]
One of the build steps of the demo app is creating a jspm bundle for the gists. You can have a look how it is done there. I've got  a very limited access to the internet (vacation) so will only be able to have a look after 20th of October

**Comment by MaximBalaganskiy** [comment]
Basically, you don't really need an aurelia bundler - jspm cli can to this task just fine.

**Comment by nndevstudio** [comment]
Thanks Max, great tip with demo-materialize project and jspm.config.js approach. Unfortunately we are not so experienced for native jspm bundling so in this moment we experiment with downgraded aurelia-bundler v. 0.5.0. It seems that it works.

**Comment by MaximBalaganskiy** [comment]
There is not much to it. Just one cli command where you list the packages
you want in the bundle. You can see it in package.json under bundle:jspm
script

**Comment by nndevstudio** [comment]
I must ask you, can this bundle:jspm approach be used with bundles.js file and already configured gulp task in tasks/bundle.js so instead of `var bundler = require('aurelia-bundler');` we can use something like  `var bundler = require('jspm only');` ?

We rely on bundles.js configuration because one part of application can work in "execution only" mode so it does not need all components. But in case when the user is signed in then all bundles are requested.
