### ISSUE TITLE
Installation for CLI - aurelia.json step is unclear

### ISSUE THREAD

**Issue by Krossmaskinen** [aurelia-ui-toolkits/aurelia-materialize-bridge#534]
Aurelia CLI [installation](https://aurelia-ui-toolkits-1.gitbook.io/materialize-bridge-docs/2.-installation/aurelia-cli) step 4 is unclear on where the piece of JSON should be added.

> 4. Update aurelia.json for the typed plugin
```
{
  "name": "aurelia-typed-observable-plugin",
  "path": "../node_modules/aurelia-typed-observable-plugin/dist/amd",
  "main": "index"
},
```

I can't add it directly under the main JSON object in `aurelia.json` file since it has no key, and not outside it since it can only hold one JSON object. What key should it be under? Do I have to add a new one?

It would be awesome if the instructions were clearer on this step.

**Comment by MaximBalaganskiy** [comment]
It should already be present in "dependencies" for the vendor-bundle, in bundles section, just needs a little tweak. If not there you can just add it.

**Comment by Krossmaskinen** [comment]
Is the vendor-bundle in aurelia.json?
Anywho, I have neither in my aurelia.json by default. Your reply is precisely the info that should be in the docs.

**Comment by MaximBalaganskiy** [comment]
Docs are updated
