### ISSUE TITLE
validation class for checkboxes not set

### ISSUE THREAD

**Issue by eikaramba** [aurelia-ui-toolkits/aurelia-materialize-bridge#536]
i tried having a validation rule for a checkbox. the actual validation works, however in the browser the input does not get the ".invalid" class and thus is not styled in red.

Code:
`<md-checkbox validate="true" checked.bind="terms & validate">Ich habe die <a style="text-decoration: underline" class="bright" click.trigger="scrollTo('#terms')">Nutzungsbedingungen</a> gelesen und willige in diese ein.</md-checkbox>`

![grafik](https://user-images.githubusercontent.com/1320525/47884697-12cdac00-de32-11e8-8153-cc3225b72229.png)

**Comment by MaximBalaganskiy** [comment]
Original materialize checkbox does not support validation. You could just display an error message below it or, I as i did, write a custom validation container element. I will probably add it later to the bridge but for now feel free to copy it from the gist
https://gist.github.com/MaximBalaganskiy/74ef29931975bd641a159031162b2316

**Comment by MaximBalaganskiy** [comment]
![image](https://user-images.githubusercontent.com/3712700/47886741-09732c80-de90-11e8-9c84-2fd2071cab23.png)

**Comment by MaximBalaganskiy** [comment]
Done via e03c9198d9931df694e657f799dce884c507aaeb

**Comment by MaximBalaganskiy** [comment]
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/validation-container/basic-use

**Comment by eikaramba** [comment]
hey @MaximBalaganskiy i already use something like that you can see it here:
https://psyweb.uni-muenster.de/signup

just click "einloggen". As you see here the checkbox actually turns red as it used to in the past(i think i just needed to add the css code for that, but the class selector was set by AMB). I updated from 0.x to 1.x now and migrated everything and observed that it seems also the validationRenderer got some refactoring.

You are right i checked again and Materialize indeed does not provide a style for this. Too bad, i think it is easy to do (just add the .invalid class to the input field in the same way how it is done to text fields) and add one simple line of css class to make the border red of the checkbox.

I don't know if you agree to "patch" such functionality to AMB or it is better to hope the materialize guys provide something in the future. Anyway your validation-container is something i want to have a look at, although i already have it. But always good to stick with the frameworks choices :)
