### ISSUE TITLE
Using native materialize markup.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#537]
Is there a way to use native materialize markup ?

What I mean is that I have quite a few <md-card title="Card title"></md-card> elements to display.
The problem is I need to have an icon element in the title.

something like

```
<div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title <icon name="someicon"></icon></span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
```
What would be the best way to get that icon element into the generated markup?

**Comment by MaximBalaganskiy** [comment]
md-card does not support this at the moment. It would have to use templated parts and it wouldn't be backwards compatible.
