### ISSUE TITLE
Null ref on tooltip detached event

### ISSUE THREAD

**Issue by bmcdaniels** [aurelia-ui-toolkits/aurelia-materialize-bridge#539]
The detached event in md-tooltip fires destroy on the tooltip instance. The instance is only being created if text is supplied, so when the view is detached it will throw exceptions. 

`<i md-tooltip="position: bottom; text.bind: tooltipText;" show.one-way="tooltipText" class="far fa-question-circle"></i>`

Above is an example of when this can occur. A quick fix was to change `show.one-way` to `if.one-way`, but I think both need to be supported.

**Comment by MaximBalaganskiy** [comment]
Fixed via 293482ca66402ee43f382748ee6a309c82730a20
