### ISSUE TITLE
Can't get form value from checkbox

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#540]
I am having trouble getting the value from a checkbox. This is when it is checked and submitted.
I am using serializeArray to get the values of the form.

I think the name attribute on md-checkbox is being removed. 

I have an example gist here

https://gist.run/?id=401d17507278f8a816d8f430c33fa0f3

Thanks

**Comment by MaximBalaganskiy** [comment]
`serializeArray` looks for the `value` *attribute* which is not present on this custom element

**Comment by glennpierce** [comment]
Thanks. What you you suggest as a work around ?
