### ISSUE TITLE
Validation on Select item

### ISSUE THREAD

**Issue by schmarre** [aurelia-ui-toolkits/aurelia-materialize-bridge#541]
Validation on select item doesn't seem to work!

**Comment by MaximBalaganskiy** [comment]
Could you please provide more details and error logs. It works fine in the demo app
http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/select/validation

**Comment by schmarre** [comment]
Yesterday when I was testing the validation function on a select item, the
error message was not shown. I was using safari. Today it works!
So it seems to be solved now.

**Comment by MaximBalaganskiy** [comment]
There was an issue with the demo. The bridge itself was fine though...
