### ISSUE TITLE
Range component limits are being ignored

### ISSUE THREAD

**Issue by Vheissu** [aurelia-ui-toolkits/aurelia-materialize-bridge#544]
The [range component](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/range/min-and-max) appears to be ignoring minimum and maximum values provided to the component. Enter "10" as a minimum value and "20" as a maximum, you can drag the slider below 10 and above 20. I have a Gist here where the issue can be seen: https://gist.run/?id=31b44be0b5fcf068bcd25607dcf2e42c

Playing around with that Gist created from the samples, you can see all values being provided to the plugin are actually being ignored.

**Comment by MaximBalaganskiy** [comment]
It's a demo bug. `md-` atrtibute prefixes should be removed

**Comment by MaximBalaganskiy** [comment]
Fixed

**Comment by Vheissu** [comment]
Legend. Love your work @MaximBalaganskiy
