### ISSUE TITLE
Rename tooltip and toast text/message fields

### ISSUE THREAD

**Issue by FINDarkside** [aurelia-ui-toolkits/aurelia-materialize-bridge#546]
[toastService](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/toast/toastService.ts#L8) and [tooltip](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/tooltip/tooltip.ts#L15) use `message` and `text` fields for content which does not adequately convey that the content is actually rendered as html instead of text.

**Comment by MaximBalaganskiy** [comment]
That's going to be a breaking change. I'm inclined to hold on till the upgrade to Aurelia vNext.

**Comment by FINDarkside** [comment]
While it's a breaking change, the current state exposes many people to XSS as they don't know the data labeled as `text` is really handled as html. Even more so, because this is Aurelia, and there's really no need for parsing attributes as html. The content should be exposed as a slot instead. I get that it's done the way it is, because of how materialize work, but it's not reasonable to expect developers to know this. Pretty much the only way to find about this is by specifically testing every component for xss, or by reading all the source code in this repo. Even if you decide to not make the change yet, you should at least make a big warning about it.
