### ISSUE TITLE
md-select has to be .two-way bound explicitly

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#55]
Although ```md-select``` is configured this way:
```javascript
@bindable({
    defaultBindingMode: bindingMode.twoWay
  }) selected;
```

It seems like ```selected``` still needs to be bound ```.two-way``` explicitly to work correctly:
```html
<select multiple md-select="selected.bind: selectedValues;">
```

does not update ```selectedValues``` while the following does:
```html
<select multiple md-select="selected.two-way: selectedValues;">
```

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/templating/issues/253?

**Comment by Thanood** [comment]
That was fast. Very nice! :smile: 
Thanks for linking.

**Comment by JeroenVinke** [comment]
Can you fork that plunker, and use `<select>` instead of `<input>`? If that doesnt work either, you should mention that in the issue

**Comment by Thanood** [comment]
Sure, will do that later.

**Comment by Thanood** [comment]
tbh I am not sure if this really shows the issue:
http://plnkr.co/edit/g2i582ZL29bhLEiXobhG?p=preview

Could you take a quick look before I post it to aurelia/templating?

**Comment by JeroenVinke** [comment]
http://plnkr.co/edit/UjmWYHElE4l09lyyQT29?p=preview

or 

http://plnkr.co/edit/pQBcziEVQsf5wHJl1Qti?p=preview

**Comment by Thanood** [comment]
http://plnkr.co/edit/pQBcziEVQsf5wHJl1Qti?p=preview

I knew I forgot something. :smile:

**Comment by JeroenVinke** [comment]
:)

**Comment by Thanood** [comment]
Aurelia has been fixed :)
