### ISSUE TITLE
Missing gulpfile

### ISSUE THREAD

**Issue by OtherLeadingBrand** [aurelia-ui-toolkits/aurelia-materialize-bridge#551]
Sometime in the past around Feb 25, 2018 Commit ID: 7d461833ecae91b7a86a54b82c81092739c4f0f the build sub directory and the related gulpfile.js were removed from the project.  This causes the gulp commands in the documentation to fail because there is no existing gulp configuration.

Does the documentation need to be updated to include new build instructions? Apologies if I'm missing a step here.

**Comment by MaximBalaganskiy** [comment]
Any gulp stuff is a leftover. `Npm run build` should build the project

**Comment by OtherLeadingBrand** [comment]
Thanks for the quick feedback. I was able to build using npm run build yesterday. 

I see that both the "test" and "ci" scripts in package.json use "gulp test" and "gulp ci". Are the unit tests now ran via a different method than documentation?

**Comment by MaximBalaganskiy** [comment]
Unfortunately, docs are out of date. There are no tests at the moment. It's
always been monkey tested :)

**Comment by OtherLeadingBrand** [comment]
No problem Maxim. The monkeys are doing a great job thus far. Appreciate the feedback.
