### ISSUE TITLE
md-select error: M is not defined

### ISSUE THREAD

**Issue by SirMossi** [aurelia-ui-toolkits/aurelia-materialize-bridge#553]
I'm new to aurelia and the materialize bridge. So I think, that it's just a configuration problem on my side, which I could not find.

I've added a select component with the following code:

    <select md-select value.bind="selectedVnl"
              change.delegate="selectedSalesmanChanged(changedValue)">
        <option model.bind="null">Choose a salesman</option>
        <option repeat.for="salesman of salesmen"
                model.bind="salesman.Vnl">
              ${salesman.Firstname} ${salesman.Lastname} (${salesman.Vnl})
        </option>
    </select>

But this causes the following runtime error:

    select.ts:135 Uncaught ReferenceError: M is not defined
    at MdSelect.createMaterialSelect (select.ts:135)
    at select.ts:89
    at TaskQueue._flushQueue (aurelia-task-queue.js:96)
    at TaskQueue.flushTaskQueue (aurelia-task-queue.js:142)
    at aurelia-task-queue.js:81
    at handleFlushTimer (aurelia-task-queue.js:38)

I think, this is a loading issue, but I have no idea how to fix this.

In my app.html I've added the following lines:

    <require from="font-awesome/css/font-awesome.min.css"></require>
    <require from="materialize-css/dist/css/materialize.css"></require>

In main.ts I've added the plugin usage statement:

    .plugin(PLATFORM.moduleName('aurelia-materialize-bridge'), b => 
        b.useAll().preventWavesAttach()
    );

Also interessting (I think) is the stylesheet in index.html

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

Are there any additions needed in aurelia.json? I did not find any informations in the getting started documentation.

I hope someone could help me with this issue

**Comment by MaximBalaganskiy** [comment]
Check if you have `import 'materialize-css';` somewhere in your code

**Comment by MaximBalaganskiy** [comment]
https://aurelia-ui-toolkits-1.gitbook.io/materialize-bridge-docs/2.-installation/webpack

**Comment by SirMossi** [comment]
that's it. Maybe it is possible to highlight all changes you have to make in a default configuration somehow or something like that. Then you'd rather see what has to be done.
Thank you for your assistance

**Comment by MaximBalaganskiy** [comment]
The link above is a part of the book which is referenced on the main page. Adding that import is a part of the instructions. Not really sure how to improve this...
