### ISSUE TITLE
md-datepicker and md-timepicker causing issues with scrolling.

### ISSUE THREAD

**Issue by glennpierce** [aurelia-ui-toolkits/aurelia-materialize-bridge#566]
Hi

I have a page where I have a md-datepicker and a  md-timepicker. Thibngs seem to working fine
when selecting eith . the dialog pops ups and I can select a date or time. however, once the dialog closes
I can no longer scroll. I can see any errors though in the page.

Note that this is on my android mobile . On the desktop things are fine.
I am trying to find a work around. 

does anyone have suggestions for debugging this. Maybe destroying manually somehow ?
I am running out of ideas.

thanks

**Comment by MaximBalaganskiy** [comment]
Can you check if scrolling works for you in the demo app? I don't observe the issue there.

**Comment by glennpierce** [comment]
I worked it out. It was wierd behaviour from fullpage (setup on another page of a single page app)
I have had nothing but trouble with that code. Sorry to waste your time.

**Comment by MaximBalaganskiy** [comment]
Just a reminder - this bridge will be retired soon. Please consider switching to https://github.com/aurelia-ui-toolkits/aurelia-mdc-web

**Comment by glennpierce** [comment]
Thanks is it a easy port ?
Not sure I could justify any serious amount of work.  I would probably move to Vuejs as I have other projects in that and it seems more widely used than Aurelia

**Comment by MaximBalaganskiy** [comment]
While it's 1-to-1 component replacement you'll still need to upgrade all templates manually.
The original Materialize CSS is abandoned and other devs created a fork. Our company has decided to not rely on this unstable UI framework anymore.
