### ISSUE TITLE
Implement dropdown

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#59]
Any opinions on md-dropdown?

```html
<md-dropdown title="drop me!" constrain-width="true">
  <ul>
    <li><a click.delegate="action1()">one</a></li>
    <li><a click.delegate="action2()">two</a></li>
    <li class="divider"></li>
    <li><a click.delegate="action3()">three</a></li>
  </ul>
</md-dropdown>
```
http://plnkr.co/edit/zhgVowIr3mPPLYHoFJyk?p=preview

vs

```html
<a md-dropdown="constrain-width: true;" class="btn" data-activates="dropdown1">drop me!</a>
    
<ul id='dropdown1' class='dropdown-content'>
  <li><a click.delegate="action1()">one</a></li>
  <li><a click.delegate="action2()">two</a></li>
  <li class="divider"></li>
  <li><a click.delegate="action3()">three</a></li>
</ul>
```
http://plnkr.co/edit/jaSEjYf8K1ZyRq8g4aZ8?p=preview

I'd prefer a custom element as we can ignore IDs and the dropdown-structure itself is "embedded" and not anywhere in the DOM
.

**Comment by adriatic** [comment]
This is one of the issues that was discussed several times. If you take the custom element approach you have to "process" all child elements (`ul`, `li`) and do that in a sufficiently generic fashion. In addition, people with solid understanding of HTML 5 would be surprised that this is implemented that way.

This is not something that we can do regardless of users might expect, so I would recommend to start the custom attribute approach

**Comment by Thanood** [comment]
Thanks a lot. That's exactly why I tagged this "needs more feedback". :smile:

**Comment by Thanood** [comment]
I've had a look at the [dropdown source](https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js) and it seems that it doesn't need to be ```<ul>``` but can be anything. So this would be possible.

Having said that, I think that this:
> people with solid understanding of HTML 5 would be surprised that this is implemented that way

is a strong point.

**Comment by Thanood** [comment]
Currently implementing the sample pages. There's another reasons for an attribute: Multiple triggers for the same dropdown:
```html
<a md-button md-dropdown="activates: dropdown1; below-origin: true;">below origin</a>
<a md-button md-dropdown="activates: dropdown1; hover: true;">open on hover</a>
<ul id="dropdown1">
  <li><a click.trigger="showToast($event)">one</a></li>
  <li><a click.trigger="showToast($event)">two</a></li>
  <li class="divider"></li>
  <li><a click.trigger="showToast($event)">three</a></li>
</ul>
```

**Comment by JeroenVinke** [comment]
I agree with @adriatic, besides there is already an existing HTML structure (not a placeholder)
