### ISSUE TITLE
prefixing attributes/elements

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#6]
How should we prefix our controls? There are some options, with the example of a button (be it an element or attribute):
* md-button
* ma-button
* material-button
* materialize-button

I'm proposing the first because I think ```ma-button``` just looks funny. The other two options are in my opinion too long and not as easy to write.

**Comment by JeroenVinke** [comment]
I vote for `md-button`, for the reasons mentioned above :)

**Comment by adriatic** [comment]
What Jeroen says [above](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/6#issuecomment-171917189) :-)

**Comment by Thanood** [comment]
No :point_up: ? :smiley:

**Comment by adriatic** [comment]
:+1:  :8ball:  :smile: :sake:
