### ISSUE TITLE
Implement modals

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#64]
So modals... :smile: 

Do we use aurelia-dialog from the start or implement "native" modals first?
I only had a quick look but it seems that it'd be quite easily adaptable to aurelia-dialog.

**Comment by adriatic** [comment]
I would advise against "plain inclusion" of Aurelia Dialog into Materialize plugin - our project should be completely independent of "official aurelia" despite the rumors of making our bridges to "play along" with Aurelia Interface. If and when that happens, we will deal with inter-dependencies when they will be clearly defined

**Comment by JeroenVinke** [comment]
When you decide to use materialize, you accept the features and limitations of it. So I would choose to implement native modals first, and when there is a demand we should look into integrating aurelia-dialog

**Comment by Thanood** [comment]
This is a bit more complicated then it looks..

There is an optional trigger button which can take some interesting arguments to configure the modal, f.i. callbacks to ```ready``` (modal is opened) or ```closed``` (modal is closed).

I'd prefer to use these as promises.

All of the above can be implemented using a "companion" attribute like with ```side-nav``` or even leaving the modal itself up to the user using pure html/css.

These options available for the trigger button can also be used in manual trigger function ```openModal()``` which - again - is not documented but present in materialize source.

https://github.com/Dogfalo/materialize/blob/master/js/leanModal.js#L172 shows that the button trigger activator (```leanModal```) only registers a ```click``` event which calls ```openModal()``` using its options.

So these options **can** be implemented both on the trigger and the modal itself.
This way, we could even construct our own trigger, being able to circumvent IDs completely (I don't like IDs, ever).

On the other hand, providing a simple custom attribute which activates a modal already present, would be much simpler for the end-user.

The best would probably be to provide both ways. And there it becomes complicated. :smile: 
We'd probably have to merge activator/modal options.
