### ISSUE TITLE
Implement scrollfire

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#67]
The sample to this needs [transitions](http://materializecss.com/transitions.html) implemented.

This is tricky. Although the original is imperative, I can imagine some (hopefully) nice declarative implementations.

Usage example:
```html
<div md-scrollfire-target="offset: 50; callback.bind: staggerList()">a list to be staggered</div>
```

Scrollfire itself is perhaps best suited as a container attribute (or a service, but that's not so pretty):
```html
<div md-scrollfire>
  <content-from-above />
</div>
```

All of the above is **untested**.

**Comment by JeroenVinke** [comment]
`<div md-scrollfire-target="offset: 50; callback.bind: staggerList()">a list to be staggered</div>`

that would be awesome :+1:

**Comment by Thanood** [comment]
I've tried it but I don't know if it's possible since Materialize uses:
```javascript
var callbackFunc = new Function(callback);
callbackFunc();
```
https://github.com/Dogfalo/materialize/blob/master/js/scrollFire.js#L33

I've actually never used the ```Function``` constructor but according to [MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Function) the body (last argument) has to be a string. So we cannot call the constructor with a function pointer. :disappointed: 

I'd be glad if anybody knew a workaround.

**Comment by Thanood** [comment]
We could provide an optional override of ```Materialize.scrollFire``` which also accepts function pointers as callbacks.

Given the current state of the Materialize project - really good PRs not even commented (it's rather sad) - this may be a nice addition in general. More work for us, but still nice if it makes sense.

Of course, this would be entirely optional. Configurable from ConfigBuilder with something like ```useWorkarounds()```.

**Comment by Thanood** [comment]
I gave this a shot and patched Materialize scollFire:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/a1388a1947e78f57f9975a5385b6ed9ba3e6c290/src/scrollfire/scrollfire-patch.js

Works quite well. :smile: 
But I'm not yet satisfied with the details of the implementation..
```javascript
target.get(0).au['md-scrollfire-target'].viewModel.callback
```
Is there a better way to get a view model of a dynamically added custom attribute from within a view model? No ```ref```s, I guess.

Also I'm really not sure about that patch-business...

**Comment by Thanood** [comment]
> Is there a better way to get a view model of a dynamically added custom attribute from within a view model?

I should read more.
I guess the answer is documented in KendoUI's bridge dev notes: ```@children``` :smile:

**Comment by adriatic** [comment]
> I guess the answer is documented in KendoUI's bridge dev notes

I am not sure that the answer is what you suggest above, since that situation arrives in "processing" the grid, where rows are using templates. In that case we use the Aurelia compiler to handle all cells in a given row.

However, the final answer should be provided by @JeroenVinke who authored that code.

**Comment by JeroenVinke** [comment]
I am not sure if the children decorator also observes custom attributes

**Comment by Thanood** [comment]
I'm also not sure but it takes a selector as an argument so I suppose it's not restricted to elements per se.
The Aurelia docs are not clear in this regard imo.

I will try it. :smile:

**Comment by Thanood** [comment]
Of course it does not work that way. Which view model would be referenced if there is more than one?
But this:
```javascript
child.au['my-attr'].viewModel
```

is imo still better than that:
```javascript
target.get(0).au['my-attr'].viewModel
```

and there's no jQuery required.

**Comment by Thanood** [comment]
I've submitted a PR with the funtioni reference changes:
https://github.com/Dogfalo/materialize/pull/2790

**Comment by Thanood** [comment]
That PR is not merged but the change is in.
I'm reopening this to remind myself to remove the workaround one Materialize releases a new version.

**Comment by Thanood** [comment]
0.97.6 is released now and supports function callbacks.
