### ISSUE TITLE
Implement scrollspy

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#68]
Not sure what to do with this. Please have a look at [the original sample](http://materializecss.com/scrollspy.html).

We could implement a custom attribute ```md-scrollspy``` and have the "table of contents" element constructed automatically. But then that may be too much.

But the actual implementation consist of a css class and an initialization method. That method is called for **all** elements "spied upon" so we'd need a wrapper?

I don't want this implementation to become more complicated than the original so please comment.

**Comment by JeroenVinke** [comment]
> But the actual implementation consist of a css class and an initialization method. That method is called for all elements "spied upon" so we'd need a wrapper?

yeah looks like it. It's not that every md-scrollspy could initialize on its DOM element so we'd need to do that with a custom element around it.

or perhaps something like this:

```
  <div class="row">
    <div class="col s12 m9 l10" md-scrollspy="target: .scrollspy">
      <div id="introduction" class="section scrollspy">
        <p>Content </p>
      </div>

      <div id="structure" class="section scrollspy">
        <p>Content </p>
      </div>

      <div id="initialization" class="section scrollspy">
        <p>Content </p>
      </div>
    </div>
    <div class="col hide-on-small-only m3 l2">
      <ul class="section table-of-contents">
        <li><a href="#introduction">Introduction</a></li>
        <li><a href="#structure">Structure</a></li>
        <li><a href="#initialization">Intialization</a></li>
      </ul>
    </div>
  </div>
```

**Comment by Thanood** [comment]
I like that idea. Looks quite flexible. :+1:
