### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-materialize-bridge#72]
Instead of depending on [aurelia-framework](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L34) we should instead mention all the individual things we depend on such as aurelia-templating or aurelia-binding. Basically whatever we use when we import things from Aurelia.

and then instead of importing everything from aurelia-framework:

`import { bindable, customElement, inject } from 'aurelia-framework';`

we should import more specifically:

```
import {bindable, customElement} from 'aurelia-templating';
import {inject} from 'aurelia-dependency-injection';
```

When we do the above, we must add a dependency on aurelia-templating and aurelia-dependency-injection here. This helps with the amount of forks people will get when they install the plugin.

Also, can you update all the version of Aurelia in package.json and config.js (both the plugin and the sample app) and also of core-js (to 2.0.3)?

**Comment by Thanood** [comment]
Whatever I do, jspm insist on npm:core-js@1.2.6.
Trying ```jspm resolve --only```. But I'd rather understand this. Any ideas?

**Comment by JeroenVinke** [comment]
did you update core-js [here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L43)? and then run jspm update?

If nothing else depends on 1.2.6 after that (check config.js), JSPM should remove 1.2.6 from your filesystem

**Comment by Thanood** [comment]
Yes, I did it that way. Getting:
```warn core-js@2.0.3 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.```

When I do this, it's reverted. I'm trying to not do this now. :smile:

**Comment by JeroenVinke** [comment]
Are you sure it's reverted? can you check in `jspm_packages/npm/` which versions of core-js there are? and perhaps share your config.js via [gist](gist.github.com)

**Comment by Thanood** [comment]
It is reverted.
```
Installed core-js as npm:core-js@^1.1.4 (1.2.6)
```
jspm_packages/npm/ has both versions.
config.js: https://gist.github.com/Thanood/c905d3abb43e91160c68

Will continue later.

**Comment by adriatic** [comment]
Daniel how do you invoke jspm?

Like this: `jspm install -y`

or

like this; `jspm install`

**Comment by Thanood** [comment]
I've used ```jspm install``` and also ```jspm update```. Everything is fine until I download the latest loaders.

I will try it again without downloading loaders, also I'll update jspm.

**Comment by Thanood** [comment]
After a bunch of ```jspm update```, ```jspm clean```, ```jspm install``` and ```jspm resolve --only npm:core-js@2.0.3``` I finally reached a state where everything is up2date and now jspm fails by constantly throwing timeouts at me. -.-

Last time I checked it was still complaining about core-js not being compatible. When that thing ever gets finished timing out, I'll just try a ```gulp watch``` and see if it runs, ignoring the warning.

**Comment by Thanood** [comment]
It works now, after having to find some of the imports (f.i. bindingMode).
Does anybody know if this is the "official" way to import ```LogManager```?
```javascript
import * as LogManager from 'aurelia-logging';
```

**Comment by adriatic** [comment]
It seems like we all have a bad jspm day. Yesterday, Jeroen updated the Aurelia-KendoUI-bridge to the two days old Aurelia version and that kills the Catalog app. This is still unexplained and I am mad as I wanted to get rid of some work that needs to be done on the master repository ASAP.

**Comment by Thanood** [comment]
Just for the record: I've pulled the changes to another machine (at work) and everything updated flawlessly, despite the fact that jspm is still warning me about an unsupported version of core-js.

It seems we can ignore this warning. At least for now.
