### ISSUE TITLE
add source-maps to plugin

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#8]
Currently, there are no source-maps created for the plugin itself. It would be very convenient having source-maps in the embedded catalog and later in dist builds.

What is the intention of not having them built? Does it cause any problems (f.i. with bundling/deployment)? If there are no concerns, I can add them.

Note: this probably also affects the plugin-builder.

**Comment by adriatic** [comment]
By source maps you mean the files that are used by Chrome to help with debugging (by presenting you the ES6 code, while running ES5 code itself)?

How are source maps generated?

**Comment by JeroenVinke** [comment]
I believe this is not done currently so that the payload is smaller. But since JSPM only downloads `dist/system` or `dist/amd` we can actually create an extra folder in there (`dev`) in which sourcemaps are generated. You can duplicate [this task](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/build/tasks/build.js#L57-L61) and enable sourcemaps on that

**Comment by Thanood** [comment]
Yes I mean the files that are used by Chrome to help with debugging.
I tried to find something like a reference implementation along the Aurelia repos but they don't seem to use source-maps.

@JeroenVinke I'll try to come up with something like that. I think if we do it this way then we also need to add a (server-side) route/virtual dir to that "dev" folder, right?
I've only used inline source maps so far.

If you'd like to take a look, I've uploaded my [typescript plugin playground](https://github.com/Thanood/skeleton-plugin-typescript/blob/master/build/tasks/build.js)

**Comment by Thanood** [comment]
I've tried using a new path but it seems it doesn't work taht way. It created the (es6) source files in a folder "dev" and sourcemaps along with them.

Now I've tried a different task, enhancing "build-system" as an example:
```javascript
gulp.task('build-system', function () {
  return gulp.src(paths.source)
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(to5(assign({}, compilerOptions, {modules:'system', plugins: []})))
    .pipe(sourcemaps.write('../dev', {
      includeContent: false,
      sourceRoot: '../es6',
      debug: true
    }))
    .pipe(gulp.dest(paths.output + 'system'));
});
```

That creates sourcemaps in "dev" using the "es6" folder as the sources and writing a reference to maps in the output of "build-system". To be able to use this I've created to new server-side routes in serve.js:

```javascript
options.server.routes['/src/' + 'dev'] = path.join(paths.output, 'dev');
options.server.routes['/src/' + 'es6'] = path.join(paths.output, 'es6');
```

That works but pollutes the "src" subtree (one level up from the plugin folder).
I don't think this is a good solution but maybe we'll find a better way.

Note: I decided to not upload these changes because it's basically changing the "orange box" as mentioned [here](https://github.com/aurelia-ui-toolkits/plugin-builder/issues/1).

**Comment by Thanood** [comment]
Maybe this is better. At least it "looks" cleaner:
```javascript
gulp.task('build-system', function () {
  return gulp.src(paths.source)
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(to5(assign({}, compilerOptions, {modules:'system', plugins: []})))
    .pipe(sourcemaps.write('../dev', {
      includeContent: false,
      sourceRoot: '../' + paths.packageName + '-es6',
      debug: true
    }))
    .pipe(gulp.dest(paths.output + 'system'));
});
```
