### ISSUE TITLE
move current content of help pages into the wiki

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#82]
Empty the bridge docs afterwards.

Missing docs:
- [x] About Aurelia (but I guess that would be the same anyway)
- [x] About materialize
- [x] Bridge developers notes

**Comment by adriatic** [comment]
The bridge developers notes should be created in sync with @rborosak as everything that is "target bridge independent" (across all bridges) should be in the [skeleton bridge](https://github.com/aurelia-ui-toolkits/skeleton-bridge) as well.

Both tutorial categories should be completely Materialize bridge specific Note that each tutorial comes with the finished code repository https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo and https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo

**Comment by Thanood** [comment]
KendoUI has some specific features in bridge developers notes (generation of bindables), which I find interesting. I thought it would be a good idea to document some Materialize specific thigs there, too.

Of course that doesn't stop us from having synced contents.

**Comment by adriatic** [comment]
It is very rewarding to see that you are not limiting your interest in Materialize bridge only as it was always my desire that we all know as much about what other team members to as possible. 

The concept of using any available metadata from the bridge target toolkit is one of the key property of our bridge implementations, so we should always seek to find a reliable way to do this (see **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/296)** and **[this](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/pull/310)** as examples)
