### ISSUE TITLE
possible future feature: color-management

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#9]
As I began working on waves I noticed that Materialize has added css classes corresponding to some colors of the material palette (waves-${color}). There are a few missing, like f.i. indigo.

Materialize uses sass for its css styles. These sass files contain a complete representation of the [Material color palette](https://www.google.com/design/spec/style/color.html#color-color-palette).

I guess, creating the ```waves-${color}``` classes should be quite easy. But I have no experience working with sass atm (I have been using less so far).
If we could somehow extract these colors to JSON we could probably even use them to generate a theme selector.

Theming in Material basically consists of defining the primary and accent colors and some hues along with standardized shadows and opacity (descibed [here](https://www.google.com/design/spec/style/color.html#color-themes)).

I tried [gulp-sass-json](https://www.npmjs.com/package/gulp-sass-json) to extract the variables to no avail.

**Comment by adriatic** [comment]
I am still way to inexperienced in Materialize to be able to comment this - planning to improve that as soon as I can :-)

**Comment by Thanood** [comment]
When the catalog UI is finished, we could simply declare a ```primary``` and ```accent``` color class in css (following material css style although I don't like that unprefixed style very much, tbh).
Then use them in custom attributes, which leads to everything being at least a custom attribute, even simple css-based components, like ```<button>```.

That way we can first implement a simple color-picker which would for example change the primary/accent colors directly using string interpolation on the above mentioned styles. This works at least with inline ```<style>``` definitions (as I've done [here](https://github.com/Thanood/aurelia-mdl-skeleton-navigation/blob/master/src/aurelia-mdl/css-tweaks/mdl-ripple.html)).

From that color-picker we could then build the theme-selector, presenting themes from Materialize (default), Polymer, Muicss, React Material-UI and anything other color themes we'd come across.

But first, I'd like to come up with something which handles setting (and removing) component's classes in a more advanced way, depending on what users have set before our bridge takes control. :smile:

**Comment by adriatic** [comment]
I would like to see comments from other team members here please - as we already agreed on using the `ma` prefix. Now we need to decide all places where this prefix will be used

**Comment by Thanood** [comment]
Could use this as an inspiration: https://material.angularjs.org/latest/Theming/05_under_the_hood

**Comment by Thanood** [comment]
I took a first shot at it here: [color-management branch](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/tree/color-management)

**Comment by Thanood** [comment]
I'm making progress with color-management, although my solution is still a bit cobbled togeher, it works.
I'm wondering if I should merge it in already. It's certainly nowhere near best practice but a nice feature to show when we get to do #39.

**Comment by adriatic** [comment]
Re https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/9#issuecomment-175040175

I would suggest to push all this code in the repo as it really shows nice. We could always change it if needed later.

**Comment by Thanood** [comment]
Not a future feature anymore.. ;-)
