### ISSUE TITLE
docs: use the bridge name consistently: Aurelia Materialize bridge

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#90]
Currently, there are several spellings in use:
* Aurelia-Materialize-Bridge
* Aurelia Materialize Bridge
* Aurelia-Materialize bridge
* Aurelia Materialize bridge
* Materialize bridge

**Comment by adriatic** [comment]
Github enforces the use of the form `string of dash connected words` and I believe that you cannot go wring with "everything lower case" either. So I propose aurelia-materialize-bridge in all contexts that might be used as the reference to Github repository

I would use `Aurelia Materialize bridge` in the context of an article that describes this tool, though

**Comment by Thanood** [comment]
This issue is all about the documentation. Mentioning just to be clear. :smile: 

I will take whatever you intend to use for KendoUI, so that we have consistent naming. ```Aurelia Materialize bridge``` it is, then.
