### ISSUE TITLE
Implementing the catalog navigation

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#91]
The purpose of this issue is to document how the catalog navigation has been implemented, for use in bridge dev notes and as a possible guidance for other bridge developers who like to do something similar.

At the time of writing, ```project status``` is the only view which hosts links to Aurelia Materialize bridge components. There is no convenient catalog navigation like in KendoUI bridge.
(and this is also the reason why the "component catalog" documentation is still missing)

The project status view already has a ```categories``` array in place which holds a dictionary per component category along with implemented components and their status.

All component sample pages share a view ```shared/showcase``` - a perfect place to implement a sub-navigation for our components.

For Aurelia Materialize bridge we've decided to implement a side-nav with component categories with the goal to provide a similar look&feel of the original Materialize website.

Because of this, the following side-nav has been added to ```showcase.html```:
```html
<md-sidenav view-model.ref="sideNav" md-fixed="true" md-edge="left">
    <ul md-collapsible="accordion: true;" repeat.for="cat of categories">
      <li>
        <div md-waves class="collapsible-header">${ cat.title }<i class="mdi-navigation-arrow-drop-down right"></i></div>
        <div class="collapsible-body">
          <ul>
            <li repeat.for="ctrl of cat.controls" md-waves>
              <span show.bind="!!ctrl.link"><a href.bind="ctrl.link">${ ctrl.title }</a></span>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </md-sidenav>
```

Which maybe raises the question: where do we get the ```categories``` array from? For this purpose we've introduced a new file ```showcase.js``` with a ```Showcase``` class acting as a **base class for all component index pages**.

```javascript
import { Controls } from '../project-status/controls';

export class Showcase {
  constructor() {
    this.categories = new Controls().categories;
  }
}
```

Here's an example of a inheriting class:
```javascript
import { useView } from 'aurelia-framework';
import { Showcase } from 'shared/showcase';

@useView('shared/showcase.html')
export class Index extends Showcase {
  configureRouter(config, router) {
    config.title = 'Waves';
    config.map([
      { route: ['', 'basic-use'], moduleId: './basic-use', nav: true, title: 'Basic use' },
      { route: 'colors', moduleId: './colors', nav: true, title: 'Colors' }
    ]);

    this.router = router;
  }
}
```

Currently, this class imports the categories array from ```project-status``` and provides that array to inheriting classes. This way, ```showcase.html``` - which is already the "base view" of all component pages - is able to provide the current set of implemented components to the side-nav.

Three issues as of now:
- [x] categories should better be imported from a service
- [x] the side-nav is re-rendered every time which leads to the active category being closed when navigating to another component (time to implement ```panelBar```?)
- [x] although ```accordion: true``` is set, the side-nav categories don't act like accordions

**Comment by Thanood** [comment]
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/677826/12868195/77b7302c-cd01-11e5-9ffa-9fd2bd66ad48.png)

**Comment by Thanood** [comment]
Mimic KendoUI bridge like here:
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/samples/index.js

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/samples/menu.json

**Comment by Thanood** [comment]
:point_up: [6. Februar 2016 19:12](https://gitter.im/aurelia-ui-toolkits/aurelia-materialize-bridge?at=56b637a49c53e6696d4881ca)

**Comment by Thanood** [comment]
I just changed the implementation to use a [menu.json](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/samples/menu.json) like structure to compose both ```project-status``` and the side-nav.

Furthermore I have changed the side-nav to be included in ```samples.html```, rather than ```showcase.html```. Therefore, ```showcase.js``` is gone (it's now effectively ```menu.js```) and doesn't act as a base class anymore.

This solves the re-rendering problem of side-nav, since it is now a single component included in a single top-level view.

I had to transform the data structure into an array which could be consumed by Aurelia's ```repeat.for```. I've also tried a map but it didn't work - the code is still there but inactive. Aurelia didn't recognize the Map as a Map (```instanceof items != Map```), although Chrome debugger clearly stated that it is a Map.

I'm using some conventions to keep the menu data small:
* if a component doesn't have status information, there is no link to a sample page
* otherwise there will be a link unless ```"nav": false``` is set
* the link is derived from the lower-case ```title``` of the component unless there is a ```moduleId``` defined
* ```moduleId```s are "relative" which means it's f.i. ```button``` rather than ```samples/button/index``` (because the samples/*/index portion is the same everywhere)

Components are now provided by a ```componentService``` in ```shared```.

There are other issues I've overlooked:
- [ ] there are now two side-navs on smaller displays and the collapse button only shows the main navigation
- [ ] paddings (needed for fixed side-navs) are still present when the side-nav is hidden

**Comment by Thanood** [comment]
What I'd like to know is if what I did is general enough to be included in skeleton-bridge.

I'd also like to do a generic sample-runner equivalent later.

**Comment by adriatic** [comment]
ping @rborosak 
ping @JeroenVinke 

This issue warrants a discussion with the two people above - and while not directly related to catalog navigation, please also check https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/333 since it is a part of skeleton bridge code

**Comment by Thanood** [comment]
The menu will now be updated correctly, when called from Aurelia's router.
