### ISSUE TITLE
write bridge developers notes

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#92]
TOC proposal:
- [ ] 1. Introduction
- [ ] 2. Bridge utilities
- [ ] 3. Babel DTS generator
- [ ] 4. AttributeManager
- [ ] 5. Problems (and solutions) implementing select
- [ ] 6. Bundling
- [ ] 7. Theming and colors

probably more to come, still gathering information

**Comment by adriatic** [comment]
can you try to fit your proposal into the KendoUI help structure - as the consistent UI is always appreciated?

![image](https://cloud.githubusercontent.com/assets/2712405/12891800/2fd5184e-ce57-11e5-8792-8a6e8413f48d.png)

**Comment by Thanood** [comment]
I don't understand. The above is the table of contents for the Bridge developer notes (last category in your screen). Everything else - the structure you've posted - stays the same.

If you're concerned about the notes' structure then I've only left out kendo-specific topics:
* Generation of bindables
* Grid HTML API
* Template compilation

The Babel DTS generator topic is missing, but not on purpose. I'll edit the original post and put it back in.

**Comment by adriatic** [comment]
> I don't understand. The above is the table of contents for the Bridge developer notes only 

That just tells me that it is me who does not understand :-) - as I completely missed the title of this issue (write bridge developers notes). So, I created a nice recursion for you - sorry Daniel

**Comment by Thanood** [comment]
No problem. Aside from me liking recursions most of the time, that happens to me all the time. Mostly on forums. :smile:
