### ISSUE TITLE
Implement breadcrumbs

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#93]
[Breadcrumbs](http://materializecss.com/breadcrumbs.html) consist of simple css classes. Combined with a bound router, though, they could be auto-generated using the current route instruction and its parent(s).

This would probably end up as a custom element since we'd have to implement a repeated list of router instructions:
```html
<md-breadcrumbs router.bind="router"></md-breadcrumbs
```

Translating to (depending on the current route):
```html
<a href="#samples/" class="breadcrumb">Samples</a>
<a href="#samples/dialogs/" class="breadcrumb">Dialogs</a>
<a href="#samples/dialogs/tooltips/" class="breadcrumb">Tooltips</a>
```

This would be an entirely optional element, to be used along Aurelia router. The basic usage would still consist of manually added css classes.

**Comment by Thanood** [comment]
Just discovered this: https://github.com/heruan/aurelia-breadcrumbs :smile:

**Comment by adriatic** [comment]
Interesting find. I was quite successful finding things by searching `aurelia xxx`, so I am glad you do the same

**Comment by Thanood** [comment]
I do that like every other day.. :smile: 
Even found an interesting project in its infancy: Aurelia RTE.. ;-)

**Comment by adriatic** [comment]
RTE stands for Arelia Real Time Editor which is the beginning of a "possible" but not yet confirmed project initiated by yours truly :-)

**Comment by Thanood** [comment]
It's implemented but I'm having problems navigating.

```javascript
this.router.navigateToRoute(navigationInstruction.config.name);
```

The line above constantly throws errors: "route not found".
Will have to investigate that further.
