### ISSUE TITLE
Write bridge documents

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#96]

**Comment by Thanood** [comment]
This one was created by an Asana extension. :smile:

**Comment by adriatic** [comment]
Asana extension?

**Comment by Thanood** [comment]
Yeah, more of a connector. I just tried to connect [Asana](https://asana.com) to GitHub. Not as good as I thought, though.

**Comment by adriatic** [comment]
I used to like Asana a lot, but finally gave up because of their (performance based) decision to use only ASCII characters

**Comment by Thanood** [comment]
I'm not convinced of it either. I'm primarily looking for a task/project manager to track non-github things. GitHub integration would just be a plus..
