### ISSUE TITLE
Improve Installation/Quick Start

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#99]
The list of all components included gets very long.
Maybe show ```useAll()``` first, then show the complete list.

**Comment by adriatic** [comment]
This issue seems not to be written for sharing - but rather as a "self-reminder", right?

**Comment by Thanood** [comment]
Right. :smile: 
But for the sake of sharing, this is too long in my opinion
:
```javascript
.plugin('aurelia-materialize-bridge', bridge => {
    bridge
      .useBox()
      .useButton()
      .useCard()
      .useCarousel()
      .useCheckbox()
      .useCollapsible()
      .useColors()
      .useDropdown()
      .useModal()
      .useNavbar()
      .useParallax()
      .usePushpin()
      .useScrollfire()
      .useScrollSpy()
      .useSelect()
      .useSidenav()
      .useSlider()
      .useSwitch()
      .useTabs()
      .useTooltip()
      .useTransitions()
      .useWaves()
      .useWell();
  });
```
Source: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/src/installation/installation.md

**Comment by adriatic** [comment]
Yes, reversing the order is better - specific enumeration is a solution for people that always try to squeeze everything to get better performance. 

Use Aurelia configuration as the good guidance for this
